### PR TITLE
Grafana dashboards old templating datasource

### PR DESCRIPTION
**Pull request by albundy83**
Subject:
Fix for `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found`

Problem:
When we try to manually import Grafana dashboards, we have the following error `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found` when we open the dashboard once imported.

Solution:
Add this to each dashboard:
```yaml
      {
        "hide": 0,
        "label": "datasource",
        "name": "DS_PROMETHEUS",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      },
```

It also fix dashboards that were not working with [kube-prometheus-stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

Validation

Fixes [10873](https://github.com/linkerd/linkerd2/issues/10873)

Signed-off-by: Grégoire Bellon-Gervais <greggbg@gmail.com>

### CODE REVIEW

**Comment by albundy83** [comment]
Any comment, is it something that could be approved ?

**Comment by alpeb** [comment]
@albundy83 the diff is looking pretty big for some files, perhaps a formatting issue? Also it seems there are other changes besides the datasource templating one? Can you please make it so the diff is minimal and we can focus on reviewing the datasource change?

**Comment by albundy83** [comment]
Hello,
 yes for most of the dashboards modifications are:
```json
"datasource": "${DS_PROMETHEUS}",
```
becoming:
```json
"datasource": {
  "type": "prometheus",
  "uid": "${datasource}"
},
```
and an add to be able to template datasource (as some users have more than one Prometheus configured:
```json
{
  "current": {
    "text": "default",
    "value": "default"
  },
  "hide": 0,
  "label": "Data Source",
  "name": "datasource",
  "options": [],
  "query": "prometheus",
  "refresh": 1,
  "regex": "",
  "type": "datasource"
},
```
There are also updates on dashboards that need more work to make them work correctly:
kubernetes.json, multicluster.json, prometheus-benchmark.json, replicaset.json.
Finally, to be able to use prometheus.json (the one called Prometheus 2.0 Stats) dashboard with kube-state-metrics, we need to change its name from prometheus.json to prometheus-20-stats.json for example.
If not, it can't be loaded in Grafana automatically as it already exists in their repo: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml

I can rollback some of the modifications and perform others pulls if you prefer.
Just tell me :)

**Comment by alpeb** [comment]
@albundy83 I tested your changes for the datasource-specific fixes with a couple of dashboards and it works for me, both through the usual loading and using ConfigMaps :+1: 
So yes, please open separate PRs for the other issues. I think the prometheus chart can be named something like `prometheus-linkerd.json`.

**Comment by albundy83** [comment]
Ok I m lost in rebase, closing this one ...

**Comment by albundy83** [comment]
@alpeb sorry, the good pull request is here now: https://github.com/linkerd/linkerd2/pull/11017
Rebasing just killed me again ...

**Pull request closed without merging**
