### PR TITLE
Bump node version to v20

### PR DESCRIPTION
**Pull request by mateiidavid**
lingui/cli manages locales, extracts messages from source files and compiles message catalogs for production use. Dependabot's bump seems to fail since lingui/cli requires at least node v16, and the current Dockerfile uses node v14.

This change updates the web dockerfile to use node v20 and also configures the JS web test runner to use node v20.

Lingui/cli's migration docs are covered in
https://lingui.dev/releases/migration-4#backward-incompatible-changes for migrating from v3.x.x to v4.x.x.

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
LGTM, but my understanding is that bookworm is the latest Debian stable, did you try using that?

**Comment by mateiidavid** [comment]
ah, good spot, I've fallen off the debian release chart. I haven't but I think it's safe to use bookworm, the runtime for node is still the same.

**Review by alpeb — APPROVED** [review]

**Review by adleong — COMMENTED** [review]
It looks like codecov.yml also uses `node:14-stretch`.  Do we want to update that as well?

**Comment by mateiidavid** [comment]
> It looks like codecov.yml also uses `node:14-stretch`. Do we want to update that as well?

That's probably a good idea, updated the PR.

**Review by adleong — APPROVED** [review]

**Pull request merged**
