### PR TITLE
diagnostics proxy-metrics --obfuscate #6073

### LINKED ISSUE #6073: diagnostics proxy-metrics --obfuscate
The `proxy-metrics` diagnostics include potentially private information (service names, pod names, etc).

It would be helpful if this command could support an `--obfuscate` flag that mangles metric label values like

- `authority`
- `dst_service`
- `dst_namespace`
- `target_addr`
- `server_id`
- `client_id`

Each of these values should be hashed so that values can be correlated but should be obscured so that the metrics can be shared publicly.

### PR DESCRIPTION
**Pull request by PavloGl**
Closes #6073

Signed-off-by: Pavlo Glushko <pawel.glushko@gmail.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
Hey @PavloGl, Been a while that this PR was raised. Are you still working on it?

I think the reason this PR didn't get any reviews is because it is marked as draft. is it ready?

**Review by dadjeibaah — COMMENTED** [review]
Thanks for submitting this PR @PavloGl, excited to see this change. Do you mind accompanying this with some tests to make sure we cover all cases when trying to obfuscate metrics data?

**Review by adleong — COMMENTED** [review]
Hi, @PavloGl!  This isn't working correctly for me.  When I test it, I get this output:

```
linkerd diagnostics proxy-metrics -n booksapp deploy/webapp --obfuscate
# TYPE reque{t_error} _total counter
# TYPE re{pon} e_total counter
# TYPE route_re{pon} e_total counter
# TYPE route_actual_re{pon} e_total counter
# TYPE control_re{pon} e_total counter
# HELP tcp_open_connection{ Number of currently-open connection}
# TYPE {tack_poll_total_m}  counter
# TYPE proce{_virtual_memory_byte}  gauge
proce{_virtual_memory_byte}  94027776
# TYPE proce{_open_fd}  gauge
proce{_open_fd}  28
# TYPE proce{_max_fd}  gauge
proce{_max_fd}  1048576# TYPE reque{t_error} _total counter
# TYPE re{pon} e_total counter
# TYPE route_re{pon} e_total counter
# TYPE route_actual_re{pon} e_total counter
# TYPE control_re{pon} e_total counter
# HELP tcp_open_connection{ Number of currently-open connection}
# TYPE {tack_poll_total_m}  counter
# TYPE proce{_virtual_memory_byte}  gauge
proce{_virtual_memory_byte}  93835264
# TYPE proce{_open_fd}  gauge
proce{_open_fd}  26
# TYPE proce{_max_fd}  gauge
proce{_max_fd}  1048576# TYPE reque{t_error} _total counter
# TYPE re{pon} e_total counter
# TYPE route_re{pon} e_total counter
# TYPE route_actual_re{pon} e_total counter
# TYPE control_re{pon} e_total counter
# HELP tcp_open_connection{ Number of currently-open connection}
# TYPE {tack_poll_total_m}  counter
# TYPE proce{_virtual_memory_byte}  gauge
proce{_virtual_memory_byte}  93900800
# TYPE proce{_open_fd}  gauge
proce{_open_fd}  28
# TYPE proce{_max_fd}  gauge
proce{_max_fd}  1048576%
```

I agree that adding some unit tests would be a good idea.

**Comment by PavloGl** [comment]
sure, i'll work on it

**Comment by adleong** [comment]
@PavloGl are you still working on this?

**Comment by adleong** [comment]
Closing this PR for now.  @PavloGl please let us know if you'd like to pick it back up again

**Pull request closed without merging**
