### PR TITLE
Make labels of multicluster components consistent

### LINKED ISSUE #4511: multicluster component labels are inconsistent
```
:; kubectl --context=k3d-dev get po -n linkerd-multicluster --show-labels                                   
NAME                                      READY   STATUS    RESTARTS   AGE   LABELS
linkerd-service-mirror-768646f4cc-9qxjr   2/2     Running   0          10m   linkerd.io/control-plane-component=linkerd-service-mirror,linkerd.io/control-plane-ns=linkerd,linkerd.io/proxy-deployment=linkerd-service-mirror,linkerd.io/workload-ns=linkerd-multicluster,pod-template-hash=768646f4cc
linkerd-gateway-7c84577c55-t4xbq          2/2     Running   0          10m   app=linkerd-gateway,linkerd.io/control-plane-ns=linkerd,linkerd.io/proxy-deployment=linkerd-gateway,linkerd.io/workload-ns=linkerd-multicluster,pod-template-hash=7c84577c55
```

The gateway component lacks a `linkerd.io/control-plane-component` label. It seems like it should have one.

The `service-mirror` component has an inconsistent control-plane-component value. It should be `service-mirror` and not `linkerd-service-mirror` to be consistent with other components:
```
:; kubectl --context=k3d-dev get po -n linkerd --show-labels             
NAME                                      READY   STATUS    RESTARTS   AGE   LABELS
linkerd-identity-6645679c5b-mz2lz         2/2     Running   0          12m   linkerd.io/control-plane-component=identity,linkerd.io/control-plane-ns=linkerd,linkerd.io/proxy-deployment=linkerd-identity,linkerd.io/workload-ns=linkerd,pod-template-hash=6645679c5b
linkerd-web-b767fc89c-m7pn7               2/2     Running   0          12m   linkerd.io/control-plane-component=web,linkerd.io/control-plane-ns=linkerd,linkerd.io/proxy-deployment=linkerd-web,linkerd.io/workload-ns=linkerd,pod-template-hash=b767fc89c
linkerd-destination-7994f6b94f-fcvzv      2/2     Running   0          12m   linkerd.io/control-plane-component=destination,linkerd.io/control-plane-ns=linkerd,linkerd.io/proxy-deployment=linkerd-destination,linkerd.io/workload-ns=linkerd,pod-template-hash=7994f6b94f
...
```

This was tested on `edge-20.5.4` (so may have changed since)

### PR DESCRIPTION
**Pull request by zaharidichev**
This PR fixes the inconsistency in component labels.

Fix #4511

Signed-off-by: Zahari Dichev <zaharidichev@gmail.com>

### CODE REVIEW

**Comment by zaharidichev** [comment]
@adleong I am just trying to follow what the pattern is with control plance resources. I guess this helps with cleanup, etc? Doesn't that make sense?

**Comment by adleong** [comment]
Totally!  I'm all for consistency.  However, the controller component label is mostly used for the purposes of `linkerd uninstall` so we need to think through how that would work here.

**Comment by zaharidichev** [comment]
@adleong So I guess we need to start off from the result we want. So when we do uninstall on a cluster that has linkerd + multicluster we can do all of: 

- delete the gateway
- delete linkerd control plane
- delete the service mirror controller
- delete the linkerd-multicluster namespace
- delete all the mirrored services

Does that sound correct and if it does does it mean we need to ass this label to the mirrored services as well ?

**Comment by adleong** [comment]
As discussed today, I think we can close this PR for now.  In the future we will need to have a larger discussion about how uninstall should work for addons.  In the meantime, `linkerd multicluster install | kubectl delete -f -` is the recommended way to uninstall the multicluster addon.

**Pull request closed without merging**
