### PR TITLE
Upgraded `Helm` cli to v2.16.1

### PR DESCRIPTION
**Pull request by alpeb**
Needed for k8s 1.16

### CODE REVIEW

**Comment by grampelberg** [comment]
Should we go to v3 now?

**Comment by cpretzer** [comment]
Can we support both? My guess is that some long-time helm users may not be able to migrate to v3 very quickly, and the option to use v2 or v3 would help them.

**Comment by grampelberg** [comment]
> Can we support both?

Yes, but the details matter. I'd prefer to support one or the other purely from an effort perspective. We could hold off officially supporting v3 until users start running into problems. I just wanted to make sure we were thinking about it.

**Comment by cpretzer** [comment]
Makes sense to me!

**Comment by alpeb** [comment]
We do support both from the user's perspective. This change just determines the version against which the Helm integration tests are run, which is set in `/bin/helm`'s `helmversion` var. It would require some other changes for the tests to run against v3.
I could make those changes, to apply conditionally depending on the value of `helmversion`, so we can still run the tests against both versions.

**Comment by cpretzer** [comment]
Thanks for the explanation @alpeb

**Pull request merged**
