### PR TITLE
Multicluster: Uninstall multicluster without Linkerd control plane

### LINKED ISSUE #5624: multicluster extension cannot be uninstalled if Linkerd is not installed
If the main Linkerd control plane has been uninstalled, it is no longer possible to uninstall the multicluster extension.  

Uninstalling the multicluster extension should not required the main control plane.

```
bin/linkerd mc uninstall | k delete -f -
Error: you need Linkerd to be installed in order to install multicluster addons
Usage:
  linkerd multicluster uninstall [flags]
```

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>

Problem
If the main Linkerd control plane has been uninstalled, it is no longer possible to uninstall the multicluster extension.
```
$ bin/linkerd mc uninstall | k delete -f -
Error: you need Linkerd to be installed in order to install multicluster addons
Usage:
  linkerd multicluster uninstall [flags]
```
Solution
Fetch resources with the label `linkerd.io/extension: linkerd-multicluster` and delete them

Fixes #5624

### CODE REVIEW

**Comment by piyushsingariya** [comment]
These are the resources being deleted till now.

- [ ] namespace "linkerd-multicluster" deleted
- [ ] configmap "linkerd-gateway-config" deleted
- [ ] deployment.apps "linkerd-gateway" deleted
- [ ] service "linkerd-gateway" deleted
- [ ] serviceaccount "linkerd-gateway" deleted
- [ ] clusterrole.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
- [ ] serviceaccount "linkerd-service-mirror-remote-access-default" deleted
- [ ] clusterrolebinding.rbac.authorization.k8s.io "linkerd-service-mirror-remote-access-default" deleted
- [ ] customresourcedefinition.apiextensions.k8s.io "links.multicluster.linkerd.io" deleted

**Review by alpeb — COMMENTED** [review]
`FetchKubernetesResources` returns the cluster-scoped resources with the given label, which includes the namespace. So deleting all that, including the namespace, will also get rid of the namespace-scoped resources :+1:

**Comment by piyushsingariya** [comment]
This means the resources that are not being mentioned while deletion, are actually being deleted??
> `FetchKubernetesResources` returns the cluster-scoped resources with the given label, which includes the namespace. So deleting all that, including the namespace, will also get rid of the namespace-scoped resources +1

**Comment by alpeb** [comment]
> This means the resources that are not being mentioned while deletion, are actually being deleted?? 
> 
> > `FetchKubernetesResources` returns the cluster-scoped resources with the given label, which includes the namespace. So deleting all that, including the namespace, will also get rid of the namespace-scoped resources +1

Correct.

**Review by adleong — APPROVED** [review]
Awesome!

Just something to note here: people who installed the multicluster extension at a previous version will not have this label and therefore `linkerd multicluster uninstall` will not work.  They would have to first upgrade the multicluster extension by running `linkerd multicluster install | kubectl apply -f -` to get the label, and then they would be able to run `linkerd multicluster uninstall | kubectl delete -f -`.

This can leave them in a particularly sticky situation if they don't have a working LInkerd control plane since they won't be able to upgrade, and therefore they won't be able to uninstall.  I'm not sure there's much we can easily do about this situation, however.

**Review by kleimkuhler — APPROVED** [review]
This works well @piyushsingariya, thanks!

**Pull request merged**
