### PR TITLE
Update "linkerd-version" check

### PR DESCRIPTION
**Pull request by mayankshah1607**
Fixes https://github.com/linkerd/linkerd2/issues/3973

- Update check command to throw a warning when it fails to determine
latest version

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

### CODE REVIEW

**Comment by mayankshah1607** [comment]
@zaharidichev yes, that makes a lot more sense. I was thinking we could add a method in `version` that pings the `checkURL` for some response; if a network error is returned, we could directly throw a `SkipError` before proceeding with the check. Does that sound good?

**Comment by zaharidichev** [comment]
@mayankshah1607 Can't you just use the potential errore returned by `version.GetLatestVersions` ? Seems like it will include information about the status code: https://github.com/linkerd/linkerd2/blob/master/pkg/version/channels.go#L67. Seems more reasonable than introduing a separate ping method. WDYT?

**Comment by adleong** [comment]
I'm not sure there's a meaningful difference between not being able to reach the version check endpoint vs some other error coming from the version check endpoint.  Both cases seem like they should be a warning to me.

**Comment by zaharidichev** [comment]
well okey then, lets simply make it a warning

**Pull request merged**
