### PR TITLE
Multi grafana prometheus datasource support

### LINKED ISSUE #6043: Centralized Grafana is not supporting Dashboards
### What is the issue?
Grafana dashboard is currently supporting into hardcoded data source name prometheus only. It will not work directly in external Grafana and Prometheus

### How can it be reproduced?
 Most of the Grafana default datasource will be Prometheus (Please note Capital letter begin with). So we need to duplicate datasource with small letter names like prometheus to work with external Prometheus and Grafana. But this will not help when we are using centralized Grafana to get metrics from multiple Kubernetes environments

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: Any
- Cluster Environment:  AKS
- Host OS: ubuntu
- Linkerd version: Any

### Possible solution
Add a Datasource as variable

### PR DESCRIPTION
**Pull request by jijeesh**
Subject
Support Multi Prometheus Datasource

Problem

Grafana dashboard is currently supporting into hardcoded data source name prometheus only. It will not work directly in external Grafana and Prometheus

Solution

Add a Datasource as a variable  into each  Linkerd dashboard

Validation

Fixes #6043 

DCO Sign off

Signed-off-by:  Jijeesh K A <jijeesh.ka@gmail.com>

### CODE REVIEW

**Comment by alpeb** [comment]
Thanks @jijeesh. Besides setting `datasource` as a variable, I see you're trying to create a chart? Can you explain that part?

**Comment by jijeesh** [comment]
> Thanks @jijeesh. Besides setting `datasource` as a variable, I see you're trying to create a chart? Can you explain that part?

The Grafana chart is used to help to add the Linkerd dashboard into the external Grafana automatically. I have added a namespace in the 'values.yaml' file where the Prometheus Grafana is installed.

**Comment by jijeesh** [comment]
> > Thanks @jijeesh. Besides setting `datasource` as a variable, I see you're trying to create a chart? Can you explain that part?
> 
> The Grafana chart is used to help to add the Linkerd dashboard into the external Grafana automatically. I have added a namespace in the 'values.yaml' file where the Prometheus Grafana is installed.

**Comment by jijeesh** [comment]
accidentally closed this pull request

**Comment by Pothulapati** [comment]
image


This change seems to add the following label in the dashboard here but what should the query be here so that the options are genereated? for data sources. Is there a way to do this? 🤔

**Comment by jijeesh** [comment]
> This change seems to add the following label in the dashboard here but what should the query be here so that the options are genereated? for data sources. Is there a way to do this?

let me understand your question..
It will show the query based on which dashboard is selected like below.
image

**Comment by alpeb** [comment]
I'm wondering the same thing as @Pothulapati ; where do those options come from? Would the user need to edit the grafana json files to put those options in?

**Comment by jijeesh** [comment]
> I'm wondering the same thing as @Pothulapati ; where do those options come from? Would the user need to edit the grafana json files to put those options in?

No need to edit Grafana JSON by the user. This option will automatically be listed there based on the number Prometheus datasource added in the Grafana

I am creating datasource as a variable. so that it will query from the default datasource that exists in the Grafana when it took. 
This dropdown will get a list of datasources available in that Grafana and users can choose which Prometheus want to get a query. 

As per my scenario , we have centralized Grafana is connected to different cluster's Prometheus as data source.
Ex: dev,qa,uat and production. 
It will not work when the hardcoded data source. That is why I changed like this.



image

**Comment by alpeb** [comment]
Thanks for your efforts on this @jijeesh . However we've decided to not to follow this direction. The Grafana charts we provide are more for people to get started, and we expect folks to draw on them to build charts more specific to their needs. As such, we'd like to keep them as simple as possible, without trying to cater for very specific needs like the current PR attempts to. As a matter of fact, we're thinking at some point to push these charts in some sort of Grafana charts repo people can retrieve them from, and also contribute with different approaches, uncoupling them from the linkerd repo itself. Anyways, thanks again, these discussions are always appreciated!

**Comment by jijeesh** [comment]
No issue.. 
I am expecting the Grafana chart should easily pluggable to external Grafana other than the hard-coded Prometheus data source name.
I have experienced external Grafana has many Prometheus clusters data sources. That is why I changed it to the variable. Thanks for the reply.

**Pull request closed without merging**
