### PR TITLE
Allow args to be passed to Jaeger (#6587)

### LINKED ISSUE #6587: Allow args to be passed to Jaeger in Linkerd-Jaeger Helm chart
## Feature Request
Allow args to be passed to Jaeger in linkerd-jaeger helm chart

### What problem are you trying to solve?
The Jaeger-all-in-one deployed by the Linkerd-Jaeger Helm chart has unbounded limits and uses memory as the default storage mechanism. When this chart is deployed and Jaeger is receiving traces, it continues to use memory until there is no free memory on the host as old traces effectively never get purged. Upon looking deeper into Jaeger, I discovered they support passing arguments that allow you to restrict the maximum number of traces jaeger will keep in memory, effectively mitigating this issue. However, the Linkerd-Jaeger helm chart does not support passing arguments to the container, and there for unable to control jaegers memory usage (along with dozens of other arguments Jaeger has available). 

### How should the problem be solved?
Updating the Linkerd-Jaeger helm chart to support passing args to the Jaeger container from values.yaml. 

What do you want to happen? Add any considered drawbacks.
Arguments from values.yaml to be passed to Jaeger container in Linkerd-Jaeger chart. 

### Any alternatives you've considered?
No, passing arguments via values.yaml is pretty common practice. 

Is there another way to solve this problem that isn't as good a solution?
Not that I am aware of.

### How would users interact with this feature?
By overriding helm values during chart install. 

If you can, explain how users will be able to use this. Maybe some sample CLI
output?
Configuring something like the below in values.yaml
```yaml
jaeger:
  args:
    - --memory.max-traces=2000
```
or from helm cli like this:
```--set args={--memory.max-traces=2000}```

### PR DESCRIPTION
**Pull request by bsord**
Subject
Allow args to be passed to Jaeger

Problem
The Jaeger-all-in-one deployed by the Linkerd-Jaeger Helm chart has unbounded limits and uses memory as the default storage mechanism. When this chart is deployed and Jaeger is receiving traces, it continues to use memory until there is no free memory on the host as old traces effectively never get purged. Upon looking deeper into Jaeger, I discovered they support passing arguments that allow you to restrict the maximum number of traces jaeger will keep in memory, effectively mitigating this issue. However, the Linkerd-Jaeger helm chart does not support passing arguments to the container, and there for unable to control jaegers memory usage (along with dozens of other arguments Jaeger has available).

Solution
Updating the Linkerd-Jaeger helm chart to support passing args to the Jaeger container from values.yaml.

Validation
```sh
git clone https://github.com/bsord/linkerd2/
git checkout helm-jaeger-aio-args-support
cd linkerd2/jaeger/charts/linkerd-jaeger
helm install -n linkerd-jaeger --set namespace=linkerd-jaeger --set installNamespace=false --set webhook.image.version=stable-2.10.2 --set args={--memory.max-traces=2000} linkerd-jaeger .

Kubectl describe the pod, validate arguments match what was passed. 
```

Fixes #6587

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
Thanks, @bsord!  I don't think the helm templating you have here is quite right.  When I test with values:

```
  args:
    foo: bar
    bas: 10
```

this is rendered as:

```
      containers:
      - args:
        
        - 10
        
        - bar
        
        image: jaegertracing/all-in-one:1.19.2
```

**Comment by bsord** [comment]
the args would be pass like this:

```
values:
  jaeger:
    args:
      - --memory.max-traces=2000
      - --collector.num-workers=100
```

**Comment by bsord** [comment]
Or, alternatively like this. 
```
values:
  jaeger:
    args:
      - --memory.max-traces
      - 2000
      - --collector.num-workers
      - 100
```

**Comment by adleong** [comment]
Ah, I see!  Should the default value of the args value be `[]` instead of `{}` to indicate that it is a list?  I think you can also cut down on the extraneous whitespace in the rendered template:

```
        {{- range .Values.jaeger.args }}
        - {{ . -}}
        {{ end }}
```

**Comment by bsord** [comment]
Good suggestions. I've added them.

**Comment by adleong** [comment]
Thanks @bsord!  Looking at the unit test failure, should the default value of args actually be `--query.base-path=/jaeger` to match the behavior that we have today?

**Comment by bsord** [comment]
@adleong I must have missed that removal sorry. I've added it as a default value.

**Comment by kleimkuhler** [comment]
@bsord You'll need to run `bin/helm-docs` to update the generated Helm READMEs. This will allow the currently failing CI check to pass.

**Comment by bsord** [comment]
Is this good to go?

**Comment by bsord** [comment]
@kleimkuhler Thanks for the pointer there. May be useful to output that info in the CI script if it fails. I've updated the helm chart as suggested.

**Review by kleimkuhler — APPROVED** [review]
Thanks @bsord this looks good. I tested the change and it works as expected.

**Review by adleong — APPROVED** [review]
Nice!

**Pull request merged**
