### PR TITLE
CI: fix image load issue in k3d

### PR DESCRIPTION
**Pull request by Pothulapati**
This PR fixes the current CI failures!

`k3d` supports [multiple ways of importing images](https://k3d.io/v5.2.0/usage/importing_images/)
in the latest version of k3d. The default way however fails to import
multiple images from the same command. Hence, there is a need to
either
- load one by one using the `direct` mode
- load all at once using the `tools-node` mode.

I've went ahead with the `tools-node` mode, so that we chan
paralellize the image loads.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Comment by mateiidavid** [comment]
What sort of issue are we having when importing the images? I tried to reproduce this through the load script and separately by calling `k3d image import` directly and both worked for me.

`bin/image-import`
```bash
# Latest main
:; bin/k3d version
k3d version v5.1.0
k3s version v1.21.5-k3s2 (default)

:; bin/image-load --k3d --cluster review
k3d version v5.1.0
k3s version v1.21.5-k3s2 (default)
Importing cr.l5d.io/linkerd/cli-bin:git-1fb6ef23...
Importing cr.l5d.io/linkerd/cni-plugin:git-1fb6ef23...
Importing cr.l5d.io/linkerd/controller:git-1fb6ef23...
Importing cr.l5d.io/linkerd/policy-controller:git-1fb6ef23...
Importing cr.l5d.io/linkerd/metrics-api:git-1fb6ef23...
Importing cr.l5d.io/linkerd/debug:git-1fb6ef23...
Importing cr.l5d.io/linkerd/grafana:git-1fb6ef23...
Importing cr.l5d.io/linkerd/proxy:git-1fb6ef23...
Importing cr.l5d.io/linkerd/web:git-1fb6ef23...
Importing cr.l5d.io/linkerd/jaeger-webhook:git-1fb6ef23...
Importing cr.l5d.io/linkerd/tap:git-1fb6ef23...
INFO[0000] Importing image(s) into cluster 'review'
```

`k3d image import`
```
:; k3d version
k3d version v5.2.0
k3s version v1.21.7-k3s1 (default)

:; k3d image import -c review cr.l5d.io/linkerd/proxy:git-7ed768d9 cr.l5d.io/linkerd/policy-controller:git-7ed768d9
ERRO[0000] error getting loadbalancer config from k3d-review-serverlb: runtime failed to read loadbalancer config '/etc/confd/values.yaml' from node 'k3d-review-serverlb': Error: No such container:path: ec4e41fe3eaea16ac9415f4f30ee525f2462faefb81d81159da04247fead5c5b:/etc/confd/values.yaml: file not found
INFO[0000] Importing image(s) into cluster 'review'
INFO[0000] Loading 2 image(s) from runtime into nodes...
INFO[0001] Importing images into node 'k3d-review-server-0'...
INFO[0003] Successfully imported image(s)
INFO[0003] Successfully imported 2 image(s) into 1 cluster(s)
```

In both cases I managed to pass multiple images 🤔

**Review by mateiidavid — APPROVED** [review]
Ah, I see. Thanks, that makes more sense, also managed to reproduce locally. This looks good then! 👍🏻

**Comment by alpeb** [comment]
k3d docs indicate `auto | direct | tools` for possible values for the `-m`. Is `tools-node` some hidden option?

**Comment by Pothulapati** [comment]
@alpeb `tools-mode` seems to be the actual value that works.

```
on ⛵ k3d-k3s-default  linkerd2 on 🌱 taru [📦🤷‍] via 🐼 v1.16.9 via  via ⚙️ v1.56.0took 3s
❯ ./bin/k3d image import ./image-archives/proxy.tar ./image-archives/tap.tar -m tools
FATA[0000] Unknown image loading mode 'tools'

on ⛵ k3d-k3s-default  linkerd2 on 🌱 taru [📦🤷‍] via 🐼 v1.16.9 via  via ⚙️ v1.56.0
❯ ./bin/k3d image import ./image-archives/proxy.tar ./image-archives/tap.tar -m tools-node
INFO[0000] Importing image(s) into cluster 'k3s-default'
INFO[0000] Starting new tools node...
INFO[0000] Starting Node 'k3d-k3s-default-tools'
INFO[0000] Saving 2 tarball(s) to shared image volume...
INFO[0000] Importing images into nodes...
INFO[0000] Importing images from tarball '/k3d/images/k3d-k3s-default-images-20211206203604-file-tap.tar' into node 'k3d-k3s-default-server-0'...
INFO[0000] Importing images from tarball '/k3d/images/k3d-k3s-default-images-20211206203604-file-proxy.tar' into node 'k3d-k3s-default-server-0'...
```

**Review by alpeb — APPROVED** [review]
Sounds good. There's a bug in their docs and help screen it seems :+1:

**Pull request merged**
