### PR TITLE
Add nodeSelector and tolerations to linkerd-viz chart

### PR DESCRIPTION
**Pull request by aatarasoff**
Add nodeSelector and tolerations to linkerd-viz chart for metricsAPI, grafana and prometheus.

I've added separated configuration for external components only.

Signed-off-by: aatarasoff <aatarasoff@gmail.com>

### CODE REVIEW

**Comment by aatarasoff** [comment]
Hi, do you have a chance to see this PR?

**Review by dadjeibaah — APPROVED** [review]
Changes look good to me. 📦 🚢

**Comment by aatarasoff** [comment]
Could anyone else to look at this PR?)

**Review by alpeb — APPROVED** [review]
Thanks @aatarasoff , looks good to me! :+1: 
CI failure could be flakiness. I'll re-run that.

**Comment by aatarasoff** [comment]
@alpeb Thanks. Now tests are passed 🎉

**Pull request merged**
