### PR TITLE
Detect default ns for metrics and profile subcommands

### PR DESCRIPTION
**Pull request by alpeb**
Followup to #5485, fixes remaining cases for #5524

Properly detect the default namespace given `kubeConfigPath` and
`kubeContext` for the `metrics` and `profile` subcommands.

Also gets rid once and for all of the `defaultNamespace` global var.

### CODE REVIEW

**Review by adleong — APPROVED** [review]

**Comment by Pothulapati** [comment]
@alpeb This logic should also be part of `linkerd identity` and `linkerd viz routes` right? It seems to be missing there.

**Comment by alpeb** [comment]
> @alpeb This logic should also be part of `linkerd identity` and `linkerd viz routes` right? It seems to be missing there.

Good catch :+1:  I'll add that to `linkerd viz routes` in a moment. Although while checking `linkerd identity` I found some other inconsistencies around that, so I'll fix that in a followup PR.

**Comment by alpeb** [comment]
Ok I ended up pushing to this same branch the default namespace mechanism for `linkerd identity`; the inconsistency was just a bad description in the `--namespace` flag.

**Review by Pothulapati — APPROVED** [review]
LGTM

**Pull request merged**
