### PR TITLE
New Sidebar - Draft PR for UI review

### PR DESCRIPTION
**Pull request by scottcarol**
This is a draft PR, code is not for review. Original sidebar code has not been removed yet.

@grampelberg LMKWYT about the look and functionality.

Notes: 
1. The teal "Namespace Change" button looked jarring when next to the Linkerd green. The true "secondary color" for our Material-UI color palette is a hot pink, which also looked jarring. I made the button gray instead, if you think it's better as a teal button, I can change.
2. Responsive "disappearing sidebar" functionality is not in this PR.

### CODE REVIEW

**Comment by grampelberg** [comment]
Hmmm, do I need to do something special to get this to build?

```
 => ERROR [webpack-bundle 8/8] RUN ./bin/web build                                                30.2s
------
 > [webpack-bundle 8/8] RUN ./bin/web build:
#27 1.071 yarn run v1.7.0
#27 1.140 $ /linkerd-build/web/app/node_modules/.bin/webpack
#27 1.938 clean-webpack-plugin: /linkerd-build/web/app/dist has been removed.
#27 30.00 Hash: 1bf1bf49959997542898
#27 30.00 Version: webpack 4.39.3
#27 30.00 Time: 27709ms
#27 30.00 Built at: 09/23/2019 6:42:47 PM
#27 30.00  3 assets
#27 30.00  [24] ./node_modules/d3-selection/src/index.js + 50 modules 28.1 KiB {0} [built]
#27 30.00       |    51 modules
#27 30.00  [96] (webpack)/buildin/global.js 472 bytes {0} [built]
#27 30.00 [392] ./css/styles.css 1.09 KiB {0} [built]
#27 30.00 [393] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./css/styles.css 843 bytes {0} [built]
#27 30.00 [395] ./img/favicon.png 61 bytes {0} [built]
#27 30.00 [460] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
#27 30.00 [627] ./css/svg-wrappers.css 1.11 KiB {0} [built]
#27 30.00 [628] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./css/svg-wrappers.css 5.95 KiB {0} [built]
#27 30.00 [633] (webpack)/buildin/module.js 497 bytes {0} [built]
#27 30.00 [844] ./js/index.js + 132 modules 605 KiB {0} [built] [4 errors]
#27 30.00       | ./js/index.js 14.6 KiB [built] [1 error]
#27 30.00       |     + 132 hidden modules
#27 30.00     + 850 hidden modules
#27 30.00
#27 30.00 ERROR in ./js/components/MetricsTable.jsx
#27 30.00 Module Error (from ./node_modules/eslint-loader/index.js):
#27 30.00
#27 30.00 /linkerd-build/web/app/js/components/MetricsTable.jsx
#27 30.00   249:75  error  'nsMetrics' is missing in props validation  react/prop-types
#27 30.00
#27 30.00 ✖ 1 problem (1 error, 0 warnings)
#27 30.00
#27 30.00  @ ./js/components/Namespace.jsx 31:0-46 145:29-41 172:29-41
#27 30.00  @ ./js/index.js
#27 30.00
#27 30.00 ERROR in ./js/components/Navigation.jsx
#27 30.00 Module Error (from ./node_modules/eslint-loader/index.js):
#27 30.00
#27 30.00 /linkerd-build/web/app/js/components/Navigation.jsx
#27 30.00     2:10  error  'processMultiResourceRollup' is defined but never used  no-unused-vars
#27 30.00    14:8   error  'HomeIcon' is defined but never used                    no-unused-vars
#27 30.00    24:8   error  'NavigationResources' is defined but never used         no-unused-vars
#27 30.00    33:8   error  '_find' is defined but never used                       no-unused-vars
#27 30.00    35:8   error  '_isNil' is defined but never used                      no-unused-vars
#27 30.00    44:8   error  'teal' is defined but never used                        no-unused-vars
#27 30.00   216:22  error  'metricsForNs' is defined but never used                no-unused-vars
#27 30.00   222:11  error  Unused state field: 'loaded'                            react/no-unused-state
#27 30.00   289:19  error  'state' is defined but never used                       no-unused-vars
#27 30.00
#27 30.00 ✖ 9 problems (9 errors, 0 warnings)
#27 30.00
#27 30.00  @ ./js/index.js 38:0-53 121:33-43 129:33-43 136:33-43 144:33-43 151:33-43 159:33-43 166:33-43 174:33-43 181:33-43 189:33-43 196:33-43 204:33-43 211:33-43 219:33-43 226:33-43 234:33-43 241:33-43 248:33-43 255:33-43 262:33-43 270:33-43 278:33-43 286:33-43 294:33-43 302:33-43 310:33-43 318:33-43 326:33-43 334:33-43 342:33-43
#27 30.00
#27 30.00 ERROR in ./js/components/ResourceList.jsx
#27 30.00 Module Error (from ./node_modules/eslint-loader/index.js):
#27 30.00
#27 30.00 /linkerd-build/web/app/js/components/ResourceList.jsx
#27 30.00    4:1   error  Imports should be sorted alphabetically                                                 sort-imports
#27 30.00   13:1   error  Imports should be sorted alphabetically                                                 sort-imports
#27 30.00   35:5   error  propType "nsMetrics" is not required, but has no corresponding defaultProp declaration  react/require-default-props
#27 30.00   35:16  error  'nsMetrics' PropType is defined but prop is never used                                  react/no-unused-prop-types
#27 30.00
#27 30.00 ✖ 4 problems (4 errors, 0 warnings)
#27 30.00
#27 30.00  @ ./js/index.js 43:0-57 137:24-36 152:24-36 167:24-36 182:24-36 197:24-36 212:24-36 227:24-36 263:24-36 271:24-36 279:24-36 287:24-36 295:24-36 303:24-36 311:24-36 319:24-36 327:24-36 335:24-36
#27 30.00
#27 30.00 ERROR in ./js/index.js
#27 30.00 Module Error (from ./node_modules/eslint-loader/index.js):
#27 30.00
#27 30.00 /linkerd-build/web/app/js/index.js
#27 30.00   12:8   error  'NamespaceLanding' is defined but never used  no-unused-vars
#27 30.00   46:22  error  Unused state field: 'nsMetrics'               react/no-unused-state
#27 30.00   51:7   error  Unused state field: 'api'                     react/no-unused-state
#27 30.00   52:7   error  Unused state field: 'pathPrefix'              react/no-unused-state
#27 30.00   53:7   error  Unused state field: 'productName'             react/no-unused-state
#27 30.00   54:7   error  Unused state field: 'nsMetrics'               react/no-unused-state
#27 30.00   55:7   error  Unused state field: 'changeNs'                react/no-unused-state
#27 30.00
#27 30.00 ✖ 7 problems (7 errors, 0 warnings)
#27 30.00
#27 30.00 Child html-webpack-plugin for "index_bundle.js.out":
#27 30.00      1 asset
#27 30.00     [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index_bundle.js.lodash.tmpl 1.18 KiB {0} [built]
#27 30.00     [2] (webpack)/buildin/global.js 472 bytes {0} [built]
#27 30.00     [3] (webpack)/buildin/module.js 497 bytes {0} [built]
#27 30.00         + 1 hidden module
#27 30.07 error Command failed with exit code 2.
#27 30.07 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c ./bin/web build]: exit code: 1
```

**Comment by scottcarol** [comment]
@grampelberg What are you using to build? Are you running `bin/web setup` and `bin/web dev`?

**Comment by grampelberg** [comment]
`bin/docker-build` which should be a clean environment.

**Comment by scottcarol** [comment]
This may be because of the webpack errors due to not removing un-used code from the old sidebar yet - I'm holding off on that because I want to get your feedback on UI first.

Could you try running `bin/web setup` and `bin/web dev` while running the latest edge release of Linkerd? If that doesn't work for you, I can post screenshots here and/or we can go over it together in person.

**Comment by grampelberg** [comment]
Hmm, I guess all the errors are lint related. This looks right directionally. There's a bunch of little polish stuff that'd be nice to fix (padding for the namespace selector, remove highlights of section names, icon sizing, ....).

Let's start getting this cleaned up and code reviewed, I'll get a list of the required polish stuff together and the follow up work (breadcrumbs for example).

**Comment by scottcarol** [comment]
Ok, sounds great, will move towards code review now.

**Pull request closed without merging**
