### PR TITLE
Update helm instructions to include name

### LINKED ISSUE #6418: linkerd-viz: helm installation instructions need a name
The instructions to [install](https://github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz#installing-the-viz-extension-chart) the linkerd-viz extension with helm don't include a name for the installation, so the installation fails with this error:

`Error: must either provide a name or specify --generate-name`

This is the install command that fails:

`helm install linkerd/linkerd-viz`

The instructions should be updated for both helm 2 and helm 3.

helm v2: `helm install --name linkerd-viz linkerd/linkerd-viz`
helm v3: `helm install linkerd-viz linkerd/linkerd-viz`

### PR DESCRIPTION
**Pull request by cpretzer**
* Updates helm install instructions to include a `name` value with instructions for helm v2 and v3

Fixes #6418
 
Signed-off-by: Charles Pretzer <charles@buoyant.io>

### CODE REVIEW

**Comment by Pothulapati** [comment]
@cpretzer LGTM, but should we also do the same for other Helm extension READMEs? as they also have this similar confusion!

**Comment by cpretzer** [comment]
> @cpretzer LGTM, but should we also do the same for other Helm extension READMEs? as they also have this similar confusion!

good catch @Pothulapati I'll get the other instructions updated soon

**Comment by cpretzer** [comment]
@Pothulapati committed instructions for jaeger and mc 😄

**Review by Pothulapati — APPROVED** [review]
LGTM

**Review by kleimkuhler — APPROVED** [review]

**Pull request merged**
