### PR TITLE
Add prometheus authentication (#7038)

### LINKED ISSUE #7038: Support custom authentication with external prometheus instance
### What problem are you trying to solve?

Bring your own Prometheus that requires some sort of authentication, such as token-based (static), basic auth.

```
GET /api/v1/query HTTP/1.1
Host: external.prometheus.com
Authorization: Bearer supersecuretoken
```

### How should the problem be solved?

`viz` plugin should have a way to accept arbitrary HTTP headers 

Add a new flag to the `metrics-api` entrypoint, something like `prometheusAuthHeaders`, and it is expecting a string array. For example, `--prometheusAuthHeaders key1=val1,key2=val2` or `--prometheusAuthHeaders key1=val1 --prometheusAuthHeaders key2=val2`

https://github.com/linkerd/linkerd2/blob/451602e28da51a0db4ff053e33cefe9f1eda9a17/viz/metrics-api/cmd/main.go#L21-L29

In the helm chart, we can just add a new value and map them to the metrics-api deployment command arguments.

```yml
prometheusAuthHeaders:
  Authorization: "Bearer supersecuretoken"
  More: "Custom Headers"
```

To include the auth headers, we will need to change how the prom API client is initialized. 

This can be implemented using the `RoundTrippers` from the prometheus API client somewhere around here https://github.com/linkerd/linkerd2/blob/451602e28da51a0db4ff053e33cefe9f1eda9a17/viz/metrics-api/cmd/main.go#L49-L55

Learn more about how the round trippers work https://github.com/prometheus/client_golang/pull/817

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

No.

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

See the previous section.

### Notes

I am open to work on it.

### PR DESCRIPTION
**Pull request by ketchoop**
Signed-off-by: Alexey Boyko ket4yiit@gmail.com

### Problem

Described in #7038

### Solution

Added basic and bearer auth by using possibility to create prometheus client RoundTripper([example from official repo](https://github.com/prometheus/client_golang/blob/d69fe9a80254b8a262bb071cad63595fcbff6dab/api/prometheus/v1/example_test.go#L164))

### Validation

For bearer token: 

Used [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy/tree/master/examples/non-resource-url)

For basic auth:

Used official prometheus [web-config feature](https://prometheus.io/docs/guides/basic-auth/)

Fixes #7038

### CODE REVIEW

**Comment by adleong** [comment]
Hi @ketchoop!  As discussed in #7038, I think we'd want these credentials to be loaded from a secret rather than being publicly visible.

**Comment by ketchoop** [comment]
@adleong Hi! What if I do that by using [valueFrom](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data) kubernetes' feature and make this work by changing the chart?

Does it seem to be the right and secure way for you?

**Comment by adleong** [comment]
Yes, that sounds right to me.

**Comment by mateiidavid** [comment]
Hi @ketchoop! I converted the PR to a draft. It sounds like the shape of the solution is going to have to change to read the credentials from a secret. Are you still willing to work on this? If yes, then feel free to mark the PR as ready to review after you've made the changes. Thanks for all of the work you've done on this thus far.

**Comment by alpeb** [comment]
Seems this has gotten stale, so closing for now. Please reopen a new PR if you're still interested in moving this forward.

**Pull request closed without merging**
