### PR TITLE
Jaeger injector mutating webhook

### LINKED ISSUE #5231: Create jaeger-injector mutating webhook
Create a muting admission controller webhook called `jaeger-injector` which adds the appropriate tracing environment variables to the Linkerd proxy container.  

This webhook adds the LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR, LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME, and LINKERD2_PROXY_TRACE_ATTRIBUTES_PATH environment variables as well as the podinfo volume to the Linkerd proxy container if it exists.  If a pod does not have a Linkerd proxy sidecar, no action should be taken.  However, this webhook should have a `IfNeeded` reinvokation policy so that it will be reinvoked if the Linkerd proxy is added.

By default, this injector should set the above env variable to the address and service account of the `oc-collector` in the linkerd-jaeger namespace.  However, if the `config.linkerd.io/trace-collector` or `config.alpha.linkerd.io/trace-collector-service-account` annotations are set on the pod or its namespace, it should use those values instead.

By default, this injector should be invoked on all newly created pods and act on them if they have a Linkerd proxy sidecar.  However, it should also be possible to configure the injector with a label selector to selectively opt in which pods will be affected.

### PR DESCRIPTION
**Pull request by alpeb**
Closes #5231. This is based off of the `alex/sep-tracing` branch.

This webhook injects the `LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR`,
`LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME` and
`LINKERD2_PROXY_TRACE_ATTRIBUTES_PATH` environment vars into the proxy
spec when a pod is created, as well as the podinfo volume and its mount.
If any of these are found to be present already in the pod spec, it
exits without applying a patch.

The `values.yaml` file has been expanded to include config for this
webhook. In particular, one can define a `namespaceSelector` and/or a
`objectSelector` to filter which pods will this webhook act on.

The config entries in `values.yam` for `collectorSvcAddr` and
`collectorSvcAccount` can be overriden with the
`config.linkerd.io/trace-collector` and
`config.alpha.linkerd.io/trace-collector-service-account` annotation at
the namespace or pod spec level.

## How to test:
```bash
docker build . -t ghcr.io/linkerd/jaeger-webhook:0.0.1 -f
jaeger/proxy-mutator/Dockerfile
k3d image import ghcr.io/linkerd/jaeger-webhook:0.0.1
bin/helm-build
linkerd install
helm install jaeger jaeger/charts/jaeger
linkerd inject https://run.linkerd.io/emojivoto.yml | kubectl apply -f -
kubectl -n emojivoto get po -l app=emoji-svc -oyaml | grep -A1 TRACE
```

## Reinvocation policy
The webhookconfig resource is configured with `reinvocationPolicy:
IfNeeded` so that if the tracing injector gets triggered before the
proxy injector, it will get triggered a second time after the proxy
injector runs so it can act on the injected proxy. By default this won't
be necessary because the webhooks run in alphabetical order (this is not
documented in k8s docs though) so
`linkerd-proxy-injector-webhook-config` will run before
`linkerd-proxy-mutator-webhook-config`. In order to test the
reinvocation mechanism, you can change the name of the former so it gets
called first.

I versioned the webhook image as `0.0.1`, but we can decide to align
that with linkerd's main version tag.

### CODE REVIEW

**Review by adleong — APPROVED** [review]
Very nice work!  🐯 No surprises in here.

**Comment by alpeb** [comment]
Note that I've commented out the tracing tests until we swap out the old tracing implementation.

**Comment by Pothulapati** [comment]
@alpeb Why remove the tracing tests? Ik the current injector code is removed.

I think, as #5278 is adding `jaeger` sub-command to linkerd binary, we can instead install extension [in the tracing test](https://github.com/linkerd/linkerd2/blob/main/test/integration/tracing/tracing_test.go#L52) (which will include the new jaeger injector) and continue running these integration tests? Also, helps us make sure this new extension stuff works. WDYT?

**Comment by alpeb** [comment]
I just wanted to have the tests here pass in case it got merged first. But it seems #5278 is close to land, so I can wait for that and update the tests here :+1:

**Comment by alpeb** [comment]
I ended up reenabling the tests after having restored `_proxy.tpl` to its original tests, so tests _should_ pass.
We can then in a separate PR start using `linkerd jaeger` to install tracing in the integration tests, and in another PR remove the old tracing implementation if we decide so.

**Comment by alpeb** [comment]
Ok, in the latest push:
- Peg the mutator image version to Linkerd's
- Create `bin/docker-build-jaeger-webhook` and add it to `bin/docker-build`
- Add more missing entries to `values.go`

**Comment by Pothulapati** [comment]
As per the Distributed Tracing doc, When we do inject through annotations, The `namespace` is being appended to the serviceaccount before adding it as variable.

```bash
tarun in dev in on  kind-kind () linkerd2 on  alpeb/tracing-webhook [$] via 🐹 v1.15.4
❯ kubectl -n emojivoto patch -f https://run.linkerd.io/emojivoto.yml -p '
quote> spec:
quote>   template:
quote>     metadata:
quote>       annotations:
quote>         linkerd.io/inject: enabled
quote>         config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
quote>         config.alpha.linkerd.io/trace-collector-service-account: collector
quote> '
namespace/emojivoto patched
serviceaccount/emoji patched
serviceaccount/voting patched
serviceaccount/web patched
service/emoji-svc patched
service/voting-svc patched
service/web-svc patched
deployment.apps/emoji patched
deployment.apps/vote-bot patched
deployment.apps/voting patched
deployment.apps/web patched

tarun in dev in on  kind-kind () linkerd2 on  alpeb/tracing-webhook [$] via 🐹 v1.15.4
❯ kubectl -n emojivoto get po -l app=emoji-svc -oyaml | grep -A1 TRACE
      - name: LINKERD2_PROXY_TRACE_ATTRIBUTES_PATH
        value: /var/run/linkerd/podinfo/labels
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR
        value: collector.linkerd-jaeger:55678
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME
        value: collector.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
--
      - name: LINKERD2_PROXY_TRACE_ATTRIBUTES_PATH
        value: /var/run/linkerd/podinfo/labels
--
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR
        value: collector.linkerd-jaeger:55678
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME
        value: collector.linkerd-jaeger.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)

```

but this is not the case with the new injector

```bash
tarun in dev in on  kind-kind () linkerd2 on  alpeb/tracing-webhook [$] via 🐹 v1.15.4
❯ kubectl -n emojivoto get po -l app=emoji-svc -oyaml | grep -A1 TRACE
      - name: LINKERD2_PROXY_TRACE_ATTRIBUTES_PATH
        value: /var/run/linkerd/podinfo/labels
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR
        value: collector.linkerd-jaeger:55678
      - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME
        value: collector.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
```

Hence, the new injector was not showing proxy traces. Is this expected?

**Comment by alpeb** [comment]
Great catch @Pothulapati :+1:  I've just pushed a fix.

**Review by Pothulapati — APPROVED** [review]
LGTM! Works as espected!

**Pull request merged**
