### PR TITLE
Add affinity settings in viz and jaeger chart

### LINKED ISSUE #10680: linkerd-viz and linkerd-jaeger charts do not support nodeAffinity
### What is the issue?

In contrast to [linkerd-control-plane](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/proxy-injector.yaml#L58) helm chart `linkerd-viz` and `linkerd-jaeger` helm charts do not support nodeAffinity at the moment. Can you please add this functionality there unless there is any specific reason not to do it?

### How can it be reproduced?

Deploy latest version of linkerd-viz and linkerd-jaeger

### Logs, error output, etc

no errors

### output of `linkerd check -o short`

not required

### Environment

kubernetes 1.25.5
linkerd 2.12.4

### Possible solution

update helm charts to add nodeAffinity

### Additional context

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by naing2victor**
Add `nodeAffinity` for `deployment` template to `linkerd-viz` and `linkerd-jaeger` charts

Fixes #10680

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
Thanks, @naing2victor!

I noticed that you're setting the component and label values which are used by podAntiAffinity, not nodeAffinity.  What do you think of adding

```
# -- Enables Pod Anti Affinity logic to balance the placement of replicas
# across hosts and zones for High Availability.
# Enable this only when you have multiple replicas of components.
enablePodAntiAffinity: false
```

to the values.yaml since we're setting those component and label values anyway.  That makes it consistent with the other extensions as well.

**Comment by naing2victor** [comment]
@adleong Thank you for your feedback. I can see that `linkerd-viz` chart is already implemented with `podAntiAffinity`. We'll only need to apply for `linkerd-jaeger` chart. Adding `enablePodAntiAffinity` may also need to variabilize the `replicas` for each component. May I know how would you suggest for the value usage. 

Would it be better if we separate the variable by the component. For example,
```
replicas: {{.Values.jaegerInjector.replicas}}
replicas: {{.Values.collector.replicas}}
replicas: {{.Values.jaeger.replicas}}
```
Or just using 1 value for all the components.
```
replicas: {{.Values.replicas}}
```

**Comment by adleong** [comment]
I'd recommend having a separate replicas value for each component (which is what we do in linkerd-viz).  However, the exception to that is that increasing the number of replicas of the `jaeger` component could be problematic since this is a stateful trace backend; so we may want to leave that one hardcoded at 1 replica.

**Comment by naing2victor** [comment]
I've added `enablePodAntiAffinity` and make `replicas` values to get from values file.

**Review by alpeb — COMMENTED** [review]
If you try rendering the templates with `enablePodAntiAffinity=true` you'll see there's a problem. I believe the issue is not passing `$tree` into the `linkerd.affinity` include.

**Review by adleong — APPROVED** [review]

**Review by alpeb — APPROVED** [review]

**Pull request merged**
