### PR TITLE
Add imagePullSecrets to the multicluster chart.

### LINKED ISSUE #11285: Unable to install linkerd-multicluster with helm in air-gapped environment
### What is the issue?

In contrast to the control-plane  and the viz chart, where we can [supply ](https://github.com/linkerd/linkerd2/blob/a4bec904cc19d30441fb4ab591cff0a1edc66c20/charts/linkerd2-cni/values.yaml#L70) an override for imagePullSecrets this is missing from the multicluster chart.

In an air-gapped environment it is not possible to deploy the the multicluster feature with helm.

### How can it be reproduced?

Try to deploy the mutlicluster without access to cr.l5d.io or gcr.io.

### Logs, error output, etc

Back-off pulling image private.registry.google_containers/pause:3.2

### output of `linkerd check -o short`

n/a

### Environment

- Air Gapped, private AKS cluster

### Possible solution

Supply imagePullSecrets in the multicluster chart's values.yaml.

### Additional context

_No response_

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by lhaussknecht**
Fixes #11285

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
Do the gateway and/or ServiceMirror need imagePullSecrets also?

**Comment by lhaussknecht** [comment]
@adleong Added the secret also to the gateway service account.

**Comment by adleong** [comment]
thanks, @lhaussknecht!  This looks great but it's probably not complete until we have image pull secrets for the service mirror controller too, right?  Anyone who wants to use the linkerd-multicluster extension in an air gapped environment like this would need image pull secrets for the service mirror controller.

The service mirror controller is in the linkerd-multicluster-link helm chart.  This isn't a helm chart we publish.  Instead, the `linkerd multicluster link` command uses Helm as a library to render the linkerd-mutlicluster-link chart, which produces the service mirror controller (and related) manifests.  Therefore, to add image pull secrets to the service mirror controller, we would also need to add an image pull secret helm value to the linkerd-multicluster-link chart and render it in the service mirror controller template.

**Comment by lhaussknecht** [comment]
Thanks for the clarification. I added imagePull secrets to the service mirror.

**Review by adleong — APPROVED** [review]
Excellent!  Thanks for this, @lhaussknecht

**Review by olix0r — APPROVED** [review]

**Pull request merged**
