### PR TITLE
Make wait=true a default option for check and dashboard

### LINKED ISSUE #1618: make `--wait` the default
Right now you have to pass `--wait` explicitly to `linkerd check` but I think this should happen by default.

### PR DESCRIPTION
**Pull request by alenkacz**
resolves #1618 

Signed-off-by: Alena Varkockova <varkockova.a@gmail.com>

### CODE REVIEW

**Comment by klingerf** [comment]
@alenkacz Thanks for submitting this! Sorry this wasn't specified in the ticket, but I'd prefer to keep the `--wait` flag available and change its default value from `false` to `true`. I think we should also make the equivalent change for the `--wait` flag in `cli/cmd/dashboard.go`.

**Comment by wmorgan** [comment]
I agree. Sorry @alenkacz I should've been more specific in the issue description!

**Comment by olix0r** [comment]
@klingerf 

>  I'd prefer to keep the --wait flag available and change its default value from false to true

What do you think about `--wait` taking a duration, with the default being something very high?

I'm imagining that in CI, etc, it would be nice to say `--wait 1 minute`, for instance -- we'd want the command to fail eventually, just not immediately.

**Comment by klingerf** [comment]
@olix0r That works for me, and it relates to the change requested in ##1586.

**Comment by alenkacz** [comment]
@klingerf ok that actually makes sense :) I will change that.

I'll maybe address #1586 in another PR to not mix those two together if it works for everyone.

**Comment by alenkacz** [comment]
@klingerf fixed and added wait=true also for dashboard

**Pull request merged**
