### PR TITLE
 Fix for CLI printing command usage for API Errors for multiple commands

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya piyushsingariya@gmail.com

Related to #5058

Problem: CLI prints command usage for multiple commands in-case of API errors
Solution: Print the error and the exit using os.Exit(1) to avoid Cobra printing usage

### CODE REVIEW

**Comment by piyushsingariya** [comment]
Hey @adleong @alpeb, I messed the previous PR so I opened up a fresh one.
and I think that the tests are failing because they're expecting an error in return but the changes are simply printing the error and exiting the process. :thinking:

**Review by alpeb — COMMENTED** [review]
For the current error, it should be just a matter of replacing this message
https://github.com/linkerd/linkerd2/blob/89ec6056c02632d88026c13b89ae212d1b71e4e7/test/integration/endpoints/endpoints_test.go#L80
with
```
 if stderrOut[0] != "Destination API error: Invalid authority: foo" { 
```

**Comment by piyushsingariya** [comment]
@alpeb Yes, it worked! :tada:

**Review by alpeb — APPROVED** [review]
Thanks @piyushsingariya , looks good to me :+1:

**Review by kleimkuhler — APPROVED** [review]
Looks great @piyushsingariya, thank you!

**Pull request merged**
