### PR TITLE
Add Collector Flags for inject cmd

### LINKED ISSUE #3468: Allow trace collector address to be configured via flag or helm variable
https://github.com/linkerd/linkerd2-proxy/pull/354 added environment variables: `LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR` and `LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME` which enable the Linkerd proxy to participate in traces and to emit spans to the provided collector.  We should allow these environment variables to be set from the CLI in the normal ways.

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #3468 

This PR allows users to configure traces for their workloads proxies by
```
linkerd inject --trace-collector oc-collector.tracing:55678 --trace-collector-svc-account oc-collector emojivoto.yml
```

This will add the necessary annotations to the workloads which are then honoured by the `proxy-injector` during injection. As the annotation's values are then defaulted/updated by the proxy-injector we would not need any of that logic here.

@ihcsim

### CODE REVIEW

**Comment by Pothulapati** [comment]
@ihcsim The catch here being even though these flags are not included in the global protobuf config , but as the `proxyConfigFlags` are also used at the install cmd they just show up in the `linkerd install --help` but dont effect the install annotations.

As @grampelberg suggested to not have these flags for `install`, (`--control-plane-tracing` can be used there). Is there a way to add flags only to inject but not to install?

**Comment by ihcsim** [comment]
@Pothulapati Does the below diff match what you are looking for?

```diff
diff --git a/cli/cmd/inject.go b/cli/cmd/inject.go
index 86511e13..69eb6e6d 100644
--- a/cli/cmd/inject.go
+++ b/cli/cmd/inject.go
@@ -115,6 +115,11 @@ sub-folders, or coming from stdin.`,
 
 	flags.BoolVar(&enableDebugSidecar, "enable-debug-sidecar", enableDebugSidecar,
 		"Inject a debug sidecar for data plane debugging")
+	flags.StringVar(
+		&options.traceCollector, "trace-collector", options.traceCollector,
+		"Collector Service address for the proxies to send Trace Data")
+	flags.StringVar(&options.traceCollectorSvcAccount, "trace-collector-svc-account",
+		options.traceCollectorSvcAccount, "Service account associated with the Trace collector instance")
 	cmd.PersistentFlags().AddFlagSet(flags)
 
 	return cmd
diff --git a/cli/cmd/root.go b/cli/cmd/root.go
index 30f21102..bcd69dd6 100644
--- a/cli/cmd/root.go
+++ b/cli/cmd/root.go
@@ -295,8 +295,6 @@ func (options *proxyConfigOptions) flagSet(e pflag.ErrorHandling) *pflag.FlagSet
 	flags.StringVar(&options.proxyCPULimit, "proxy-cpu-limit", options.proxyCPULimit, "Maximum amount of CPU units that the proxy sidecar can use")
 	flags.StringVar(&options.proxyMemoryLimit, "proxy-memory-limit", options.proxyMemoryLimit, "Maximum amount of Memory that the proxy sidecar can use")
 	flags.BoolVar(&options.enableExternalProfiles, "enable-external-profiles", options.enableExternalProfiles, "Enable service profiles for non-Kubernetes services")
-	flags.StringVar(&options.traceCollector, "trace-collector", options.traceCollector, "Collector Service address for the proxies to send Trace Data")
-	flags.StringVar(&options.traceCollectorSvcAccount, "trace-collector-svc-account", options.traceCollectorSvcAccount, "Service account associated with the Trace collector instance")
 
 	// Deprecated flags
 	flags.StringVar(&options.proxyMemoryRequest, "proxy-memory", options.proxyMemoryRequest, "Amount of Memory that the proxy sidecar requests")
```

**Comment by Pothulapati** [comment]
@ihcsim Ah Thanks, updated the code to make them inject only flags.

**Comment by ihcsim** [comment]
@Pothulapati Thanks! Since #3468 mentioned both Linkerd CLI and Helm, can you help me with updating the `charts/linkerd2/README.md` file to include the two new variables; `{{.Proxy.Trace.CollectorSvcAddr}}` and `{{.Proxy.Trace.CollectorSvcAccount}}`? We can just use the same description as the CLI options.

**Comment by Pothulapati** [comment]
Updated. I think, there should also be a mention of these flags that they are not present in the global proxy config but are only applicable to the control-plane proxy instance.

**Comment by ihcsim** [comment]
When I run `linkerd inject` in this branch, the proxy injector is panicking:
```
⚡ bin/linkerd inject --trace-collector=foo --trace-collector-svc-account=default.default https://run.linkerd.io/emojivoto.yml | k apply -f -

⚡ bin/linkerd logs --control-plane-component proxy-injector
....
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector 2019/10/21 20:18:34 http2: panic serving 127.0.0.1:43904: runtime error: invalid memory address or nil pointer dereference
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector goroutine 718 [running]:
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector net/http.(*http2serverConn).runHandler.func1(0xc000442450, 0xc000c59faf, 0xc000279200)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /usr/local/go/src/net/http/h2_bundle.go:5681 +0x16b
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector panic(0x16ac5e0, 0x29d87a0)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /usr/local/go/src/runtime/panic.go:522 +0x1b5
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/pkg/inject.(*ResourceConfig).trace(0xc000c44c00, 0xc000e449c0)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/pkg/inject/inject.go:570 +0x1cb
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/pkg/inject.(*ResourceConfig).injectPodSpec(0xc000c44c00, 0xc000b9a500)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/pkg/inject/inject.go:505 +0x7f5
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/pkg/inject.(*ResourceConfig).GetPatch(0xc000c44c00, 0xc000c59a01, 0x18d82d9, 0x15, 0xc000c59b50, 0xc00051b080, 0x23)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/pkg/inject/inject.go:213 +0x5f9
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/controller/proxy-injector.Inject(0xc00010ca00, 0xc0000d04e0, 0x1b7d9e0, 0xc00019cd80, 0x1, 0x1, 0x8db)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/controller/proxy-injector/webhook.go:101 +0x10fb
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/controller/webhook.(*Server).processReq(0xc0001ddbf0, 0xc00092c000, 0x8db, 0xe00, 0x8db)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/controller/webhook/server.go:122 +0x31e
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector github.com/linkerd/linkerd2/controller/webhook.(*Server).serve(0xc0001ddbf0, 0x1b77c60, 0xc000442450, 0xc0004bd200)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /linkerd-build/controller/webhook/server.go:93 +0x63
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector net/http.HandlerFunc.ServeHTTP(0xc000221600, 0x1b77c60, 0xc000442450, 0xc0004bd200)
linkerd-proxy-injector-c779fdf78-dh7mk proxy-injector   /usr/local/go/src/net/http/server.go:1995 +0x44
```

This diff should fix it:

```diff
diff --git a/pkg/inject/inject.go b/pkg/inject/inject.go
index 86413efc..1fa3f13e 100644
--- a/pkg/inject/inject.go
+++ b/pkg/inject/inject.go
@@ -567,7 +567,7 @@ func (conf *ResourceConfig) trace() *charts.Trace {
 
 	var ns string
 	if len(hostname) == 1 {
-		ns = conf.workload.Meta.Namespace
+		ns = conf.pod.meta.Namespace
 	} else {
 		ns = hostname[1]
 	}
```
It looks like `conf.workload.Meta.Namespace` is only instantiated if we are using auto-inject + annotations.

> there should also be a mention of these flags that they are not present in the global proxy config but are only applicable to the control-plane proxy instance.

These flags do apply to global proxy config. See #3481.

**Pull request merged**
