### PR TITLE
do not skip headless services for the opaque ports check

### PR DESCRIPTION
**Pull request by kleimkuhler**
Currently the opaque ports check skips headless services, but it should not do that. This removes the skip and results in it correctly warning on manifests like the below
```
apiVersion: v1
kind: Pod
metadata:
  name: pod
  annotations:
    config.linkerd.io/opaque-ports: "80"
  labels:
    app: pod
spec:
  containers:
  - name: app
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: pod
  clusterIP: None
  ports:
  - name: http
    port: 80
```

```
$ linkerd check --proxy
...
× opaque ports are properly annotated
        * service svc targets the opaque port 8080 through 8080; add 8080 to its config.linkerd.io/opaque-ports annotation
    see https://linkerd.io/2/checks/#linkerd-opaque-ports-definition for hints
```

Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

### CODE REVIEW

**Review by Pothulapati — APPROVED** [review]
LGTM :shipit:

**Review by alpeb — APPROVED** [review]

**Comment by olix0r** [comment]
@kleimkuhler Why shouldn't it skip headless serves? There's no clusterIP for these services, so we'll never try a resolution through the service.

**Comment by kleimkuhler** [comment]
@olix0r a client could still target `svc.default.svc.cluster.local:80` like in the example above. In this situation, the headless service selects a pod that sets `80` as opaque, but that's no the case on the service. We'd want `linkerd check --proxy` to warn in this situation that `svc` should also have the annotation.

**Comment by olix0r** [comment]
> a client could still target svc.default.svc.cluster.local:80 like in the example above

If a client targets such a service, DNS is resolved to a pod in that service and not a clusterIP. when the proxy does profile discovery, it's on the pod IP, so the service never comes into play from linkerd's perspective.

**Comment by kleimkuhler** [comment]
Okay yea I thought we still went through a `GetProfile` call for it, but I'll close it then

**Pull request closed without merging**
