### PR TITLE
Add support for build in multi arch

### PR DESCRIPTION
**Pull request by aliariff**
This PR only means to address the needs of building Linkerd manually from local with different architecture. It will not make Linkerd officially support any other architecture than amd64, because it does not yet utilize `docker manifest` to support multi-arch images[1].

Changes:
- Introduce new env key `DOCKER_BUILD_ARCH` to set the output docker images architecture
- If `DOCKER_BUILD_ARCH` set, it will create the repositories with the suffix name of the arch, ex: `gcr.io/linkerd-io/base-arm`, `gcr.io/linkerd-io/grafana-arm64`, `gcr.io/linkerd-io/web-arm`
- Use the SHA method to version the `base` image same like the `go-deps`
- Remove hard-coded image name, instead, we use docker ARG and pass the image name dynamically, the arguments called `RUNTIME_IMAGE` and `BUILDER_IMAGE`
- Reuse `go-deps` image to do cross-compile to other architecture, therefore a new docker ARG called `GOARCH` introduced
- Remove the tag validation features, because it is not needed anymore, we already remove hard-coded image name and use docker ARG instead
- Add more documentation

What happens after this is merged:
- It WILL create a new base image with the tag is using SHA, called `gcr.io/linkerd-io/base:44134b1b` according to the SHA of current `Dockerfile-base` file
- It WILL create a new `go-deps` image because of the changes `Dockerfile-go-deps` file, and it called `gcr.io/linkerd-io/go-deps:60254700`(if nothing change with the `Gopkg.lock`)

- It WILL NOT create a repo with different arch name and push it to the registry because we don't set any `DOCKER_BUILD_ARCH` in `.travis.yml`, so it will behave as usual, only push the normal amd64 image

Tested manually:
:white_check_mark: Grafana
Screen Shot 2019-07-22 at 16 01 46

:white_check_mark: Debug
Screen Shot 2019-07-22 at 16 01 05

:white_check_mark: Web
Screen Shot 2019-07-22 at 16 00 09

:white_check_mark: CNI-Plugin
Screen Shot 2019-07-22 at 15 58 58

:white_check_mark: Controller
Screen Shot 2019-07-22 at 15 52 50

:white_check_mark: CLI-Bin
Screen Shot 2019-07-22 at 15 50 22

:x: Proxy (Future work to support Rust cross compile)
Screen Shot 2019-07-22 at 16 03 45

Future works in another PR:
- Support `linkerd2-proxy` that using Rust to do cross-compile in order to fully support other architecture
- Support multi-arch images officially by build and push other architectures like `arm` or `arm64` to the registry and link them using `docker manifest`. This is should be done after making the `linkerd2-proxy` works in another architecture

References:
[1] https://docs.docker.com/engine/reference/commandline/manifest/

Related issues:
#3114 
#1165

### CODE REVIEW

**Comment by grampelberg** [comment]
@aliariff interested in getting this polished up so that we can merge it?

**Comment by aliariff** [comment]
@grampelberg
Do you think this is still relevant for now? because earlier you said that there is a blocker which is the hardware and it is necessary to have it so that the integration test can be performed.

**Comment by grampelberg** [comment]
@aliariff most definitely, I guess I should have used something more specific than "polished up". We'd love to work with you to get a checklist together on what would be required for this functionality to land in Linkerd. With a checklist, we'll be able to divide and conquer!

**Comment by aliariff** [comment]
@grampelberg 
Yes sure, I think my idea at that time when I create this PR is just to introduce a way to create docker images in multiple arch, this is a good start to make Linkerd support multi-arch officially. 
But of course, as you say even after it is possible to create the docker images in another arch like `arm`, it is necessary to do an integration test for that arch.

So, in short, there is 2 part that we need to do.
1. Make it possible to create the docker images in different arch
2. Prepare the environment that we want to officially support (ex: `arm`, `arm64`) & integrate it with the current CI/CD and also pushed the created images to the GCR repo after the test succeeds.

What do you think?

**Comment by grampelberg** [comment]
Hmm, that sounds right to me. It feels like there's a couple steps after 2 around release process and making sure all the artifacts are up to snuff.

It appears that this PR does step 1? Or does it do more than that?

**Comment by aliariff** [comment]
@grampelberg 

Yes, this PR only means to address the first part.

**Comment by richliu** [comment]
One question, 

in file cni-plugin/Dockerfile, it will download a jq binary file 
RUN curl -kL -o $(which jq) https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64

but this file is for AMD64 arch, so, I need to compile a ARM64 binary. 

Do you have some idea to solve that ?

**Comment by grampelberg** [comment]
@richliu Maybe add some logic to check the arch and download the right binary?

**Comment by richliu** [comment]
> @richliu Maybe add some logic to check the arch and download the right binary?

There is no official jq Linux arm64 binary on jq's website. I am not sure why it doesn't use distribution's default jq. probably version issue ? 
Download version is 1.6 
and ubuntu 18.04 is 1.5

**Comment by grampelberg** [comment]
Honestly, that sounds fine. Give it a try and see if that works.

**Comment by aliariff** [comment]
Closed. More thorough design will follow in the RFC repo.

**Pull request closed without merging**
