### PR TITLE
Remove admin policy resources from extensions

### LINKED ISSUE #9364: Investigate which extensions need policy resources for probes
### What problem are you trying to solve?

#6846 introduced policy resources for authorization probes in Linkerd extensions. As of #9008, probes are authorized by default when no other Server selects that workload.

We should investigate which extensions still need explicit probe authorizations (because another Server already should exist for that workload) and which ones can be removed.

### How should the problem be solved?

Unnecessary policy resources can be removed from the templates.

### Any alternatives you've considered?

NA

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

_No response_

### PR DESCRIPTION
**Pull request by adleong**
Fixes #9364

Since probes are automatically authorized, Linkerd extensions no longer need admin Server resources in order for probes to be authorized.  We therefore remove them.

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Review by kleimkuhler — APPROVED** [review]
Awesome!

**Review by mateiidavid — APPROVED** [review]
Looks good. We still have a policy for the jaeger-injector webhook though.

https://github.com/linkerd/linkerd2/blob/main/jaeger/charts/linkerd-jaeger/templates/jaeger-injector-policy.yaml

Do we want to remove it? It seems to allow unauthenticated traffic on `jaeger-admin` port, and to the `http-admin` port. If probes are allowed by default, we could probably delete the whole policy file (otherwise with an existing server we won't get the probe authorized automatically). Wdyt? Not a blocker so approving.

**Comment by adleong** [comment]
@mateiidavid This policy is in place so that the kube-api can call the webhook, rather than for liveness probes.  We narrow this policy in aother PR: https://github.com/linkerd/linkerd2/pull/10079/files#diff-110442f53b1edeb69551e5469d800e951619b706f394512cacb35ba182592081

**Comment by whiskeysierra** [comment]
This had some undesired side effects and I'm not sure whether those are accidental or intentional.
Those policies were not very fine-grained, i.e. instead of targeting `:4191/live` and `:4191/ready` respectively, they just targeted port `4191` in its entirety.
But that port also serves `/metrics` to prometheus.

When someone BYO Prometheus coupled with a cluster-wide default policy of `deny` then those policies were important to still allow access to `:4191/metrics`.

See also https://github.com/linkerd/linkerd2/issues/10691

**Pull request merged**
