### PR TITLE
Only process server updates on workloads affected by the server

### PR DESCRIPTION
**Pull request by adleong**
We the destination controller's workload watcher receives an update for any Server resource, it recomputes opaqueness for every workload.  This is because the Server update may have changed opaqueness for that workload.  However, this is very CPU intensive for the destination controller, especially during resyncs when we get Server updates for every Server resource in the cluster.

Instead, we only need to recompute opaqueness for workloads that are selected by the old version of the Server or by the new version of the Server.  If a workload is not selected by either the new or old version of the Server, then the Server update cannot have changed the workload's opaqueness.

### CODE REVIEW

**Review by alpeb — APPROVED** [review]
Noice! :cowboy_hat_face: :ship:

**Review by zaharidichev — APPROVED** [review]
Very nice. I think this is certainly better than skipping resyncs completely.

**Comment by alpeb** [comment]
Does this address #11995?

**Comment by adleong** [comment]
@alpeb no it doesn't

**Pull request merged**
