### PR TITLE
Fix Pod Volume Conflict in Linkerd Jaeger Injector

### LINKED ISSUE #11254: linkerd-jaeger injector fails when pod already has a podinfo volume
### What is the issue?

The following template is attempted to be applied and the `podinfo` volume may conflict with an existing definition leading to an error when the pod is provisioning.
https://github.com/linkerd/linkerd2/blob/51214c06668e7585f33649327a39b87fe655eefa/jaeger/injector/mutator/patch.go#L41-L57

### How can it be reproduced?

Create a meshed pod that already has a `podinfo` downward API volume.

### Logs, error output, etc

```
Error creating: Pod "my-pod-796d57f667-bbt76" is invalid: spec.volumes[10].name: Duplicate value: "podinfo"
```

### output of `linkerd check -o short`

```text
linkerd-config
--------------
× control plane CustomResourceDefinitions exist
    CRD httproutes.policy.linkerd.io is missing version v1beta2
    see https://linkerd.io/2.13/checks/#l5d-existence-crd for hints
```

### Environment

- Kubernetes version: 1.23.17-eks
- LInkerd version stable-2.12.4

### Possible solution

The podinfo section could be merged with an existing one or the existing one checked before applying that patch.

Assuming `podinfo` can be alternatively named, the volume could also be prefixed with a linkerd specific name.

### Additional context

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by moki1202**
Fixes #11254 

Signed-off-by: Shashank [shashanksingh819@gmail.com](mailto:shashanksingh819@gmail.com)

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
Thanks, @moki1202 

Doesn't the name of the volume need to be updated as well to match the volume mount?

**Comment by moki1202** [comment]
My apologies, missed that!

**Comment by moki1202** [comment]
@adleong (not related to this PR) I wanted to ask whether linkerd's taking part in LFX this term(spring). I apologize for asking this here ( I couldn't get a response on slack ;-; )!

**Review by alpeb — APPROVED** [review]
This looks good to me @moki1202 :+1:

**Review by adleong — APPROVED** [review]

**Pull request merged**
