### PR TITLE
Fix typo in healthcheck error message

### PR DESCRIPTION
**Pull request by pradeepnnv**
Fixes https://github.com/linkerd/linkerd2/issues/5438

Signed-off-by: pradeepnnv <pradeepnnv@gmail.com>

### CODE REVIEW

**Review by cpretzer — COMMENTED** [review]
Thanks @pradeepnnv this is a good catch.

I think the test failures might be due to flakiness so I'll rerun them and approve this merge when it goes green

**Review by alpeb — APPROVED** [review]
LGTM :+1:

**Review by adleong — APPROVED** [review]

**Comment by kleimkuhler** [comment]
Hi @pradeepnnv! If you could please merge the latest `main` into this branch, it will resolve some issues that were causing CI to fail. As this already has the needed approvals, we'll be able to merge after it passes. Thanks!

**Comment by pradeepnnv** [comment]
HI @kleimkuhler , it's merged now. 
Please review.

**Pull request merged**
