### PR TITLE
cli: Support custom namespace installation

### LINKED ISSUE #5239: Inability to specify `--linkerd-namespace` via the CLI in stable-2.9.0
### What is the issue?

When attempting to upgrade to `stable-2.9.0` by generating the YAML files using the `linkerd` command line interface, specifying a non-default namespace via the `--linkerd-namespace` no longer seems to be respected and the default `linkerd` namespace is used instead

### How can it be reproduced?

```linkerd  install --ignore-cluster --linkerd-namespace=custom-namespace```

When inspecting the output YAML, the `custom-namespace` namespace does not appear. When running the same command on `stable-2.8.0` it does.

### Environment

- OS: MacOS
- Linkerd version: stable-2.9.0

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #5239 

We did a revamp of the flags logic recently, and most flags had
relevant logic and what has to be done, except for
`--linkerd-namespace`.

I'm guessing the reason we forgot this is that this specific flag is a root flag
i.e applicable under all commands.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Review by kleimkuhler — APPROVED** [review]
lgtm 👍

**Review by cpretzer — APPROVED** [review]
Nice work @Pothulapati 

This is working in my local env

**Comment by cpretzer** [comment]
@Pothulapati Looking through the tests, I don't see one that tests a custom `linkerd-namespace` on install. Did I overlook it?

If there isn't one, we should add it.

**Comment by adleong** [comment]
This adds an additional `linkerd-namespace` flag in addition to the one defined in the persistent flags in `root.go`.  I assume that the new one replaces the persistent one in the subcommands that it's added to, but this is confusing.  For example, it will mean that the CLI package global variable `controlPlaneNamespace` may not match the `globals.namespace` field in the values struct.

What about this instead: after creating a new values struct in `install.go` and `upgrade.go`, we set the global.namespace field to the `controlPlaneNamespace` (which was populated from the persistent root level flag).

**Comment by Pothulapati** [comment]
Yep, That makes sense!

> after creating a new values struct in install.go and upgrade.go, we set the global.namespace field to the controlPlaneNamespace (which was populated from the persistent root level flag).

How about adding that into `render()` which is common between installl and upgrade? Considering folks would want cli flag to take highest precedence when set (instead of current stored config), It should work as expected.

**Review by adleong — APPROVED** [review]
Nice!

**Pull request merged**
