### PR TITLE
Issue #2809 Update webpack-dev-server to ^3.2.0

### LINKED ISSUE #2809: web: build errors on bin/web setup for fsevents using node 12
## Bug Report
Build errors occur when running `bin/web setup` with node 12 on MacOS Mojave.

**NB**: The messages indicate that the module is optional and the errors can be ignored, however the dashboard will crash. I'll file a separate issue for that.

### What is the issue?
When following the [web build instructions](https://github.com/linkerd/linkerd2/blob/master/BUILD.md#web) using node 12 or higher, the build errors in [this related gist](https://gist.github.com/cpretzer/824b2c4b0e08474613ff71c84ebad5e0) occur, because the webpack-dev-server defined in 3.1.14 depends on a version of [chokidar](https://github.com/paulmillr/chokidar) which has a dependency on an incompatible version of fsevents (1.2.4).

The build process attempts to retrieve the version of fsevents v1.2.4 for node 12 (v72) which is not available. The build process tries build the library because the file does not exist on the fsevents CDN. See the errors in the error section below.

### How can it be reproduced?
These steps assume that homebrew is installed.

Install node version 12 or higher and follow the steps in the [build guide for the web](https://github.com/linkerd/linkerd2/blob/master/BUILD.md#web)

```
brew install node
```

verify node version 12
```
node --version
```

clone the repository, install yarn, and run setup
```
git clone https://github.com/linkerd/linkerd2
brew install yarn
bin/web setup
```

### Logs, error output, etc
```
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
```

The underlying error comes from nan:
```
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/user/.node-gyp/12.1.0/include/node/v8.h:5380:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
```

The entire log file is at [this](https://gist.github.com/cpretzer/824b2c4b0e08474613ff71c84ebad5e0) gist

#### `linkerd check` output
The linkerd check output does not apply to building  the web component, but the output is included here for completeness.

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version:
v1.10.11

- Cluster Environment: (GKE, AKS, kops, ...)
Docker Desktop for Mac running Kubernetes

- Host OS:
MacOS Mojave

- Linkerd version:
stable-2.3.0

### Possible solution
Update package.json with a more recent version of `webpack-dev-server (^3.2.0)`

### Additional context
I've tested webpack-dev-server 3.2.0 with node 10.X and the build works as expected

### PR DESCRIPTION
**Pull request by cpretzer**
Problem: 
Build instructions produce errors on MacOS Mojave with Node 12

Solution: 
Update webpack-server-dev to version ^3.2.0 to ensure that a compatible version of [chokidar](https://github.com/paulmillr/chokidar) is resolved.

Validation:
Ran the build `bin/web` `dev` and `run` scripts with Node 12 without any errors.
Ran same scripts with fix using Node 10 as a regression test.

Fixes #2809

### CODE REVIEW

**Comment by rmars** [comment]
Yeah, I get those errors too - running `bin/web` before running `bin/web dev` or saving a file to cause the hot reloader to recompile solves the `iteratee is not a fn` errors for me. Though we might want to investigate getting that to run more smoothly.

Also, we should probably fix the `require` errors that now show up in the console with this branch. It's kinda scary to open up the dev console and see a bunch of errors.

As for specifying a node version, that's a good suggestion! Looks like it is [possible](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json) to do. We could also maybe add to the readme that the developer should make sure they're running node >12.

**Comment by cpretzer** [comment]
@dadjeibaah @rmars I ran in to the `iteratee` errors as well and determined that they are part of a second, separate issue which I'll be opening shortly.

**Comment by cpretzer** [comment]
The fix for #2817 supersedes this one because I had to merge the two in order to resolve the errors.

I think that this one can be closed.

**Comment by cpretzer** [comment]
Closing this pull request because pull request #2818 has the changes from this pull request

**Pull request closed without merging**
