### PR TITLE
Add version check to Grafana dashboard

### LINKED ISSUE #1607: Add version checking to the grafana dashboards
We've got an awesome version check in the `linkerd dashboard`, but not in grafana. Let's add that into grafana so that folks can see it as part of all the dashboards!

### PR DESCRIPTION
**Pull request by siggy**
The web dashboard checks the local Linkerd version against the latest
release, and informs the user if an update is available. Grafana was not
doing this.

Modify the Grafana dashboard to perform a version check, and prompt the
user to update if needed.

Fixes #1607

Signed-off-by: Andrew Seigner <siggy@buoyant.io>

Open question: Do we want this on the top-line dashboard, or on every Grafana dashboard?

screen shot 2018-09-13 at 9 36 44 am

screen shot 2018-09-13 at 9 37 06 am

Since the code change is embedded in a single line in the Grafana dashboard, I'll include it here also for easier review:

```html
<div>
  <div style="position: absolute; top: 0, left: 0">
    <a href="https://linkerd.io" target="_blank"><img src="https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg" style="height: 30px;"></a>
  </div>
  <div id="version" style="position: absolute; top: 0; right: 0; font-size: 15px">
  </div>
</div>
<script type="text/javascript">
var localReqURL =
  window.location.href.substring(
    0,
    window.location.href.indexOf(
    "/services/grafana:http/proxy/"
    )
  )+'/services/web:http/proxy/overview';

fetch(localReqURL, {
  credentials: 'include',
  headers: {
    "Content-Type": "text/html; charset=utf-8",
  },
})
.then(response => response.text())
.then(text => (new window.DOMParser()).parseFromString(text, "text/html"))
.then(html => {
  var main = html.getElementById('main');
  var localVersion = main.getAttribute("data-release-version");
  var uuid = main.getAttribute("data-uuid");

  var versionElem = document.getElementById('version');
  versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';

  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {
    credentials: 'include',
    headers: {
      "Content-Type": "application/json; charset=utf-8",
    },
  })
  .then(response => response.json())
  .then(json => {
    if (json.version === localVersion) {
      versionElem.innerHTML += 'Linkerd is up to date.';
    } else {
      versionElem.innerHTML += "A new version ("+json.version+") is available. <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.";
    }
  });
});
</script>
```

### CODE REVIEW

**Comment by wmorgan** [comment]
I think we should remove the "Linkerd is a ..." text entirely, and have it read purely "Running Linkerd vx.x.x. Linkerd is up to date."

(Don't forget the trailing period!)

**Comment by siggy** [comment]
@wmorgan we don't use trailing periods on the web dashboard... shall I make them consistent? which way?
screen shot 2018-09-13 at 9 33 03 am

**Comment by wmorgan** [comment]
Since we have multiple sentences at this point, my preference is to add trailing periods and make everything a real sentence, just like how you have the original screenshot in this PR.

**Comment by grampelberg** [comment]
@siggy could you change from `XMLHttpRequest` to `fetch` and add `{ credentials: 'include' }` as options?

You'll want to switch over to promises as well as part of that:

```javascript
fetch(localReqURL, { credentials: 'include' })
  .then()
```

**Pull request merged**
