### PR TITLE
Custom labels and annotations on helm deployments and services

### LINKED ISSUE #4537: helm chart support for arbitrary labels and annotations
## Feature Request

I would like the ability to add arbitrary labels and annotations to any deployment or service created by the chart

### What problem are you trying to solve?

The issue I am personally trying to solve is how to add a `cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'` label to the proxy-injector so I don't have new pods potentially falling out of the service mesh during a simultaneous autoscaling event and deployment. There are many other use cases that depend on an individual's needs.

### How should the problem be solved?

What do you want to happen? Add any considered drawbacks.

Looking at `proxy-injector.yaml`, There exists the following labels spec
```
  labels:
    app.kubernetes.io/name: proxy-injector
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: {{default .Values.global.linkerdVersion .Values.global.controllerImageVersion}}
    {{.Values.global.controllerComponentLabel}}: proxy-injector
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
```
Adding something like below would allow users of the chart to add their own arbitrary labels
```
{{- if .Values.proxy-injector.labels}}
{{ toYaml .Values.proxy-injector.labels | indent 6 }}
{{- end }}
```
This pattern can be repeated for annotations and labels across all Deployments and Services created by the chart

### PR DESCRIPTION
**Pull request by ConnorGraham**
There are use cases that may require cluster administrators to add arbitrary annotations and labels to linkerd deployments and services.

Added the following new properties in values.yaml and corresponding deployments and services

```
controller.service.labels
controller.service.annotations
controller.deployment.labels
controller.deployment.annotations

destination.service.labels
destination.service.annotations
destination.deployment.labels
destination.deployment.annotations

identity.service.labels
identity.service.annotations
identity.deployment.labels
identity.deployment.annotations

prometheus.service.labels
prometheus.service.annotations
prometheus.deployment.labels
prometheus.deployment.annotations

proxyInjector.service.labels
proxyInjector.service.annotations
proxyInjector.deployment.labels
proxyInjector.deployment.annotations

smiMetrics.service.labels
smiMetrics.service.annotations
smiMetrics.deployment.labels
smiMetrics.deployment.annotations

profileValidator.service.labels
profileValidator.service.annotations
profileValidator.deployment.labels
profileValidator.deployment.annotations

tap.service.labels
tap.service.annotations
tap.deployment.labels
tap.deployment.annotations

dashboard.service.labels
dashboard.service.annotations
dashboard.deployment.labels
dashboard.deployment.annotations
```

I had to create new root level objects in values.yaml for
* prometheus
* controller
* destination
because appropriate existing objects did not exist

Fixes #4537 

Signed-off-by: Connor Graham <connormwg@gmail.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
Hey @ConnorGraham, Thanks for the PR.

Why not have a single `labels` and `annotaitons` that is applied to all the Linkerd components? I could be definitely missing something here, and happy to learn about your use-case. :D

**Comment by Pothulapati** [comment]
Ahhh, Just came across https://github.com/linkerd/linkerd2/issues/4537, and it sounds reasonable for cases like that to have separate fields.

**Comment by alpeb** [comment]
@ConnorGraham can you please take care of the DCO requirement, as explained in the [contributing guide](https://github.com/linkerd/linkerd2/blob/master/CONTRIBUTING.md)?

**Comment by ConnorGraham** [comment]
> @ConnorGraham can you please take care of the DCO requirement, as explained in the [contributing guide](https://github.com/linkerd/linkerd2/blob/master/CONTRIBUTING.md)?

Added sign off to commit message - Sorry. This is my first contribution

**Comment by Pothulapati** [comment]
Hey @ConnorGraham, No Problem :) 
Can you perform a merge with the latest master and fix the merge conflicts?

**Comment by grampelberg** [comment]
@ConnorGraham still up for getting this over the finish line?

**Comment by ihcsim** [comment]
@ConnorGraham We are closing this for now, due to lack of activities. Feel free to re-open when you are ready.

**Pull request closed without merging**
