### PR TITLE
smi: remove default functionality in linkerd

### PR DESCRIPTION
**Pull request by Pothulapati**
Now, that SMI functionality is fully being moved into the
[linkerd-smi](www.github.com/linkerd/linkerd-smi) extension, we can
stop supporting its functionality by default.

This means that the `destination` component will stop reacting
to the `TrafficSplit` objects. When `linkerd-smi` is installed,
It does the conversion of `TrafficSplit` objects to `ServiceProfiles`
that destination components can understand, and will react accordingly.

Also, Whenever a `ServiceProfile` with traffic splitting is associated
with a service, the same information (i.e splits and weights) is also
surfaced through the `UI` (in the new `services` tab) and the `viz cmd`.
So, We are not really loosing any UI functionality here.

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
Raised https://github.com/linkerd/linkerd-smi/pull/18 to move the CRD into the extension

**Review by kleimkuhler — DISMISSED** [review]
👍

**Review by adleong — APPROVED** [review]
Yayyyyyyyy!

**Review by kleimkuhler — CHANGES_REQUESTED** [review]
It looks like the failures are related to the change and we are unable to sync the k8s API caches.

This occurs because we still `InitializeAPI` with `TS` specified as a resource ([code](https://github.com/linkerd/linkerd2/blob/5e6a1b550872751149552a043f8ff5dda875c40d/controller/cmd/destination/main.go#L92-L106)).

We should remove that now as well as all the handling of `TS` in `controller/k8s/api.go`. The actual error we see (`failed to sync caches`) happens because we're still trying to configure a TrafficSplit informer ([code](https://github.com/linkerd/linkerd2/blob/45478b6db836771bb57d87cbd60f64ea572c5527/controller/k8s/api.go#L275-L281)).

**Comment by kleimkuhler** [comment]
We don't need to watch TrafficSplits anymore so we can remove that rule from the destination's cluster role ([code](https://github.com/linkerd/linkerd2/blob/6d3f00357aa8a9d87f768a9b081cc06ad90de6d7/charts/linkerd2/templates/destination-rbac.yaml#L25-L26)).

**Review by kleimkuhler — APPROVED** [review]
Needs to be merged with `main` to pick up the 404 fix but otherwise this looks good to me.

**Pull request merged**
