### PR TITLE
Decode durations from protobuf into golang correctly

### PR DESCRIPTION
**Pull request by Pothulapati**
This PR updates the retrieval of durations from `linkerd-config`
to have conversion into the normal Go duration. This is needed
as the duration types in protobuf and golang are different.

This did not break anything previously, as we were directly using
these fields only for protobuf generation with upgrades, but now that
we are trying to use these fields with the `Values` go types (with the
new config format) this causes the upgrade tests to fail.

This is in sync with the encoding part here https://github.com/linkerd/linkerd2/blob/db57611a33b00a8f005a7ac65c4eeb7658189e50/cli/cmd/install.go#L1255

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
This was needed both with #4915 and #4941, So hence felt its better to make a separate PR and get this merged first.

**Comment by adleong** [comment]
I don't think we need to do this since we're moving over to having these components load configuration either from flags or from serialized Values, as described in https://github.com/linkerd/linkerd2/issues/5009.

The only place where we should need to load the config protobuf is in the legacy upgrade scenario.

**Comment by Pothulapati** [comment]
@adleong Hmmm, This was mainly needed for tests to pass, as it renders incorrectly causing **only the diff to fail** in `TestUpgrade*` tests.

As I understand from #5005, I could not find `protobuf.Duration` -> `golang.Duration conversion` in the` legacyUpgrade` logic here https://github.com/linkerd/linkerd2/blob/bac357d812fbd451656bcbd04177148a2e4e698b/cli/cmd/upgrade_legacy.go#L156. Is the conversion not needed? :thinking:

**Comment by Pothulapati** [comment]
Closing this, as it's not needed anymore

**Pull request closed without merging**
