### PR TITLE
Fix missing resource-cni label on linkerd-cni

### LINKED ISSUE #11058: Add misssing labels to LinkerD components to skip mutation webhook
### What is the issue?

Requirements:
- LinkerD config is set to `webhookFailurePolicy: Fail`
- An issue happens to the ProxyInjector workload
- LinkerD control plane is configured to use LinkerD CNI

If all requirements are met, then the the LinkerD cni will fail to come up as the mutation webhook is failing. And since the LinnkerD CNI is down, most workloads will have a bad time working as the network will quickly stop working.

The issue is that the LinkerD CNI pods are missing the label `linkerd.io/cni-resource`. This label is present by default in LinkerD's configmap as part of the `proxyInjector` section.

In the current release, the pods for the LinkerD CNI only contains the label `k8s-app: linkerd-cni`.

All we need to do is add the label `linkerd.io/cni-resource` to the daemonset **pods** of LinkerD CNI to it automatically gets skipped from the mutation webhooks.

### How can it be reproduced?

- Install latest LinkerD Control Plane + LinkerD CNI helm charts
- Change the LinkerD configmap with `webhookFailurePolicy: Fail`
- Intentionally break the LinkerD CNI daemonset (in my case was a race condition with the AWS VPC CNI - but this issue is more general and not completely related to the AWS VPC CNI) 

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

LinkerD check is successful. The issue is only when the proxy injector breaks.

### Environment

- Kubernetes Version: 1.24
- LinkerD Version: v2.13.2
- LinkerD CNI: v.1.1.1

### Possible solution

Add missing labels to LinkerD CNI daemonset pods. This change is very small and should be done in the Helm charts only. No code changes are required for this.

### Additional context

_No response_

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by migueleliasweb**
Move  `linkerd.io/cni-resource: "true"` from an annotation to a label in linkerd-cni.

This will improve the decoupling of the linkerd cni and the linkerd control plane (proxy injector).

With this change, even if the proxy injector is broken (for whatever reason), the linkerd-cni can still come up. Currently, since the label is not present (and if you configure the MutatingWebhook with a policy `fail`) the cni pods will completely fail to come up and this might cause and outage.

See default `objectSelector` for the `MutatingWebhook`: https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values.yaml#L370

Closes #11058

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @migueleliasweb !
Now you just need to run `go test ./... -update` to update the test fixtures and commit the changes.

**Comment by migueleliasweb** [comment]
> Thanks @migueleliasweb ! Now you just need to run `go test ./... -update` to update the test fixtures and commit the changes.

I will action this today :)

**Comment by migueleliasweb** [comment]
The command `go test ./... -update` didn't quite work for me although it did create the updates on the `.golden` files. I will wait to see if the whole CI passes and we'll go from there :+1: .

**Comment by migueleliasweb** [comment]
Some of the output from the failed tests:

```
$ go test -v ./... -update
```

```
FAIL	github.com/linkerd/linkerd2/viz/tap/pkg	0.035s
?   	github.com/linkerd/linkerd2/web	[no test files]
flag provided but not defined: -update
```

```
FAIL	github.com/linkerd/linkerd2/viz/tap/api	0.019s
?   	github.com/linkerd/linkerd2/viz/tap/cmd	[no test files]
?   	github.com/linkerd/linkerd2/viz/tap/gen/tap	[no test files]
?   	github.com/linkerd/linkerd2/viz/tap/injector	[no test files]
flag provided but not defined: -update
```

```
FAIL	github.com/linkerd/linkerd2/viz/pkg/util	0.019s
?   	github.com/linkerd/linkerd2/viz/static	[no test files]
flag provided but not defined: -update
```

**Review by alpeb — APPROVED** [review]
It all looks good now @migueleliasweb :+1: 
Indeed, the output of `test ./... -update` errors out, but it does accomplish the goal. Not sure if it's worth "fixing" if that implies adding more flags or env vars...

**Review by mateiidavid — APPROVED** [review]

**Pull request merged**
