### PR TITLE
Add @mateiidavid to maintainers

### PR DESCRIPTION
**Pull request by olix0r**
@mateiidavid has a solid history of contributing to Linkerd over the
past six+ months. Notably, he led a project to introduce StatefulSet
support for the `linkerd-multicluster` extension comprising changes
across the stack from the service-mirror and destination controllers to
the proxy. Furthermore, he's been an active contributor to code reviews
and support discussions on GitHub and the Linkerd Slack.

This change adds @mateiidavid to `MAINTAINERS.md`. Once this change is
merged, he'll also be added to the relevant GitHub groups so that he has
approval and merge privileges on Linkerd repos.

### CODE REVIEW

**Review by alpeb — APPROVED** [review]
Wohoo! Congrats @mateiidavid ! :1st_place_medal:

**Review by adleong — APPROVED** [review]
Well deserved!

**Review by Pothulapati — APPROVED** [review]
Well Deserved! :shipit:

**Review by kleimkuhler — APPROVED** [review]
🎉

**Pull request merged**
