### PR TITLE
Stop rendering addon config

### PR DESCRIPTION
**Pull request by adleong**
The linkerd-addon-config is no longer used and can be safely removed.

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Review by kleimkuhler — APPROVED** [review]
Aside from the lint and `install_helm_output_ha_namespace_selector.golden` getting updated, this looks good

**Review by Pothulapati — APPROVED** [review]
This LGTM, except for the linting and golden updates :shipit:

**Review by alpeb — APPROVED** [review]
LGTM :+1:

**Comment by alpeb** [comment]
Not strictly related to this PR, but rather to the other one that renamed `--addon-config`, there's still a mention to that flag in `charts/addons/prometheus/values.yaml` :eye:

**Pull request merged**
