### PR TITLE
feat: use direct image import in policy controller tests

### PR DESCRIPTION
**Pull request by krzysztofdrys**
Direct image import should be faster, when docker and cluster are on the
same node.

Signed-off-by: Krzysztof Dryś <krzysztofdrys@gmail.com>

### CODE REVIEW

**Comment by mateiidavid** [comment]
@krzysztofdrys do you happen to have a link to read up on the diff between all import modes? Sadly, the link pointed to by k3d gives a 404 (https://k3d.io/usage/guides/importing_images/) and I couldn't find mentions of it in their docs.

**Comment by olix0r** [comment]
@mateiidavid https://k3d.io/v5.4.3/usage/importing_images/

**Review by olix0r — APPROVED** [review]

**Comment by krzysztofdrys** [comment]
@olix0r I guess `bin/image-load` is a good case for `-m auto`. I can add it there. Should I do it this PR or open another one?

**Comment by krzysztofdrys** [comment]
I updated the mode in `bin/image-load` to `auto`. The tests pass, but I don't think change it the runtime is very significant.

**Review by mateiidavid — APPROVED** [review]

**Pull request merged**
