### PR TITLE
Removed hostNetwork: true from linkerd-cni Helm chart templates

### LINKED ISSUE #11141: Remove `hostNetwork: true` from linkerd-cni Helm chart templates
### What problem are you trying to solve?

Current does Linkerd CNI Helm chart templates have `hostNetwork: true` set which is unnecessary and less secure. 

### How should the problem be solved?

We should remove it from the chart template, or in the alternative, make it default `false` if we want to preserve the option to set it to true when needed.

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

Helm charts

### Would you like to work on this feature?

None

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
Problem - Current does Linkerd CNI Helm chart templates have hostNetwork: true set which is unnecessary and less secure.

Solution - Removed hostNetwork: true from linkerd-cni Helm chart templates

This PR Fixes #11141 

Signed-off-by: Abhijeet Gaurav <abhijeetdav24aug@gmail.com>

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @abhijeetgauravm . Can you please remove those lines altogether instead of replacing them with blank lines?

**Comment by abhijeetgauravm** [comment]
ok sure! @alpeb

**Comment by abhijeetgauravm** [comment]
Done Sir! @alpeb

**Review by alpeb — APPROVED** [review]

**Review by alpeb — CHANGES_REQUESTED** [review]
Please run `go test ./... -update` to update the unit test fixtures with changes from these templates.
Also please remove [this entry](https://github.com/linkerd/linkerd2/blob/main/pkg/healthcheck/healthcheck_test.go#L2421).

**Comment by abhijeetgauravm** [comment]
@alpeb removed that entry u mentioned but dont able to run go test ./... -update in my terminal even have recent version of go installed!

**Review by alpeb — APPROVED** [review]
I've pushed the golden file updates into your branch, and CI is green now :+1:

**Comment by abhijeetgauravm** [comment]
@alpeb Thanks!

**Review by mateiidavid — APPROVED** [review]

**Pull request merged**
