### PR TITLE
Bump golangci-lint to 1.17.1

### PR DESCRIPTION
**Pull request by siggy**
Also add `bodyclose` linter and remove `exclude-use-default: false`

Signed-off-by: Andrew Seigner <siggy@buoyant.io>

### CODE REVIEW

**Comment by adleong** [comment]
Is there any specific motivation for bumping this, or is this just to stay modern?  After reading the golangci-lint docs I still have no idea what `exclude-use-default` does.

**Comment by siggy** [comment]
@adleong Primarily to stay modern, also `bodyclose` is a nice addition.

We had original set `exclude-use-default: false` to ensure we were running a default `golint` linter. After a bit of git history spelunking, I'm going to add it back:
https://github.com/linkerd/linkerd2/pull/2239#discussion_r256675986

**Comment by siggy** [comment]
@adleong Most explicit location I can see for the linter version is at:
https://github.com/golangci/golangci-lint/blob/v1.17.1/go.mod#L23

I have not yet tried this, but here's some info on VS Code integration, ideally this could ensure that VS Code is linting via the same version of golangci-lint:
https://github.com/golangci/golangci-lint#editor-integration

**Comment by adleong** [comment]
Looks like it uses its own forked formatter here: https://github.com/golangci/golangci-lint/blob/v1.17.1/go.mod#L20

Looking at the git history of that repo: https://github.com/golangci/gofmt/commits/master

It looks like it was forked from this commit of goimports in the go tools repo:

https://github.com/golang/tools/tree/059bec968c61383b574810040ba9410712de36c5/cmd/goimports

So we probably want to standardize on using `goimports` built from revision `059bec9`

**Pull request merged**
