### PR TITLE
Add check for runAsRoot for docker container runtime

### PR DESCRIPTION
**Pull request by alex-berger**
@mateiidavid @alpeb as requested, the `linkerd check` for `proxy-init` `runAsRoot` setting.

Fixes https://github.com/linkerd/linkerd2/issues/7308
Followup to https://github.com/linkerd/linkerd2/pull/7348

Signed-off-by: Alexander Berger <alex-berger@gmx.ch>

### CODE REVIEW

**Review by mateiidavid — COMMENTED** [review]
@alex-berger thank you for the PR!

Tested using `minikube` (it uses the docker container runtime):

```
linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
× proxy-init container runs as root user if docker container runtime is used
    There are nodes using the docker container runtime and proxy-init container must run as root user.
        Try installing linkerd via --set proxyInit.runAsRoot=true
    see https://linkerd.io/2/checks/#l5d-proxy-init-run-as-root for hints

:; k get no minikube -o yaml | rg 'container'
    containerRuntimeVersion: docker://20.10.7

```

Everything looks good!

I wonder if this check would be better suited as a `--pre` check though (`linkerd check --pre`). We'd probably want to let users know ahead of time that they have to install Linkerd with the init container running as root. By the time they troubleshoot using `check`, Linkerd will have already been installed. 

We'd have to append the check to a different category, such as [`LinkerdPreInstallChecks`](https://github.com/linkerd/linkerd2/blob/6de3f8daebbe545c0d7d51f9e103432d21f33596/pkg/healthcheck/healthcheck.go#L549). I think this should be an easy change, afaict, we rely on the clientset being initialised for other pre install checks so there shouldn't be any blockers or concerns here. Wdyt?

**Review by mateiidavid — APPROVED** [review]
🚢 📦

**Comment by alpeb** [comment]
Thanks @alex-berger, the logic for the check looks good to me :+1:  I just have a couple of concerns about the location of the check and its wording.

If the node had the Docker container runtime, the linkerd pods wouldn't even start under the default config. So I think this check only makes sense under `linkerd check --pre` (@mateiidavid how did you got it to report till the `linkerd-config` section? it failed for me before, in the `linkerd-existence` checks).
OTOH, `linkerd check --pre` doesn't admit any linkerd config, so the wording "runs as root user if" doesn't sound like it fits there. I would be more brief, something like "no docker shim detected", yet still use the same detailed instructions you provided in case of failure.

**Comment by alex-berger** [comment]
@alpeb For me it makes sense to have the check in both places (`--pre` and `config`) because there can be mixed nodes (some with containerd and some still with docker as runtime) and those nodes can be dynamically allocated on-demand (e.g. by [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) or [karpenter](https://karpenter.sh/docs/getting-started/), ...) thus the `--pre` check might succeed (as at that time there are no docker nodes) but later the config check might fail (as docker nodes appear). Actually, this is exactly the setup we currently have in our clusters (which are slowly migrating to containerd in the course of the next months).

> OTOH, linkerd check --pre doesn't admit any linkerd config, so the wording "runs as root user if" doesn't sound like it fits there. I would be more brief, something like "no docker shim detected", yet still use the same detailed instructions you provided in case of failure.

I am not sure whether I understand your comment correct, but judging from the (pre PR) code the `--pre` checks have access to linkerd config, see the [InstallManifest](https://github.com/linkerd/linkerd2/blob/edge-21.11.4/cli/cmd/check.go#L171) field.

**Review by alpeb — APPROVED** [review]
Point taken on the mixed nodes scenario and so leaving the check in both places :slightly_smiling_face: 

My wording nit referred to the fact that for `linkerd --pre`, `runAsRoot` is always false, but given we'll be running this after install as well, then the messaging should be fine :+1:

**Pull request merged**
