### PR TITLE
Mark High Availability as non-experimental

### LINKED ISSUE #2419: Mark High Availability as non-experimental
### What is the issue?
The help text for `linkerd install` shows HA as experimental. The website (https://linkerd.io/2/features/ha/) also shows it as experiemental.
### How can it be reproduced?
Run `linkerd install -h`.
Visit https://linkerd.io/2/features/ha/.

# Environment
- Linkerd version: 2.2.1

### Possible solution
Remove phrasing for "experimental".

### PR DESCRIPTION
**Pull request by paranoidaditya**
Closes #2419

Signed-off-by: Aditya Sharma <hello@adi.run>

### CODE REVIEW

**Comment by paranoidaditya** [comment]
@jonrichards 👀

**Comment by jonrichards** [comment]
That looks great, thank you for doing that.

**Comment by ihcsim** [comment]
Sorry folks, I think I messed up on this one. I don't think HA has graduated from non-experimental yet. I'm gonna revert this change.

**Comment by grampelberg** [comment]
Ah damn, sorry about that @paranoidaditya! I got confused a little.

**Pull request merged**
