### PR TITLE
Bump prometheus version to 2.15.2

### LINKED ISSUE #3856: Upgrade Prometheus to 2.15
### What problem are you trying to solve?

There's a new Prometheus release out with lots of fantastic performance improvements. Let's bump the bundled version.

### PR DESCRIPTION
**Pull request by Pothulapati**
Fixes #3856 

Prometheus v2.15.0, contains significant performance improvements, and also an awesome experimental UI as per https://github.com/prometheus/prometheus/releases/tag/v2.15.0

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Comment by alpeb** [comment]
@Pothulapati Could you please bump to `2.15.1` released a few days ago containing a bugfix?

**Comment by Pothulapati** [comment]
@alpeb Done.
Sorry, should've realized that earlier :)

**Comment by Pothulapati** [comment]
There's a new Prometheus release with a small bug fix, Should we use that?
https://github.com/prometheus/prometheus/releases/tag/v2.15.2

**Comment by alpeb** [comment]
@Pothulapati Yeah go ahead, since we haven't merged this yet :slightly_smiling_face:

**Comment by Pothulapati** [comment]
@ihcsim Thanks for running those tests. :)

**Pull request merged**
