### PR TITLE
Create linkerd authz command

### PR DESCRIPTION
**Pull request by adleong**
We add a `linkerd authz <resource>` command for listing all server authorizations which apply to a specified resource.

```
> linkerd authz deployment/web -n emojivoto
  SERVER  AUTHORIZATION  
web-http     web-public 
```

It works by iterating through each authorization, using the label selector to find the authorization's servers, and then using the server's label selector to find all pods with that server.  If the requested resource contains any of the selected pods then we print the authorization.  Note that this relies entirely on the existence of resources and their label selector bindings, and does not depend on actual traffic or on proxy metrics.

### CODE REVIEW

**Review by kleimkuhler — COMMENTED** [review]
I'm using Tarun's [emojivoto policy resources](https://gist.githubusercontent.com/Pothulapati/69edb59fb1c54c3d993e1ad5145571d4/raw/897de1a8d57e3606420ca845c6abfd69bf241fb2/emojivoto-policy.yml) to test this. There is a `server/prom` with an authorization that allows linkerd-viz's Prometheus client.

When I run `bin/linkerd authz -n emojivoto deploy/emoji` shouldn't I also see that we have a server that allows traffic to `deploy/emoji` from Prometheus?

```
❯ bin/linkerd authz -n emojivoto deploy/emoji
    SERVER  AUTHORIZATION  
emoji-grpc     emoji-grpc
```

Also, maybe as a follow-up — but I think it's a pretty small change — we should support the command completion that was added to all the core and extension commands.

**Review by mateiidavid — COMMENTED** [review]
Worked great in my tests! Manifests are at the bottom of the comment.

**Set-up**: used emojivoto with two servers, each with its own authz policy. I created one server (and policy) for `web` and one server (and policy) to target two deployments, `voting` and `emoji`. I wanted to test the logic for both servers that match a label and servers that match a set (through `matchExpressions`).

```sh
#  First, get all based on deployment
# 
$ bin/linkerd authz -n emojivoto deploy
        SERVER        AUTHORIZATION
      web-http           web-public
emoji-n-voting  emoji-voting-public

#  Second, get web based on pod
#
$ bin/linkerd authz -n emojivoto po/web-5fdc656479-m6nqd
  SERVER  AUTHORIZATION
web-http     web-public

#  Third, get voting based on deploy
#  and emoji based on deploy
#
$  bin/linkerd authz -n emojivoto deploy/voting
        SERVER        AUTHORIZATION
emoji-n-voting  emoji-voting-public

$ bin/linkerd authz -n emojivoto deploy/emoji
        SERVER        AUTHORIZATION
emoji-n-voting  emoji-voting-public
```

<details><summary> Manifests </summary>

Saz and srv
```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: emojivoto
  name: web-http
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: web
    app.kubernetes.io/version: v11
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: emojivoto
      app.kubernetes.io/name: web
  port: 8080
---
apiVersion: policy.linkerd.io/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: emojivoto
  name: web-public
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/name: web
    app.kubernetes.io/version: v11
spec:
  server:
    name: web-http
  # Allow all clients to access the web HTTP port without regard for
  # authentication. If unauthenticated connections are permitted, there is no
  # need to describe authenticated clients.
  client:
    meshTLS:
      identities:
        - "*.emojivoto.serviceaccount.identity.linkerd.cluster.local"
          #networks:
          #- cidr: 0.0.0.0/0
          #- cidr: ::/0
---
apiVersion: policy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: emojivoto
  name: emoji-n-voting
  labels:
    app.kubernetes.io/part-of: emojivoto
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: ["emoji", "voting"]
  port: 8080
---
apiVersion: policy.linkerd.io/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: emojivoto
  name: emoji-voting-public
  labels:
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  server:
    name: emoji-n-voting
  # Allow all clients to access the web HTTP port without regard for
  # authentication. If unauthenticated connections are permitted, there is no
  # need to describe authenticated clients.
  client:
    meshTLS:
      identities:
        - "*.emojivoto.serviceaccount.identity.linkerd.cluster.local"
          #networks:
          #- cidr: 0.0.0.0/0
          #- cidr: ::/0
```

Emojivoto
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emoji
  namespace: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: emoji-svc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: emoji
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: emoji
        app.kubernetes.io/part-of: emojivoto
        app.kubernetes.io/version: v11
        app: emoji-svc
        version: v11
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: emoji
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: vote-bot
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v11
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: vote-bot
        app.kubernetes.io/part-of: emojivoto
        app.kubernetes.io/version: v11
        app: vote-bot
        version: v11
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: vote-bot
        resources:
          requests:
            cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: voting
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v11
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: voting
        app: voting-svc
        version: v11
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: web
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: web
        app: web-svc
        version: v11
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web
---
```

</details>

**Comment by adleong** [comment]
@kleimkuhler so if you just install emojivoto from run.linkerd.io the emojivoto deployments have the  `app.kubernetes.io/part-of=emojivoto` label, but it's not on the pod spec template so the emojivoto pods don't have that label.  Thus the server doesn't select those pods.  If you add the label to the pods, the prom server shows up as expected:

```console
alex@dev:~/workspace/linkerd2$ kubectl label -n emojivoto po --all app.kubernetes.io/part-of=emojivoto
pod/emoji-5f947b5dbd-b6rkl labeled
pod/vote-bot-64dd87cb87-txflf labeled
pod/voting-f7f875999-gx8ds labeled
pod/web-5798f7d79f-9w4rh labeled
alex@dev:~/workspace/linkerd2$ bin/linkerd authz -n emojivoto deploy
     SERVER    AUTHORIZATION  
 emoji-grpc       emoji-grpc  
       prom  prom-prometheus  
voting-grpc      voting-grpc  
   web-http       web-public
```

pretty cool that the `authz` command already has helped us detect misconfigurations 😁

**Review by mateiidavid — APPROVED** [review]

**Review by kleimkuhler — APPROVED** [review]
Still have a typo from my previous comment but otherwise looks good!

**Pull request merged**
