### PR TITLE
Parameterize PodDisruptionBudget config for Linkerd Control Plane components

### LINKED ISSUE #11321: Parameterize PodDisruptionBudget config for Linkerd Control Plane components.
### What problem are you trying to solve?

The `maxUnavailable` setting for all Linkerd Control Plane components is hardcoded to `1`:

https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/destination.yaml#L118
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/identity.yaml#L93
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/proxy-injector.yaml#L191

The above can work well with the proposed number of controller replicas in HA configurations, [which is 3](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values-ha.yaml#L29).

As it happens, we've increased the number of controller replicas to 5 in our environment, hence it'd be great to have the ability to tweak the `maxUnavailable` parameter (e.g. set to 2).

### How should the problem be solved?

Parameterize PodDisruptionBudget config in templates, which is currently hardcoded (maxUnavailable).

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

maybe

### PR DESCRIPTION
**Pull request by cdalar**
Parameterize PodDisruptionBudget config for Linkerd Control Plane components

The maxUnavailable setting for all Linkerd Control Plane components is hardcoded to 1

Parameterize PodDisruptionBudget config in templates, which is currently hardcoded (maxUnavailable), so that it can be configured from values.

Fixes #11321 

Signed-off-by: Cemal Y. Dalar <cemal@dalar.net>

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @cdalar (and sorry for the late reply!). This looks good to me, but a couple of things need to be addressed. The unit tests are failing because you still need to add an entry for `PodDisruptionBudget` into [this struct](https://github.com/linkerd/linkerd2/blob/edge-23.12.3/pkg/charts/linkerd2/values.go#L28). 

After doing that, you need to run `go test ./... -update` to update the test fixtures.
Finally, please run `./bin/helm-docs` to re-generate the `README.md` file with the new `values.yaml` entry.

**Comment by cdalar** [comment]
@alpeb , did the changes you mentioned. Hope that is good.

**Comment by alpeb** [comment]
A unit test in `values_test.go` is failing, as you can see here:
https://github.com/linkerd/linkerd2/actions/runs/7297741456/job/19896871341?pr=11687#step:6:172
You need to edit that file and fill in an appropriate value in the `expected` `Values` struct for `PodDisruptionBudget.MaxUnavailable` which now is different for the HA case.

**Review by alpeb — APPROVED** [review]
LGTM :+1:

**Comment by cdalar** [comment]
@alpeb . Do we need to ask from someone with write access to approve as well? @olix0r or do you need something else from me?

**Comment by kflynn** [comment]
@cdalar We got a couple of folks to look over this, and realized that we'd like one change – could you move `podDisruptionBudget` under `controller`, so that you'd set `controller.podDisruptionBudget.maxUnavailable`? (We're trying to be better about namespacing new parameters...) 

Thanks! 🙂

**Comment by cdalar** [comment]
> @cdalar We got a couple of folks to look over this, and realized that we'd like one change – could you move `podDisruptionBudget` under `controller`, so that you'd set `controller.podDisruptionBudget.maxUnavailable`? (We're trying to be better about namespacing new parameters...)
> 
> Thanks! 🙂

@kflynn . 👍  related changes have been made. Please check.. 

About namespacing; there are other parameters which should be inside the new controller object but I think it's out of this scope. Maybe later I can tackle them as well.

**Comment by cdalar** [comment]
@alpeb can you please re-run the tests..

**Comment by kflynn** [comment]
Hey @cdalar – I reran the test just to check, but it looks like a real failure. As @alpeb noted above, this one will need some test data to be regenerated:

- `go test ./... -update` should update the test fixtures, then
- `./bin/helm-docs` should re-generate the `README.md` file with the new `values.yaml` entry.

Try that? and then let's see where we are. 🙂

**Comment by cdalar** [comment]
> Hey @cdalar – I reran the test just to check, but it looks like a real failure. As @alpeb noted above, this one will need some test data to be regenerated:
> 
> * `go test ./... -update` should update the test fixtures, then
> * `./bin/helm-docs` should re-generate the `README.md` file with the new `values.yaml` entry.
> 
> Try that? and then let's see where we are. 🙂

@kflynn Run both commands. The `install_output.golden` has been updated now. I hope that is enough.

**Review by adleong — APPROVED** [review]
Thanks for your work and patience on this one!

**Pull request merged**
