### PR TITLE
Emit event when issuing leaf certificate

### PR DESCRIPTION
**Pull request by adleong**
We emit a Kubernetes event from the identity controller when successfully issuing a leaf certificate.  The events include the identity, expiry, and a hash of the certificate.  For example:

```
emojivoto   2m51s       Normal    IssuedLeafCertificate   serviceaccount/default                         issued certificate for default.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:34 +0000 UTC: 279a8df5785bb4967dce7f71aabe6eb5
emojivoto   2m53s       Normal    IssuedLeafCertificate   serviceaccount/emoji                           issued certificate for emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:32 +0000 UTC: 1152fce9ebef255555241aa8d6c2c10b
emojivoto   2m51s       Normal    IssuedLeafCertificate   serviceaccount/voting                          issued certificate for voting.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:34 +0000 UTC: 72d0f3f54c66fb2b6ef523e7be448544
emojivoto   2m51s       Normal    IssuedLeafCertificate   serviceaccount/web                             issued certificate for web.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:34 +0000 UTC: 1e748e4aac9a6847908f836ec454a97f
linkerd     3m8s        Normal    IssuedLeafCertificate   serviceaccount/linkerd-destination             issued certificate for linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:17 +0000 UTC: f0164fdd3e5fc1204979edd9aebc10e6
linkerd     3m7s        Normal    IssuedLeafCertificate   serviceaccount/linkerd-identity                issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:18 +0000 UTC: dcbbd6f47024c321ef35d93f40586406
linkerd     3m7s        Normal    IssuedLeafCertificate   serviceaccount/linkerd-proxy-injector          issued certificate for linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:19:18 +0000 UTC: 82938ecaaa682aeb156aae39add2628d
```

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Review by kleimkuhler — COMMENTED** [review]
Code looks good. Logging in the `linkerd-identity` pod also looks good; I see lines for when it issues certificates for other linkerd components as well as emojivoto.

I do not see events generated after issuing certs for emojivoto though:

```
❯ kubectl get -n linkerd events |rg 'IssuedLeafCertificate'
9m10s       Normal    IssuedLeafCertificate   serviceaccount/linkerd-identity ...
9m10s       Normal    IssuedLeafCertificate   serviceaccount/linkerd-destination ...
9m10s       Normal    IssuedLeafCertificate   serviceaccount/linkerd-proxy-injector ...
```

```
❯ kubectl logs -n linkerd linkerd-identity-5f4cf8bc7d-b6pgg identity
time="2021-06-24T21:06:01Z" level=info msg="running version git-fb596bdd"
time="2021-06-24T21:06:01Z" level=info msg="starting admin server on :9990"
time="2021-06-24T21:06:01Z" level=info msg="starting gRPC server on :8080"
time="2021-06-24T21:06:01Z" level=info msg="issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:06:21 +0000 UTC: 3cc703114aca6260b9ec7d6a512c04bb"
time="2021-06-24T21:06:01Z" level=info msg="issued certificate for linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:06:21 +0000 UTC: 65554414bb25627848f58e80a281c18d"
time="2021-06-24T21:06:01Z" level=info msg="issued certificate for linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:06:21 +0000 UTC: 32eefd448ca2563d44369073e0f39008"
time="2021-06-24T21:12:32Z" level=info msg="issued certificate for default.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:12:52 +0000 UTC: 7e1c6b3ee3f3364e9bbeec8021aef0be"
time="2021-06-24T21:12:32Z" level=info msg="issued certificate for voting.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:12:52 +0000 UTC: 470df87c40029ac9041426aaec03287c"
time="2021-06-24T21:12:32Z" level=info msg="issued certificate for emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:12:52 +0000 UTC: 2a1e13ac817f7d28acd543d4b3cdf74b"
time="2021-06-24T21:12:32Z" level=info msg="issued certificate for web.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-25 21:12:52 +0000 UTC: 88e239e593bc494ce1eea633ba40e17b"
```

We should be watching for events in all namespaces and based off your description you've seen it correctly log the events. I'm not sure what the issue is right now.

**Review by kleimkuhler — APPROVED** [review]
Events are in the `emojivoto` namespace. I was thinking since they are generated by `linkerd-identity` pod they'd show up in the `linkerd` namespace.

**Comment by adleong** [comment]
@kleimkuhler That's right.  I think ideally we might want these events associated with the pod that was issued the cert, but the identity controller currently doesn't have enough information to determine which pod is making the request.  In place of that, we associate the event with the service account which is used to make the request.  Since service accounts are namespaced, we see these events in the namespace of the service account / requesting pod.

**Comment by kleimkuhler** [comment]
Cool makes sense.

Do you have a sense from working on this what it would take to make the identity controller aware of the requesting pod? I'm thinking of situations where a deployment has more than 1 replica, we would generate multiple events for the same service account that only differ by their certificate hash. It may be nice to be able to distinguish the events by more than their certificate hash and trace each one back to a specific pod.

**Comment by adleong** [comment]
The two options which come to mind are:
* Add a field to the identity API for clients to send their pod name.  The proxy would need to get its pod name from the downward API and send it on identity requests.  We would probably want the proxy to handle this in an opaque way, similar to the context token it sends on destination requests.
* -OR-
* Have the identity's proxy set the Forwarded header on inbound requests so that the identity controller can read this header to determine the client's ip and then look up the pod by ip.

**Review by mateiidavid — APPROVED** [review]
Works and looks great!

```
kubectl get events -n emojivoto
60s         Normal   IssuedLeafCertificate   serviceaccount/emoji             issued certificate for emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-26 17:31:34 +0000 UTC: b499f50a6a6889ccdf3b9d196f4aabaf
60s         Normal   IssuedLeafCertificate   serviceaccount/default           issued certificate for default.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-26 17:31:34 +0000 UTC: 61dc1b991b661ff1c3934df2b180f6be
60s         Normal   IssuedLeafCertificate   serviceaccount/voting            issued certificate for voting.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-26 17:31:34 +0000 UTC: e12f97277b8476d3549c07dfcaf27b69
60s         Normal   IssuedLeafCertificate   serviceaccount/web               issued certificate for web.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-06-26 17:31:34 +0000 UTC: aedd3bd025b546f1d8c998c927c7c085
```

Like @kleimkuhler said it would be cool to have the events associated with the pod but since that work is not scoped as part of this PR I think this is good to 🚢  so approving.

**Pull request merged**
