### PR TITLE
Generate Identity certs with alternate domain names

### PR DESCRIPTION
**Pull request by Pothulapati**
Go 1.15 has been released recently and projects like Kubernetes, etc
have already moved to it.

Updating only the go version, makes the upgrades fail from older versions,
 as the identity certs do not have that setting and go 1.15 expects them.

This PR sets us up to upgrade to go 1.15 by first generating certs to have
that field, and then move to 1.15 in later versions

Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
Okay, For the checks to pass #4919 has to be merged, as the certs generated in Helm are read during upgrades, as go 1.15 expects certs with SANS, these tests fail.

The certs have been updated here by running the following commands (with 10 years lifetime)
```
step certificate create identity.linkerd.cluster.local ./cli/cmd/testdata/valid-trust-anchors.pem ca.key \\n--profile root-ca --no-password --insecure --san identity.linkerd.cluster.local --not-after 87600h
step certificate create identity.linkerd.cluster.local cli/cmd/testdata/valid-crt.pem ./cli/cmd/testdata/valid-key.pem --ca ./cli/cmd/testdata/valid-trust-anchors.pem --ca-key ca.key --profile intermediate-ca  --not-after 87600h --no-password --insecure --san identity.linkerd.cluster.local
step certificate create wrong.linkerd.cluster.local ./cli/cmd/testdata/wrong-domain-trust-anchors.pem ca.key \\n--profile root-ca --no-password --insecure --san wrong.linkerd.cluster.local --not-after 87600h
step certificate create identity.linkerd.cluster.local cli/cmd/testdata/wrong-domain-key.pem ./cli/cmd/testdata/wrong-domain-key.pem --ca ./cli/cmd/testdata/wrong-domain-trust-anchors.pem --ca-key ca.key --profile intermediate-ca  --not-after 87600h --no-password --insecure --san wrong.linkerd.cluster.local
step certificate create identity.linkerd.cluster.local cli/cmd/testdata/wrong-domain-crt.pem ./cli/cmd/testdata/wrong-domain-key.pem --ca ./cli/cmd/testdata/wrong-domain-trust-anchors.pem --ca-key ca.key --profile intermediate-ca  --not-after 87600h --no-password --insecure --san wrong.linkerd.cluster.local
step certificate create identity.linkerd.cluster.local ./cli/cmd/testdata/wrong-algo-trust-anchors.pem ca.key \\n--profile root-ca --no-password --insecure --san identity.linkerd.cluster.local --not-after 87600h --crv P-521 --kty EC
step certificate create identity.linkerd.cluster.local cli/cmd/testdata/wrong-algo-crt.pem ./cli/cmd/testdata/wrong-algo-key.pem --ca ./cli/cmd/testdata/wrong-algo-trust-anchors.pem --ca-key ca.key --profile intermediate-ca  --not-after 87600h --no-password --insecure --san identity.linkerd.cluster.local --crv P-521 --kty EC
```

**Comment by alpeb** [comment]
If I'm not mistaking, `install_test.go` will need its `TestInstallOrUpgradeCli` function to be updated as well, to pass to `linkerd install` the certs with SANs.

**Comment by Pothulapati** [comment]
@alpeb Looks like double quotes had to be added, as now the original values are returned from `parseDuration` as per ` When returning an error, ParseDuration now quotes the original value. ` from the [go 1.15 release notes ](https://golang.org/doc/go1.15)

**Comment by Pothulapati** [comment]
@alpeb Hmm, That's interesting! Because our older linkerd binaries/helm generate certs without SANs and the newer Golang expects them to have them, the upgrade command fails now! :thinking:

**Review by alpeb — APPROVED** [review]
LGTM :+1:

**Review by adleong — APPROVED** [review]

**Pull request merged**
