### PR TITLE
Add integration tests for linkerd endpoints and edges

### LINKED ISSUE #3477: Create integration test for `linkerd edges`
Just a minimal test comparing against some predefined output, to make sure the command is working.

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #3477 and #3478

### CODE REVIEW

**Comment by scottcarol** [comment]
Looking forward to reviewing this @alpeb! Would you recommend running these commands in order to test this branch?:
```
bin/docker-build
bin/linkerd install | kubectl apply -f -
bin/test-run
```

**Comment by alpeb** [comment]
@scottcarol :cool: !
`bin/docker-build`: yes (assuming you have your DOCKER_HOST env var set)
`bin/linkerd install | kubectl apply -f -`: no, you want the suite to take care of doing the installation

Then to just run the these two new tests (replace the last arg with the location of your built linkerd binary):
- First run the main test that creates the `l5d-integration` linkerd installation (which is the namespace that is targeted by these two new tests):
```
go test -v ./test -integration-tests -linkerd /home/alpeb/linkerd2/target/cli/linux/linkerd
```
- Then the test for edges:
```
go test -v ./test/edges -integration-tests -linkerd /home/alpeb/linkerd2/target/cli/linux/linkerd
```
- And then the test for endpoints:
```
go test -v ./test/endpoints -integration-tests -linkerd /home/alpeb/linkerd2/target/cli/linux/linkerd
```

Let me know how it goes!

**Comment by alpeb** [comment]
Thanks @scottcarol for the detailed feedback :mag: 
The syntax of the regex in the golden files needed some extra escaping, that's why it wasn't catching some of the errors you were trying. Also there was a problem in how I was setting the namespace. It should be fine now.
Also when the command fails, now I'll be showing what we actually get in stderr, as per your last comment ;-)
Let me know how it goes :-)

**Comment by alpeb** [comment]
Sounds great, thanks @scottcarol . I'll keep an eye open for failures :eye:

**Pull request merged**
