### PR TITLE
Return NotFound for unknown pod names

### LINKED ISSUE #11065: Failed requests to destination when using headless services
### What is the issue?

When trying to communicate with a headless service using its DNS name, the destination proxy tries to continuously discover its profile (`/io.linkerd.proxy.destination.Destination/GetProfile`) and fails. These failed requests do not show in tap and, when using 2.13 they do not count towards the "global" success rate of destination see https://github.com/linkerd/linkerd2/issues/11066.

Ideally this setup should not result in failed requests to destination, I assume that profiles are not available either since those requests are failing?

### How can it be reproduced?

- Add the manifests from [this gist ](https://gist.github.com/someone-stole-my-name/38a65ed93a6f98438281e67ea9ca3e48)
- Open viz and go to `/namespaces/linkerd/deployments/linkerd-destination`

### Logs, error output, etc

```
[    18.992783s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}: tower::balance::p2c::service: updating from discover
[    18.992895s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}: tower::buffer::worker: service.ready=true processing request
[    18.993060s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}:endpoint{addr=10.244.0.24:8086}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(69), flags: (0x4: END_HEADERS) }
[    18.993115s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}:endpoint{addr=10.244.0.24:8086}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(69) }
[    18.993126s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}:endpoint{addr=10.244.0.24:8086}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(69), flags: (0x1: END_STREAM) }
[    18.996186s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}:endpoint{addr=10.244.0.24:8086}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(69), flags: (0x5: END_HEADERS | END_STREAM) }
[    18.996308s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile: linkerd_tonic_watch: Request failed status=status: Unknown, message: "failed to get pod for hostname 10-244-0-28: no pod found in Endpoints default/server for hostname 10-244-0-28", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 28 Jun 2023 01:50:06 GMT"} }
[    18.996334s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.0.26:56094}:server{port=8080}:http:http{name=10-244-0-28.server.default.svc.cluster.local:8080}:profile: linkerd_tonic_watch: Recovering
```

### output of `linkerd check -o short`

```
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.4 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.4 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-6b566cf687-mzs2w (stable-2.13.4)
        * linkerd-identity-77bbfc58bb-mgrwh (stable-2.13.4)
        * linkerd-proxy-injector-6f5b6c8798-nw9f5 (stable-2.13.4)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * metrics-api-59c76c4d75-vqkw5 (stable-2.13.4)
        * prometheus-b7b44d965-dpflx (stable-2.13.4)
        * tap-7c8fb95758-tn5zb (stable-2.13.4)
        * tap-injector-586d58cf8f-x8t9r (stable-2.13.4)
        * web-7cf5484879-9g888 (stable-2.13.4)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- Kubernetes version: 1.26
- Environment: EKS & Minikube

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by adleong**
Fixes #11065

When an inbound proxy receives a request with a canonical name of the form `hostname.service.namespace.svc.cluster.domain`, we assume that `hostname` is the hostname of the pod as described in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields.  However, pods are also addressable with `pod-ip.service.namespace.svc.cluster.domain`.  When the destination controller gets a profile request of this form, we attempt to find a pod with hostname of `pod-ip` and return an error with gRPC status `Unknown` since this will not exist.

It is expected that this profile lookup will fail since we cannot have service profiles for individual pods.  However, returning a gRPC status `Unknown` for these requests brings the reported success rate of the destination controller down.  Instead we should return these as gRPC status `NotFound` so that these responses don't get reported as server errors.

### CODE REVIEW

**Review by mateiidavid — COMMENTED** [review]
Nice! Simple and straight to the point. I tested it and it works well.

One tiny suggestion. The change is made in `getEndpointByHostname()` which in turn will be called from `getOrNewPodPublisher`. In the latter, we are already formatting the error (see the linked snippet)
https://github.com/linkerd/linkerd2/blob/29e668357a8e1ce28afdbeb9b080b7f13914710e/controller/api/destination/watcher/pod_watcher.go#L277-L283

This yields the following error message:

```
:; go run controller/script/destination-client/main.go -token "{}" -path 10-23-0-37.nginx-svc.default.svc.cluster.local:80  -method getProfile
FATA[0000] rpc error: code = NotFound desc = failed to get pod for hostname 10-23-0-37: rpc error: code = NotFound desc = no pod found in Endpoints default/nginx-svc for hostname 10-23-0-37
exit status 1
```

If we take the formatting out of the calling function (pod watcher one) the error should look nicer:

```
:; go run controller/script/destination-client/main.go -token "{}" -path 10-23-0-37.nginx-svc.default.svc.cluster.local:80  -method getProfile
FATA[0000] rpc error: code = NotFound desc = no pod found in Endpoints default/nginx-svc for hostname 10-23-0-37
exit status 1


```

**Review by mateiidavid — APPROVED** [review]

**Review by alpeb — APPROVED** [review]
Nice :+1:

**Comment by annismckenzie** [comment]
Could this fix be backported to / included in the 2.14 release branch? Since https://github.com/linkerd/linkerd2-proxy/pull/2499 was merged and released in v2.14.3 we're now experiencing a lot of log spam when using headless services (as explained in the description above).

**Comment by wmorgan** [comment]
@annismckenzie Unfortunately we are no longer backporting to 2.14 except for critical security patches.

**Pull request merged**
