### PR TITLE
Flaky tests: ignore 'unable to copy pipes'

### LINKED ISSUE #4357: install_test flakiness: failed to create containerd task
I have ran into this multiple times over the last few days:
```
Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
"linkerd" has been added to your repositories
Test script: [install_test.go] Params: [--linkerd-namespace=l5d-integration-helm --helm-path=/home/runner/work/linkerd2/linkerd2/bin/helm --helm-chart=/home/runner/work/linkerd2/linkerd2/charts/linkerd2 --helm-stable-chart=linkerd/linkerd2 --helm-release=l5d-integration-test --tiller-ns=l5d-integration-tiller --upgrade-helm-from-version=stable-2.7.1]
--- FAIL: TestEvents (0.23s)
    install_test.go:774: Found unexpected warning events:
        Reason: [Failed] Object: [linkerd-sp-validator-646d4575d8-wv86g] Message: [Error: failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/run/containerd/io.containerd.grpc.v1.cri/containers/linkerd-proxy/io/702266748/linkerd-proxy-stdout" failed: context deadline exceeded]
```

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #4357

Tracked upstream in kubernetes/kubernetes/issues/89064

### CODE REVIEW

**Comment by adleong** [comment]
Is this error truly safe to ignore?  It looks scary and there isn't much info in the upstream issue.

**Comment by alpeb** [comment]
That issue itself links to containerd/containerd#4068. They are experience flaky tests under load. Not releated to Linkerd, so safe to ignore IMO.

**Comment by kleimkuhler** [comment]
@adleong Did you and Alejandro talk about this anymore in another channel?

**Comment by alpeb** [comment]
My bad @kleimkuhler , I should have written down what we talked about. My plan now is to see if we can change versions or config in the CI kind clusters so that the containerd version can be bumped and get rid of this problem. I'm gonna leave this PR open in case that's not possible and we do need to ignore this warning.

**Comment by alpeb** [comment]
Turns out it's not easy to bump the containerd version, and the `KinD` project is still struggling to upgrade to `1.3.4` without tests flaking: kubernetes-sigs/kind#1511

I'll be upgrading KinD in a separate PR though, to bump containerd from 1.3.2 to 1.3.3, but it appears that won't solve this flakiness. We can watch it for a while and see how it behaves before ignoring this warning.

**Comment by alpeb** [comment]
Despite the KinD upgrade we're still experiencing this error, which is causing containers to restart. So better to keep this error visible to know the cause of the restarts, and for now the only course of action is to retrigger the CI run.

**Pull request closed without merging**
