### PR TITLE
prevent duplicate prometheus args

### PR DESCRIPTION
**Pull request by n-oden**
# prevent duplicate prometheus args in linkerd-viz/prometheus

# Problem

If a user specifies a `log.level` flag for linkerd-prometheus in `prometheus.args`, the template for linkerd-prometheus will generate a prometheus command where `--log.level` is specified twice (the first being directly interpolated from `prometheus.logLevel` in the template), and prometheus will crash-loop because its flags parser does not allow duplicate flags that are not arrays.

# Solution

Only fill in the `--log.level` flag from `.Values.prometheus.logLevel` if the `log.level` key is _not_ present in `.Values.prometheus.args`

# Validation

Added a test case.

Signed-off-by: Nathan J. Mehl <n@oden.io>

### CODE REVIEW

**Comment by n-oden** [comment]
This is admittedly a corner case that view few people are likely to encounter...

...but guess who encountered it in the process of upgrading to the latest edge release in his testing environment? :)

**Comment by n-oden** [comment]
(BTW while I am pleased with myself for figuring out a valid unit test for this, I think it may be a little over the top to further slow down what is already a staggeringly lengthy PR build/test cycle in order to test this one tiny bit of templating logic, so I'm fine removing the test if you'd prefer.)

**Comment by n-oden** [comment]
(I am reaaaasonably certain that the test failure is not due to this PR.)

**Comment by kleimkuhler** [comment]
@n-oden Is the base for this the most recent `main`? It may be worth making sure you have pulled the most recent `main` and merging it in to this branch, and then pushing again.

An issue like this should have been fixed rather recently, so I just want to make sure this branch has that fix.

**Comment by n-oden** [comment]
rebased on current main/HEAD; we'll see what we see

**Comment by n-oden** [comment]
@kleimkuhler the integration test is still failing the "linkerd check jaeger" step and I am definitely rebased off of main/HEAD 🤷

**Comment by n-oden** [comment]
aha, re-rebasing fixed it.  good to go, I think?

**Comment by kleimkuhler** [comment]
@n-oden Yes sorry about that. We have disabled that test for now while we figure out why it's failing.

**Review by kleimkuhler — APPROVED** [review]
Thanks looks good!

**Review by alpeb — APPROVED** [review]
LGTM, thanks @n-oden ! :+1:

**Pull request merged**
