### PR TITLE
Add new extensions page

### LINKED ISSUE #6568: Show a list of all available extensions on the dashboard
After [Linkerd 2.10](https://linkerd.io/2021/03/01/linkerd-2.10-and-extensions/), some features are now available as part of extensions that previously where part of Linkerd's core control plane.  From the Linkerd dashboard's perspective, there isn't a clear way to know what extensions are available for a user to install in their cluster. 

It would be great to add a new page to the dashboard that will show all available extensions that can be installed in a cluster. This feature is separate from https://github.com/linkerd/linkerd2/issues/5899, where we want to show extensions that are already install in a cluster. This new page should be accessible via the navigation section of the dashboard and should function similar to the "Community" nav link.

Showing a list of installable extensions on the dashboard requires that we source that information externally. We could add a list of extensions within the dashboard source code, however, this would mean that the list would only be updated at every edge or stable release. To avoid this issue, we could probably serve a JSON file on a static site generator. It should also be easy to update this list of installable extensions. One possible good candidate to host and update this JSON file is in the www.github.com/linkerd/website repo. 

In order to display a list of these extensions, we'd need the following information about each one:
- extension name
- a screenshot of the extension in the dashboard
- a brief description
- URL to documentation

Currently, here is a list of all known linkerd extensions:
- Jaeger
- Multicluster
- Viz
- SMI
- Linkerd Buoyant
- Tapshark

### Tasks
- [x] Serve simple JSON file with list of available extensions [linkerd/website#1140]
- [ ] Add new extensions page to dashboard [#6600]

### PR DESCRIPTION
**Pull request by dadjeibaah**
This change adds a new "Extensions" page to the Linkerd dashboard. This
page lists all known built-in and third party extensions that can be
installed in a cluster.

Fixes #6568 

Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

image

### CODE REVIEW

**Comment by mateiidavid** [comment]
Looks and works great!

image

I did notice though there's a bit of a difference when changing screen sizes. On a smaller screen (such as my 13" laptop), the padding to the right of the list is added but there's a horizontal scrollbar. Is it possible to automatically resize this when switching to a smaller screen? Is that something that we want to do? For comparison, this is how it looks on my laptop screen (the first screenshot was on a bigger monitor):

image
image

**Comment by dadjeibaah** [comment]
@mateiidavid, that's a good catch. I think there should be a way to make this more responsive. I'll add that in the next commit.

**Review by adleong — APPROVED** [review]
cool!

**Review by kleimkuhler — APPROVED** [review]
Awesome!

**Pull request merged**
