### PR TITLE
make public-api use the right destination address

### PR DESCRIPTION
**Pull request by Pothulapati**
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>

PR https://github.com/linkerd/linkerd2/pull/3407 moved `destination` into a separate component. The `public-api` component was not using the latest address thus breaking `linkerd endpoints ` which interacts with the `public-api`.

Passing the address explicitely, fixes the issue!

@alpeb

### CODE REVIEW

**Comment by grampelberg** [comment]
Is there a test we can add to make sure this doesn't happen again in the future?

**Comment by alpeb** [comment]
@grampelberg we need at least one minimal integration test for `linkerd endpoints`.
`linkerd edges` is also currently lacking an integration test.

**Comment by grampelberg** [comment]
@alpeb mind creating issues for both (if they don't exist) and marking as p0 in 2.7?

**Comment by alpeb** [comment]
Done: #3477 and #3478

**Pull request merged**
