### PR TITLE
Rabbitmq client container multiarch support

### LINKED ISSUE #5926: RabbitMQ integration tests fail when running in arm64 env
It looks like we can't run the RabbitMQ integration tests in an arm64 environment.
We might need to update the `rabbit-client` image to one that has an arm64 build.
```
Run bin/tests --name deep --images skip --skip-cluster-create "$CMD"
Checking the linkerd binary...[ok]
Checking if there is a Kubernetes cluster available...[ok]
Checking if Linkerd resources exist on cluster...[ok]
Test script: [install_test.go] Params: []
ok  	command-line-arguments	177.041s
Test script: [edges] Params: []
ok  	github.com/linkerd/linkerd2/test/integration/edges	34.882s
Test script: [egress] Params: []
ok  	github.com/linkerd/linkerd2/test/integration/egress	14.349s
Test script: [endpoints] Params: []
ok  	github.com/linkerd/linkerd2/test/integration/endpoints	3.254s
Test script: [externalissuer] Params: []
ok  	github.com/linkerd/linkerd2/test/integration/externalissuer	0.080s
Test script: [externalresources] Params: []
Error: TestRabbitMQDeploy - CheckPods timed-out %s
Error: TestRabbitMQDeploy - CheckDeployment  timed-out
Error: TestRabbitMQDeploy - 'kubectl logs' command timed-out (50s)
--- FAIL: TestRabbitMQDeploy (494.04s)
    rabbitmq_test.go:61: Container [rabbitmq-client] in pod [rabbitmq-client-78d8cf5d68-bjhpm] in namespace [linkerd-rabbitmq-test] is not running
    rabbitmq_test.go:65: Error validating deployment [rabbitmq]: 
        Expected deployment [rabbitmq-client] in namespace [linkerd-rabbitmq-test] to have [1] replicas, but found [0]
    rabbitmq_test.go:82: received unexpected output
        Expected:
        [OK] Create message queue MQTestQueue
        [OK] Published message. Message count: 1
        [OK] Consumed message. Message count: 0
        
        Actual:
        standard_init_linux.go:211: exec user process caused "exec format error"
        
FAIL
FAIL	github.com/linkerd/linkerd2/test/integration/externalresources	494.130s
FAIL
```

It looks like the current rabbitmq client docker image does not have an arm64 build manifest
```
docker manifest inspect ghcr.io/barkardk/rabbitmq-client:1.0.0
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 2423,
                "digest": "sha256:d86ff766104565b0e8841eca13d3d27e3d9d3d3bc0f2787fa1c18345005caa2c"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 2811657,
                        "digest": "sha256:ba3557a56b150f9b813f9d02274d62914fd8fce120dd374d9ee17b87cf1d277d"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 1578487,
                        "digest": "sha256:6f03b9ee17a46cc071a2e3b524924d858f9172252a682c5628a4d8397c168f94"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 161,
                        "digest": "sha256:94b78c68c1fc4ba777a2550e4dfb5ce6698bb5ab559407e44cdf8d4ca79f8768"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 1578513,
                        "digest": "sha256:5beefafc3c8aeac8b74e35d86ac12beeaeb2fc3454f8a4c7f84f03cad96c8671"
                }
        ]
}
```
//cc @barkardk

### PR DESCRIPTION
**Pull request by barkardk**
Signed-off-by: Kristin Barkardottir <kristin.barkardottir@netapp.com>
Subject
New client release with docker multiarch build 
```
 "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:26c1631b02b6194c1a5b069d68a9277926dd9cadf70d5f8206849973fd9c9f43",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:819fe63bcdcbe3a0b8353e3bce55d785b208e0d9ae3f0e2453f649f4facdbdb6",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}

```

Fixes #5926

### CODE REVIEW

**Comment by barkardk** [comment]
@dadjeibaah  I have the multiarch container ready  see [barkardk/v1.1.0](https://github.com/barkardk/integration/releases/tag/v1.1.0) for source

**Comment by Pothulapati** [comment]
Can you also re-enable it as part of this  PR? Basically just [undoing changes from 5925](https://github.com/linkerd/linkerd2/pull/5925/files)

**Comment by barkardk** [comment]
@Pothulapati  absolutely

**Comment by alpeb** [comment]
@barkardk when running the test against an ARM server, the `rabbitmq-client` pod is is failing with the following message:
```
$ kubectl -n linkerd-rabbitmq-test logs rabbitmq-client-57b8fd4785-2m7hr rabbitmq-client
./mq_test: line 1: syntax error: unexpected end of file (expecting ")")
```

**Comment by barkardk** [comment]
@alpeb  Ill fix this

**Comment by barkardk** [comment]
@alpeb I have tested on darwin and an arm/v7 (32bit) raspberry pi. I am going to verify on an arm64 also 
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:6fb43563308ee5f53536684061318846f4e26c4675cd93f89f98f49e606e64e6",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:006e9f2a925c19961dc6c15fdb074f5d6c087bbab2e08f2a4fe8b60e054400dc",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:11c6a914c5626454469f5dbcd7b1958616094935b16e291057ac7d72a31a4ace",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:20c7a327aac4afe03c089942c5e2f21fbc8d01c665736997e44deb7b8cec1fb1",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v6"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:11c6a914c5626454469f5dbcd7b1958616094935b16e291057ac7d72a31a4ace",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:92197d82d3fd8398f64dfe4e7b610445b8297fe1e224d5a226bb95ebc6eda316",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}

```

**Review by alpeb — APPROVED** [review]
Thanks @barkardk , that did the trick in our test ARM cluster :+1: 
```console
$ KUBECONFIG=~/k8s/equinix/kubeconfig-arm bin/tests --name external-resources --skip-cluster-create ~/.linkerd2/bin/linkerd-edge-21.3.3
Checking the linkerd binary...[ok]
Checking if there is a Kubernetes cluster available...[ok]
Checking if Linkerd resources exist on cluster...[ok]
Test script: [install_test.go] Params: []
ok      command-line-arguments  498.440s
Test script: [rabbitmq_test.go] Params: []
ok      command-line-arguments  110.645s
```

**Review by adleong — APPROVED** [review]

**Pull request merged**
