### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by mavrick**
adding mattepaint.com to ADOPTERS.md

Signed-off-by: Daniel Lang <daniel@mattepaint.com>

### CODE REVIEW

**Comment by grampelberg** [comment]
@mavrick would you mind taking care of [DCO](https://github.com/linkerd/linkerd2/pull/4589/checks?check_run_id=763916819)? We can get this merged after that!

**Comment by grampelberg** [comment]
@mavrick we'd love to get this merged, just need DCO!

**Comment by mavrick** [comment]
apologies, i didn't see the notifcation

**Comment by wmorgan** [comment]
@grampelberg we can skip the DCO on this. The copyright risk for this change is close to zero.

**Pull request merged**
