### PR TITLE
spSharedInformers, tsSharedInformers may be nil, calling the metho will cause panic

### PR DESCRIPTION
**Pull request by wangchenglong01**
Subject
variable `spSharedInformers`, `tsSharedInformers` may be nil, calling the method will cause panic

Problem
The line 175 code are
```
var spSharedInformers sp.SharedInformerFactory
if spClient != nil {
	spSharedInformers = sp.NewSharedInformerFactory(spClient, 10*time.Minute)
}
```
if spclient is nil, then the variable spSharedInformers will nil. So calling the method will cause panic. And the tsSharedInformers is the same.

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @wangchenglong01 ,
Here you're exchanging not showing a panic for another problem down the line for not having set `api.sp` or  `api.ts`. I think a better approach would be to check at the beginning of the function that the contract is fulfilled, i.e. If the SP (or TS) resource was supplied in `resources`, then `spClient` (or `tsClient`) was supplied as well, or else do panic with a more explicit message.

**Comment by wangchenglong01** [comment]
> Thanks @wangchenglong01 ,
> Here you're exchanging not showing a panic for another problem down the line for not having set `api.sp` or `api.ts`. I think a better approach would be to check at the beginning of the function that the contract is fulfilled, i.e. If the SP (or TS) resource was supplied in `resources`, then `spClient` (or `tsClient`) was supplied as well, or else do panic with a more explicit message.

You are right. I have seen that the SP (or TS) function  has judged nil logic and throw 'panic("TS informer not configured")'.
But what I want to say is other place. The whole code snippets is follow:

```go
// line:175 controller/k8s/api.go
var spSharedInformers sp.SharedInformerFactory
if spClient != nil {
	spSharedInformers = sp.NewSharedInformerFactory(spClient, 10*time.Minute)
}

...

// line:231 controller/k8s/api.go
case SP:
	api.sp = spSharedInformers.Linkerd().V1alpha2().ServiceProfiles()
	api.syncChecks = append(api.syncChecks, api.sp.Informer().HasSynced)

```
If spClient is nil, then the variable spSharedInformers will nil. So calling the method `spSharedInformers.Linkerd()` will cause panic 'runtime error: invalid memory address or nil pointer dereference'.

**Comment by adleong** [comment]
Ah, I think I see what you mean, @wangchenglong01.  If `SP` is passed in as a resource type but `spClient` is passed in as nil, we can get the panic on line 231.  Since it is a misuse to call`NewAPI` with that combination of parameters, I think we should still panic, but perhaps with a better error message.

For example, adding a check on line 231 which is something like:
```
case SP:
    if spSharedInformers == nil {
        panic("helpful error message here")
    }
````
```

**Comment by wangchenglong01** [comment]
> Ah, I think I see what you mean, @wangchenglong01. If `SP` is passed in as a resource type but `spClient` is passed in as nil, we can get the panic on line 231. Since it is a misuse to call`NewAPI` with that combination of parameters, I think we should still panic, but perhaps with a better error message.
> 
> For example, adding a check on line 231 which is something like:
> 
> ```
> case SP:
>     if spSharedInformers == nil {
>         panic("helpful error message here")
>     }
> ```

Thanks @adleong. Maybe your opinion is better to still panic with a better error message. So I have changed them.

**Review by alpeb — APPROVED** [review]
Thanks @wangchenglong01 , this looks good to me :+1:

**Review by adleong — APPROVED** [review]
Thank you, @wangchenglong01

**Review by kleimkuhler — APPROVED** [review]
Thanks @wangchenglong01!

**Pull request merged**
