### PR TITLE
add prometheusUrl to control plane chart

### PR DESCRIPTION
**Pull request by junnplus**
This PR adds `prometheusUrl` values to control plane chart.

Fixes: https://github.com/linkerd/linkerd2/issues/9357

Signed-off-by: Ye Sijun <junnplus@gmail.com>

### CODE REVIEW

**Comment by adleong** [comment]
Thanks, @junnplus!

This looks correct but I hesitate because I wonder if it will be misleading for users to see a `prometheusUrl` in the Values for the core control plane, since prometheus is not used by the core control plane anywhere except in the heartbeat job (and even there, it's completely optional).  I'm not sure if the value add justifies the potential confusion.

**Comment by junnplus** [comment]
@adleong any suggestions? or we remove it from heartbeat job?

**Comment by adleong** [comment]
@junnplus I'm wondering if we even need to do this at all.  It may be okay to leave things as they are and have the heartbeat job continue to omit prometheus when the prometheus url is a non-default value.

**Comment by junnplus** [comment]
>  It may be okay to leave things as they are and have the heartbeat job continue to omit prometheus when the prometheus url is a non-default value.

So what does the heartbeat job need prometheus to do?

**Pull request closed without merging**
