### PR TITLE
X linkerd retry branch

### PR DESCRIPTION
**Pull request by gane5hvarma**
Subject: x-linkerd-retry
Problem: Retry policy is manually written in yaml file and patched it into the service profile
Solution: isRetryable is directly generated by adding x-linkerd-retry (boolean) property in the method the path using vendor extension in open-api spec
Fixes: #2073

### CODE REVIEW

**Comment by gane5hvarma** [comment]
@grampelberg

**Comment by ihcsim** [comment]
Still relevant.

**Comment by adleong** [comment]
@gane5hvarma are you still interested in working on this?

**Comment by gane5hvarma** [comment]
Hey @adleong. Many things have happened after I made the pr in march. I have changed my machine to mac. and got busy with work.  Yes, im interested to work on this. give me two days time.I will setup linkerd locally and update the changes mentioned above. Thanks!

**Comment by adleong** [comment]
Awesome!  Glad to hear you're still interested in this!

**Pull request closed without merging**
