### PR TITLE
Add p3r to ADOPTER.md

### PR DESCRIPTION
**Pull request by hrittikhere**
Subject
Add p3r to ADOPTER.md

DCO Sign off: Hrittik Roy <hrittikcom@gmail.com>

### CODE REVIEW

**Comment by hrittikhere** [comment]
Option 3: very simple changes
Changes that are trivial (e.g. spelling corrections, adding to ADOPTERS.md, one-word changes) do not require a DCO signoff. Maintainers should feel free to override the DCO bot for these changes.



So, I guess we can override?

**Comment by Pothulapati** [comment]
Hey @hrittikhere 

Yep, DCO is not needed, and we can approve it in the CI but the CI still fails on a markdown lint because of the addition of new line.

```
./ADOPTERS.md:66 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```
Can you fix it?

**Comment by hrittikhere** [comment]
@Pothulapati updated :)

**Review by Pothulapati — APPROVED** [review]
LGTM!

**Review by mateiidavid — APPROVED** [review]

**Pull request merged**
