### PR TITLE
Add log-format flag to control plane components

### LINKED ISSUE #5536: Support JSON log format in control plane components
JSON is much easier to collect/parse by fluentd (or any similar tools). It was nice and more flexible to have a flag for it. 

`go run main.go destination`
```
INFO[2021-01-14T05:40:30+03:00] running version dev-undefined                
WARN[2021-01-14T05:40:30+03:00]  expected trust domain through args (falling back to cluster.local) 
WARN[2021-01-14T05:40:30+03:00] expected cluster domain through args (falling back to cluster.local) 
INFO[2021-01-14T05:40:31+03:00] waiting for caches to sync                   
INFO[2021-01-14T05:40:31+03:00] caches synced                                
INFO[2021-01-14T05:40:31+03:00] starting admin server on :9996               
INFO[2021-01-14T05:40:31+03:00] starting gRPC server on :8086
```

`go run main.go destination -log-format json`
```
{"level":"info","msg":"running version dev-undefined","time":"2021-01-14T05:39:09+03:00"}
{"level":"warning","msg":" expected trust domain through args (falling back to cluster.local)","time":"2021-01-14T05:39:09+03:00"}
{"level":"warning","msg":"expected cluster domain through args (falling back to cluster.local)","time":"2021-01-14T05:39:09+03:00"}
{"level":"info","msg":"waiting for caches to sync","time":"2021-01-14T05:39:09+03:00"}
{"level":"info","msg":"caches synced","time":"2021-01-14T05:39:10+03:00"}
{"level":"info","msg":"starting admin server on :9996","time":"2021-01-14T05:39:10+03:00"}
{"level":"info","msg":"starting gRPC server on :8086","time":"2021-01-14T05:39:10+03:00"}
```

### PR DESCRIPTION
**Pull request by mo4islona**
Fixes #5536

Signed-off-by: Eugene Formanenko <mo4islona@gmail.com>

### CODE REVIEW

**Review by adleong — APPROVED** [review]
This is awesome!  Thanks, @mo4islona!

**Review by kleimkuhler — APPROVED** [review]
This is awesome. Thanks @mo4islona!

**Comment by mo4islona** [comment]
@adleong @kleimkuhler 

Hi!


Helm chart doesnt have this new `controllerLogFormat` variable. 
```bash
helm search repo linkerd
NAME                              	CHART VERSION	APP VERSION 	DESCRIPTION
linkerd/linkerd2                  	2.9.4        	stable-2.9.4	Linkerd gives you observability, reliability, a...
linkerd/linkerd2-cni              	2.9.4        	stable-2.9.4	A helm chart containing the resources needed by...
linkerd/linkerd2-multicluster     	2.9.4        	stable-2.9.4	A helm chart containing the resources to suppor...
linkerd/linkerd2-multicluster-link	2.9.4        	stable-2.9.4	A helm chart containing the resources to enable...


helm show values linkerd/linkerd2 | grep controllerLogFormat
# empty line
  ```    
      
I thought it will be updated automatically but not. Could you update it please?

**Comment by alpeb** [comment]
@mo4islona Sorry about that. It will reappear again in 2.10 coming out later this week. It's already available in the edges releases:
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml

**Comment by mo4islona** [comment]
Thx!

**Pull request merged**
