### PR TITLE
Condition is always 'false' because 'err' is always 'nil'

### PR DESCRIPTION
**Pull request by wangchenglong01**
Subject
Condition is always 'false' because 'err' is always 'nil'

Problem
Condition is always 'false' because 'err' is always 'nil', remove the code.

### CODE REVIEW

**Review by mateiidavid — APPROVED** [review]
Hey @wangchenglong01 thanks for the PR!

It does seem to always be false. It looks like it is a duplicate of the error handling line from [L224](https://github.com/linkerd/linkerd2/blob/bded2fae142547ed5111b681d77aca3adbaf8c9c/controller/api/destination/server.go#L224) onwards.

https://github.com/linkerd/linkerd2/blob/bded2fae142547ed5111b681d77aca3adbaf8c9c/controller/api/destination/server.go#L224

We don't seem to be returning an error anywhere else in the enclosing if block scope before this line -- unless I'm missing something obvious. LGTM 👍🏻

**Review by dadjeibaah — APPROVED** [review]
📦 :ship

**Review by kleimkuhler — APPROVED** [review]
Thanks @wangchenglong01!

**Comment by kleimkuhler** [comment]
@wangchenglong01 You'll probably want to merge in the latest `main` if you have not already to pick up some CI fixes. Your changes shouldn't have anything to do with the current failures.

**Comment by wangchenglong01** [comment]
> @wangchenglong01 You'll probably want to merge in the latest `main` if you have not already to pick up some CI fixes. Your changes shouldn't have anything to do with the current failures.

@kleimkuhler I have fixed it.

**Pull request merged**
