### PR TITLE
Left-align the routes column and sort by route name

### PR DESCRIPTION
**Pull request by adleong**
```
ROUTE                  SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
/authors               100.00%   0.5rps          16ms          27ms          29ms    0%
/authors/{id}          100.00%   0.5rps          24ms          29ms          30ms    0%
/authors/{id}/delete   100.00%   0.5rps          43ms          90ms          98ms    0%
/books                  50.42%   2.0rps          28ms          57ms          91ms    0%
/books/{id}            100.00%   1.0rps          24ms          85ms          97ms    0%
/books/{id}/delete     100.00%   0.6rps          16ms          78ms          96ms    0%
/books/{id}/edit        52.31%   1.1rps          54ms         135ms         187ms    0%
[UNKNOWN]              100.00%   0.5rps          40ms          93ms          99ms    0%
```

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Comment by wmorgan** [comment]
Nitpick: Does the `RPS` heading make sense for slower services? Might make more sense to call that volume/throughput, if the unit is in the cell text and can be changed.

**Comment by olix0r** [comment]
@wmorgan i don't think that unit can actually change, though that seems like a pretty nice feature. I think it's there because all of other columns provide units. I think it would be fine to change the label to `VOLUME` though.

**Comment by adleong** [comment]
@wmorgan I think there's definitely room to improve the RPS column, would you mind filing an issue?

**Comment by wmorgan** [comment]
Filed #1884 for units

**Pull request merged**
