### PR TITLE
Flaky tests: allow up to one pod restart in integration tests

### PR DESCRIPTION
**Pull request by alpeb**
The restart count test has been failing sporadically due to cluster
flakiness like what's reported in #4357.

Since we run `go test` with `--failfast`, when something fails in
`test/install_test-go` we don't get to the point where `TestEvents()` is
run so we never know the reason of the pod restart (depending on whether
the flakiness continues, I might do something for `TestEvents()` to run
regardless)

### CODE REVIEW

**Comment by adleong** [comment]
I'm not sure how I feel about this because it really risks hiding true errors.  Do we have a good understanding of why pods are restarting?

**Comment by alpeb** [comment]
In my tests, I could reproduce the restarting after many runs and in that case the culprit was what's pointed out in #4372.
But you're right, the cause can be something else that can be a legit failure caused by linkerd. We could go with my earlier suggestion of having the events test get triggered every time after a failed test in `test/install_test.go`, so we can have a better chance of knowing the cause of the restart. We'd see then that a warning like #4372's might have caused the restart and then re-run the tests? Let me know what you think.

**Comment by kleimkuhler** [comment]
@alpeb Will this be closed in favor of #4410?

**Comment by alpeb** [comment]
> @alpeb Will this be closed in favor of #4410?

Yeah, closing now :+1:

**Pull request closed without merging**
