### PR TITLE
Set allowPrivilegeEscalation to False #9946 

### PR DESCRIPTION
**Pull request by Alcadeus0**
For Current Linked viz deployments showing non-compliant against the Azure Policy. Security Context is set to true by default, to adhere to best security practices allowPrivilegeEscalation has been set to true for the helm chart. It has been done for the control plane.

Fixes: #9946

### CODE REVIEW

**Comment by mateiidavid** [comment]
We probably don't want to set this on the control plane. The issue (#9946) refers to `linkerd-viz`. viz has its own charts. Have a look at https://github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz.

**Comment by Alcadeus0** [comment]
@mateiidavid but I did make the edits there though, I was discussing it and was told that the changes are only to be done in the template files inside linkerd-viz. Or am I confusing something?

**Comment by mateiidavid** [comment]
@Alcadeus0 if you look at some of the files you've checked in, you'll notice the path is `linkerd-control-plane`.  https://github.com/linkerd/linkerd2/blob/5a8e57441dcf265b889341f2b7a5a612f0cf8aa9/charts/linkerd-control-plane/templates/destination.yaml.

The templates you should edit are in the viz charts. Perhaps you've accidentally checked in the wrong files? 😄

**Comment by Alcadeus0** [comment]
@mateiidavid Thanks for pointing it out, I realized the mistake ;-; 
WIll fix the right files this time :p

**Review by mateiidavid — COMMENTED** [review]
@Alcadeus0 seems like there is something wrong with the merge commit here. You've added commits in this PR that already exist in the main branch. This will make reviewing really difficult.

I'd suggest you either re-create the PR on a new branch (that is up-to-date with main), or you try to do a git reset.

```
$ git checkout origin SetPrivilegedEscalation
$ git reset --soft HEAD^2
# add in only the viz templates
# git commit
```

If the soft reset doesn't work, you can try a hard reset. `man git` and take it from there. In the future, a clean way to get up-to-date with the main branch is to simply do `git pull` into your own branch. That will create a git commit but will preserve the git history and ensure no new files are checked in.

Our preference is for contributors to usually do `git pull`. We squash on merge so commits won't show up. If you're on a fork, you might need to add a new remote to sync commits from our repo. For example, this is how I would normally set-up a git repo if I were working through a fork.

```
$ git remote -v
git@github.com/<username>/repo origin # my fork

$ git remote add upstream git@github.com/linkerd/linkerd2 # full url
# ensure I can never push to upstream
$ git remote set-url --push upstream NO_PUSH

# now you can pull in commits from upstream repo
$ git pull upstream main
```

**Comment by Alcadeus0** [comment]
@mateiidavid Thanks a lot for providing the feedback and guidelines on handling the workflow.
Initially i add tried squashing the commits down as i made over 15, but that went south quick so instead I planned to do a hard reset and then push the changes. The main issue was probably me somehow adding the commits from the main branch.

I've decided to instead open up a new pr with the changes, I plan to create a new fork and set it up with the commands you've listed above as it would make the set up much easier.

**Pull request closed without merging**
