### PR TITLE
Add support for resources on linkerd-cni containers

### LINKED ISSUE #9843: Update linkerd-cni Helm chart to support specifying resources on the pods for the cni plugin
### What problem are you trying to solve?

In environments that run software which ensures all pods can be scheduled based on their resource requests and spins up additional nodes when capacity decreases, having a daemonset like the cni-plugin that doesn't allow users to specify the resource requests creates issues with proper scoping and monitoring for scheduling purposes. There can be edge cases where the workload pods can't fit on the available nodes due to the space already taken by the cni-plugin but not easily accounted for.

### How should the problem be solved?

Allow users to specify resource requests for the cni-plugin resources

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

_No response_

### PR DESCRIPTION
**Pull request by jcogilvie**
When determining the sum total of resource requests for the purpose of dynamically provisioning capacity, pods should participate by specifying resource requests.

This change imports the existing resource template (shared by all other `linkerd` charts) into the pod spec of the cni daemonset pods.

Validated by running `helm template` and ensuring that the resulting chart looks as expected with resources under the daemonset container.

Fixes #9843

Signed-off-by: Jonathan Ogilvie <jonathan.ogilvie@terminus.com>

### CODE REVIEW

**Comment by jcogilvie** [comment]
A note about the default resource requests/limits:

* all pods in my running clusters seem to use <64Mi of memory, although I can't guarantee that this is universally true
* all pods in my cluster seem to burst to a very tiny amount of cpu (<1mcore) at startup, and then fall to zero; hence setting the request to `1m` with a burstable limit

**Review by kleimkuhler — COMMENTED** [review]
Thanks for working on this change @jcogilvie!

It seems like the best defaults for resources would be not specifying them. You'll notice that while we support adding them to the Linkerd install and its extensions, we don't have defaults for those installations because we try not to make any assumptions about what is available.

If users do need to set resources though, they should be able to now with the rest of this change.

**Review by kleimkuhler — APPROVED** [review]
Thanks this looks great! I tested with `helm template linkerd-cni charts/linkerd2-cni/ --set resources.cpu.limit="250Mi"` and the output looks good.

**Comment by mateiidavid** [comment]
@jcogilvie thanks for the PR! Like Kevin mentioned this looks good. Can you please:

1. Pull in the latest main: `git pull <remote>/main` when checked out on the branch (some checks are failing, trying with a more recent version of the particular action triggering the failure might help out)
2. Run `bin/helm-docs` in the root of the repo

Once all the checks pass this is good to go :)

**Comment by alpeb** [comment]
I think this will require another merge from `main`,  as soon as #10005 gets merged.

**Review by mateiidavid — APPROVED** [review]

**Comment by mateiidavid** [comment]
Thanks for the work @jcogilvie! Tested with `helm template` and the output looks great.

**Pull request merged**
