### PR TITLE
Add DNS rebinding attack protection

### PR DESCRIPTION
**Pull request by alpeb**
## Changes to `linkerd dashboard`

Creates a new web server listening on http://$options.host:$options.port
(host and port can be set as CLI params) that forwards the connection to
the old k8s port-forwarder listening on http://$options.host:$targetPort
(targetPort is now fixed). Any request received with the Host header
different than $options.host:$options.port will be rejected, thus
preventing DNS rebinding attacks.
This local web server will also rewrite the Host header to something
like "linkerd-web.linkerd.svc.cluster.local:8084" that is now enforced
by the linkerd-web service.

Note that the other alternative mentioned in #3083 to have k8s'
port-forwarding do the header rewrites was explored, but the
port-forwarding code doesn't expose any APIs that we could leverage.

## Changes to `linkerd install`

- Attack prevention is enabled by default. A new option (visible in
`linkerd (install|upgrade) [control-plane]`)
`--disable-dns-rebinding-protection` (with its corresponding Helm value
`DisableDNSRebindingProtection`) where added.

## Changes to the `linkerd-web` service

- The service will reject any request not having a Host header like
`linkerd-web.linkerd.svc.cluster.local:8084`

## How to verify the attach protection works

- Run `linkerd dashboard --port 3000`
- Go to http://rebind.it:8080/manager.html and change the target port to
3000
- Click on “Start Attack” and wait for a minute.
- The response from the dashboard will be returned, showing an 'Invalid
Host header' message returned by the dashboard. If the attack would have
succeeded then the dashboard's html would be shown instead.

## Grafana

I didn't had to add the `enforce_domain` config in Grafana because when
using `linkerd dashboard` the requests for Grafana are proxied through
the `linkerd-web` service which is now protected. This means that, unlike
the dashboard, exposing Grafana directly doesn't require headers rewriting.
But while trying to expose Grafana I noticed we need to modify its
`root_url` config (even before this PR). Something to add to the docs.

## Additional Notes

- `linkerd dashboard` remains backwards compatible with older control
planes whose `linkerd-web` doesn't enforce the Host header.
- Why would one want to disable this protection? If you're exposing the
dashboard directly you won't be able to easily set up the Host header
accordingly. Also when exposing through Ingress (gotta update those docs
to explain the header-rewrites that would be needed).

Ref #3083

### CODE REVIEW

**Comment by adleong** [comment]
Some open questions:

* Do we need to add this hostname validation to any other services?
* Does linkerd-web have any callers other than `linkerd dashboard` and potentially an ingress that the user has set up?
* Is it a problem that callers must use the fully qualified domain name?
* If we add `localhost` et al. to the linkerd-web hostname whitelist, do we still need the local web server?
  * Making the whitelist configurable works around the ingress issue nicely because users can simply add whatever explicit hostnames they need to the whitelist

**Comment by adleong** [comment]
Somewhat relevant prior art: `kubectl proxy` supports this flag:

```
--accept-hosts='^localhost$,^127\.0\.0\.1$,^\[::1\]$': Regular expression for hosts that the proxy should accept.
```

linkerd-web could support something similar.

**Comment by alpeb** [comment]
Thank you all for your feedback. Here are some answers. I think there's room for more discussion around this solution.

> My preference would be to remove --disable-dns-rebinding-protection and only allow disabling this through a helm install.

:+1:

> Not all ingress controllers allow host header rewriting, could we use l5d-dst-override as well?

Makes sense. So this means having the proxy do the Host header overriding, right?

> Do we need to add this hostname validation to any other services?

Like discussed offline, that would be good. Although It'd forbid accessing the other services directly through kubectl port-forwarding or proxy; the user could set up port-forwarding but have its http client rewrite the Host header just like we're doing here. But I don't know if there's a case for accessing those services directly.

> Does linkerd-web have any callers other than linkerd dashboard and potentially an ingress that the user has set up?

I can only think of tap when it inspects linkerd-web, but it's sending the proper Host header. Ingress would need to rewrite that header. The `l5d-dst-override` idea above should do the trick.

> Is it a problem that callers must use the fully qualified domain name?

Only if their http clients don't support header rewriting.

> If we add localhost et al. to the linkerd-web hostname whitelist, do we still need the local web server?
Making the whitelist configurable works around the ingress issue nicely because users can simply add whatever explicit hostnames they need to the whitelist

> Somewhat relevant prior art: kubectl proxy supports this flag:
--accept-hosts='^localhost$,^127\.0\.0\.1$,^\[::1\]$': Regular expression for hosts that the proxy should accept.
linkerd-web could support something similar.

We could. And if the user relies on something like `linkerd dashboard --address=1.2.3.4` (see #3100) then they'd have to add that address into that whitelist as well.

That said, I got convinced about the "properness" of enforcing a Host header that matches the pod identity. I think that warrants more discussion.

**Comment by grampelberg** [comment]
> Makes sense. So this means having the proxy do the Host header overriding, right?

I think it means that we check both headers in `linkerd-web`. Looking at the XHR spec, you can add your own headers though, so it would only be slightly better than we have now for security.

Let's make sure there is a very clear error that comes back when the header is wrong, directs them to documentation and explains what is going on.

**Comment by alpeb** [comment]
After some discussion offline, the point was raised that we should focus on just linkerd-web and the broader issue of tying this with identity can be tackled more generally later on in a separate issue. So the whitelist approach should be enough, without introducing the local webserver. I'll open a new PR that replaces this one.

I still have one question though. In order to still support `linkerd dashboard --address`, that whitelist needs to be configurable during install/upgrade. Would it be fine to surface this at both the `linkerd install|upgrade` and Helm levels?

**Comment by grampelberg** [comment]
>  Would it be fine to surface this at both the linkerd install|upgrade and Helm levels?

WDYT about hard coding it for now? Folks who really care can use kustomize and I'm not convinced we need the added complexity yet.

**Comment by alpeb** [comment]
Superseded by #3644

**Pull request closed without merging**
