### PR TITLE
Add a devcontainer configuration

### PR DESCRIPTION
**Pull request by olix0r**
VS Code [devcontainers][dc] provide a way to define a reproducible,
customizable developer environment. This should lower the barrier to
entry for contributors and reduce the maintenance burden for existing
developers, as a docker daemon is now basically all that's needed to get
up and running.

This change adds a devcontainer for the Linkerd2 project. Its container
starts in the host's network so that it can easily access k3d clusters
running on the host's docker daemon.

This change also bumps the rust toolchain version to v1.56.1, as some
tools cannot be installed with v1.56.0.

[dc]: https://code.visualstudio.com/docs/remote/containers

Signed-off-by: Oliver Gould <ver@buoyant.io>

### CODE REVIEW

**Review by adleong — APPROVED** [review]
This is sweet.

Worth noting that simply opening the workspace in a devcontainer didn't work for me because my docker daemon runs on a remote host and my local filesystem paths and remote filesystem paths don't line up.  However, doing "clone a PR in a devcontainer" worked like a charm and I imagine that "close a repo in a devcontainer" will work as well once this is merged.

One small thing I noticed is that the markdownlint script requires npm, so we may want to add that to the container as well:

```console
$ bin/markdownlint
Error: npm required to install markdownlint command
```

**Comment by olix0r** [comment]
a little cray that npm pulls in ~300MB just to run that script, but that's for another day. i'll try to get markdownlint-cli preinstalled in the image.

**Comment by olix0r** [comment]
> Worth noting that simply opening the workspace in a devcontainer didn't work for me because my docker daemon runs on a remote host and my local filesystem paths and remote filesystem paths don't line up.

You'll probably have better luck using VSCode's `Remote - SSH` to open a session on the remote host (where you'll need to check out the repo) and then opening in the container should work more smoothly. Some additional context at https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host

**Review by kleimkuhler — APPROVED** [review]
👍

**Pull request merged**
