### PR TITLE
Document workaround for external Grafana URL

### PR DESCRIPTION
**Pull request by MaT1g3R**
Fixes https://github.com/linkerd/linkerd2/issues/4848

Signed-off-by: Peijun Ma <peijun.ma@protonmail.com>

### CODE REVIEW

**Comment by ihcsim** [comment]
@MaT1g3R Thanks for the PR. I think the more complete fix is in https://github.com/linkerd/linkerd2/pull/4857. My suggestion is that we include this doc change in that PR.

@Pothulapati WDYT?

**Comment by Pothulapati** [comment]
@MaT1g3R #4857 has been closed because it does not actually makes sense and adds a lot of extra maintaince burden. This looks good to be merged. Can you re-base to make the tests pass?

**Comment by MaT1g3R** [comment]
@Pothulapati For sure

**Comment by Pothulapati** [comment]
@alpeb Hmm, That makes sense, especially because as the user can't set the URl of a external grafana instance directly without changing its proxy settings, this does not seem to add a lot of value. Also, considering that our min control plane RFC (which is currently in works) is definitely going to change this configuration. WDYT?

cc @ihcsim

**Comment by MaT1g3R** [comment]
I think having the ability to click the Grafana icon on the Linkerd UI and taking you to your own Grafana instance provides value, as we don't really want to run 2 separate Grafana instances but still want to see the dashboards.

**Comment by ihcsim** [comment]
@MaT1g3R I am closing this PR for now. @Pothulapati has an upcoming RFC with design on the minimal control plane feature, which will affect this. Once @Pothulapati is ready to share the RFC, he can share the link with you and feel free to chime in there.

As for the original issue at https://github.com/linkerd/linkerd2/issues/4848, sounds like you resolved it by not including the `https` prefix in the URL, right?

**Pull request closed without merging**
