### PR TITLE
Add missing ignoreInboundports to CNI config

### LINKED ISSUE #6224: Tap - Unauthenticated / no_tls_from_remote
### What is the issue?

Whenever I attempt to use `linkerd viz tap [...]` no requests or responses are shown. I can see the following error in the logs for the `tap` pods everytime I run the command, `rpc error: code = Unauthenticated desc = no_tls_from_remote`.

### Logs, error output, etc

```text
time="2021-06-04T05:41:57Z" level=error msg="[172.31.242.89] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.245.98] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.240.254] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.249.51] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.249.164] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.248.75] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.247.147] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.246.72] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.241.237] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.247.253] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.243.199] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.240.198] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.247.16] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.251.248] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
time="2021-06-04T05:41:57Z" level=error msg="[172.31.242.8] encountered an error: rpc error: code = Unauthenticated desc = no_tls_from_remote"
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
‼ trust anchors are valid for at least 60 days
    Anchors expiring soon:
	* 273551836759235789366509026732282688713654895984 root.linkerd.cluster.local will expire on 2021-07-03T02:03:09Z
    see https://linkerd.io/checks/#l5d-identity-trustAnchors-not-expiring-soon for hints
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-06-06T03:22:36Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.10.1 but the latest stable version is 2.10.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.1 but the latest stable version is 2.10.2
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: AWS EKS
- Host OS: Amazon Linux (Kernel 4.14.232)
- Linkerd version: 2.10.1

### PR DESCRIPTION
**Pull request by dadjeibaah**
This change fixes an issue where tap does not work when running Linkerd
through Linkerd CNI installed via helm charts. This issue was caused by
the CNI charts config not including tap control and admin ports in the
config. This caused tap request traffic to go to the inbound side of the
porxy as opposed to its respective control port.

Fixes #6224

Signed-off-by: Dennis Adjei-Baah <dennis@buoyant.io>

### CODE REVIEW

**Review by adleong — APPROVED** [review]

**Review by Pothulapati — APPROVED** [review]
LGTM, good find! Looks like we were missing logic that was being done in the CLI install

https://github.com/linkerd/linkerd2/blob/dad/fix-missing-ignore-ports-cni/cli/cmd/install-cni-plugin.go#L163

I think you need to update the golden files for the tests to pass!

**Comment by alpeb** [comment]
I'm experiencing some oddities testing this with helm, it might be PEBCAK, will report back in a few...

**Comment by dadjeibaah** [comment]
@alpeb, weird, let me know what errors you are seeing and I'm happy to take a look.

**Comment by alpeb** [comment]
It's actually a pre-existing issue when handling single values for `ignoreInboundPorts` or `ignoreOutboundPorts`. For comparison, it works with the linkerd2 chart:
```bash
$ helm template charts/linkerd2 --set proxyInit.ignoreInboundPorts=1234 -f ~/src/k8s/helm/linkerd-overrides.yaml
# no errors
```
but with the linkerd2-cni chart:
```bash
$ helm template charts/linkerd2-cni --set ignoreInboundPorts=1234
Error: template: linkerd2-cni/templates/cni-plugin.yaml:152:49: executing "linkerd2-cni/templates/cni-plugin.yaml" at <include "partials.splitStringList" .Values.ignoreInboundPorts>: error calling include: template: linkerd2-cni/charts/partials/templates/_helpers.tpl:7:11: executing "partials.splitStringList" at <len .>: error calling len: len of type int64
```
the problem being that `1234` is taken as an int and `len` chokes on it. The `partials.splitString` could be ammended to cast to a string before doing its thing:
```tpl
{{- define "partials.splitStringList" -}}
{{- if gt (len (toString .)) 0 -}}
{{- $ports := toString . | splitList "," -}}
{{- $last := sub (len $ports) 1 -}}
{{- range $i,$port := $ports -}}
"{{$port}}"{{ternary "," "" (ne $i $last)}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by dadjeibaah** [comment]
Good find @alpeb! I'll incorporate this in the next commit.

**Review by alpeb — APPROVED** [review]
Thanks @dadjeibaah :+1:

**Pull request merged**
