### PR TITLE
Default Policy controller resources to destination resources in manifest

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Fixes https://github.com/linkerd/linkerd2/issues/12131

To test locally(you would need to set some values to `.Values.identity.issuer.tls.crtPEM` and Values.identity.issuer.tls.keyPEM`` before that), run:

1. `helm template ./charts/linkerd-control-plane --devel --set=destinationResources.cpu.request=100m`. In generated manifest for policy controller you should see:
```
        resources:
          requests:
            cpu: "100m"
```
2. `helm template ./charts/linkerd-control-plane --devel --set=policyController.resources.memory.limit=25Mi --set=destinationResources.cpu.request=100m`. In generated manifest for policy controller you should see:
```
        resources:
          limits:
            memory: "25Mi"
```

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @GrigoriyMikhalkin ! This is an interesting approach, given the go templates limitations :-)
It seems there's a problem though when not setting those resources at all:
```bash
$ helm template charts/linkerd-control-plane --devel -f ~/src/k8s/helm/linkerd-overrides.yaml
Error: template: linkerd-control-plane/templates/destination.yaml:348:12: executing "linkerd-control-plane/templates/destination.yaml" at <include "partials.default-resources" $resDict>: error calling include: template: linkerd-control-plane/charts/partials/templates/_default-resources.tpl:16:4: executing "partials.default-resources" at <include "partials.resources" .default>: error calling include: template: linkerd-control-plane/charts/partials/templates/_resources.tpl:2:25: executing "partials.resources" at <index . "ephemeral-storage">: error calling index: index of untyped nil
```

So the guard (`if $res`) that was removed from destination.yaml needs to be put into the `partials.resources` template.

**Review by adleong — COMMENTED** [review]
Another potential solution here is to remove this defaulting behavior entirely and require that users who want to set resources for the policy controller must do so directly rather than allowing the policy controller to inherit the resources config from the destination controller.  Given that this defaulting does not work today, this would not be a breaking change.

Having these configs be entirely separate is easier to understand and I'm not aware of a compelling reason why these two controllers would necessarily have the same resource profile.

**Comment by GrigoriyMikhalkin** [comment]
@alpeb Thanks for the finding! Fixed that.

**Comment by GrigoriyMikhalkin** [comment]
@adleong It seems like the idea was at the time when Policy controller was introduced(https://github.com/linkerd/linkerd2/commit/b98c86700f5a3d8b2fab74ea4c25b4b8bba25ebe) -- that users are not necessary aware of it's presence. So to mitigate the risk of resource usage spiraling out of control this defaulting(and not working ;)) behavior was introduced.

I would say, there's still a benefit using this defaulting(and now working) behavior. Since, there's a good chance that some share of users are discovering existence of Policy controller only when they're encountering some problems.

**Comment by adleong** [comment]
I agree that most users don't know and shouldn't need to know about the inner workings of the control plane.  I would say that giving the policy controller reasonable defaults for resources and having config to override those defaults if necessary is sufficient for that.  Tying these defaults to the destination controller's config doesn't seem like it has any benefits, considering this wasn't even working until now.

**Comment by GrigoriyMikhalkin** [comment]
@adleong Updated tests. Could you please approve workflow)?

**Comment by alpeb** [comment]
Thanks for the update @GrigoriyMikhalkin, but I do agree with @adleong's comment above, in that there's no reason to couple these controllers configs, and adding a separate config for the policy controller is a simpler change. Do you mind changing this accordingly?

**Comment by GrigoriyMikhalkin** [comment]
@alpeb @adleong Changed PR. Removed defaulting behavior.

I think there's still one open question -- do we want to do something with default values for Policy container resources? One low hanging fruit would be to in `values-ha` to `policyController.resources` set the same defaults that are set to `destinationResources`.

**Review by adleong — APPROVED** [review]

**Pull request merged**
