### PR TITLE
cli: Add label selector flag for `stat`

### PR DESCRIPTION
**Pull request by mayankshah1607**
First take on https://github.com/linkerd/linkerd2/issues/2734

#### Add `kubectl` like label selector for `linkerd stat`
As opposed to earlier, `linkerd stat` command now accepts a label selector via the `--selector` (or `-l` shorthand):
```bash
$ linkerd -n emojivoto stat deploy -l test.linkerd/test
```
The above command will return stats for all deployments with the label `test.linkerd/test` in the `emojivoto` namespace.

---
Follow up PRs shall be made for the following features (as a part of https://github.com/linkerd/linkerd2/issues/2734):
- Update `tap`, `top`, `routes` commands to accept resource lists much like `stat`
- Update `tap`, `top`, `routes` to accept label selectors

### CODE REVIEW

**Comment by mayankshah1607** [comment]
#### Need help :
From what has been implemented currently, it looks like `buildStatsSummaryRequests()` method returns a slice of `StatSummaryRequest` where each request has `Selector.LabelSelector` being read in correctly from the `-l` or `--selector` flag.
For eg:
```bash
$ linkerd stat deploy -n emojivoto -l test-label/test
```
returns a request object where `label_selector` correctly holds the value `test-label/test`.
However, the label is being ignored while fetching the stats from API - all deployments in the namespace `linkerd` are returned, and not just the ones with the specified label. I'm not really able to figure out whats happening at `requestStatsFromAPI` to diagnose this issue further.

**Comment by Pothulapati** [comment]
Hey, 

Hmmm, I don't think the `linkerd-controller` api server is actually using the label selectors.

If we look at the `StatSummary` method in the `linkerd-controller` api server, which calls `k8sResourceQuery` to imply a request for kubernetes resources query. This method at https://github.com/linkerd/linkerd2/blob/9b29a915d31f33914cdb94d71489d98f7e31c9a1/controller/api/public/stat_summary.go#L162 is called to retrieve the k8s resources, but I don't see the `selectors` being used anywhere in this path.

I also see that we are using the `labelSelectors` in the `ListPods` path at https://github.com/linkerd/linkerd2/blob/9b29a915d31f33914cdb94d71489d98f7e31c9a1/controller/api/public/grpc_server.go#L104, Thus making `ListPods` tests with `LabelSelectors` pass at  https://github.com/linkerd/linkerd2/blob/9b29a915d31f33914cdb94d71489d98f7e31c9a1/controller/api/public/grpc_server_test.go#L338

I think, using the same labelSelectors logic in the `ListPods` at the `getKubernetesObjectStats` function in the `StatSummary` path should fix this.

**Comment by mayankshah1607** [comment]
thanks @Pothulapati ! That fixed the problem. I've updated the controller api server to use label selectors from requests. Had to do a small amount of refactoring, but it works as expected now :smile: 
As of now, I've only updated methods relevant to `stat` to make use of label selectors, but it looks like there's a lot of other places where label selectors are being ignored.

**Comment by adleong** [comment]
This looks like a good start!

**Comment by mayankshah1607** [comment]
@Pothulapati @adleong oops, tried to rebase against master and the integration tests are failing. Any tips on how to fix this?

**Comment by mayankshah1607** [comment]
@alpeb Thank you for pointing that out! :smile: I have updated the PR to address these changes. Also added a small helper to make things easier

**Comment by mayankshah1607** [comment]
@alpeb oops, my apologies! Will keep in mind 😄 thanks for the ✅

**Pull request merged**
