### PR TITLE
CI steps for Chocolatey package

### PR DESCRIPTION
**Pull request by alpeb**
Followup to #4205

This adds:
- A new job `psscript-analyzer` into the `statics_checks.yml`
workflow for linting the Chocolatey Powershell script.
- A series of new steps into the `gh_release` job of the `release.yml`
workflow for updating the Chocolatey spec file and generating the
package. This is only triggered for stable releases.
- The `Create release` step was updated to upload the generated package,
if present.

@drholmie would you mind reviewing this? This can successfully generate the final package. I triggered it in a fork, which resulted in [this file](https://github.com/alpeb/linkerd2/releases/download/2.7.8/linkerd.2.7.1.nupkg). After downlading it into my windows vm, running `choco install linkerd -s .` returns successfully but the linkerd executable is nowhere to be found. Any ideas what could be going on?

### CODE REVIEW

**Comment by drholmie** [comment]
Thanks for the PR @alpeb ! I installed the package through the `linkerd2.7.1.nupkg`, and all seems well. Will let you know if I find anything more. The package should have installed in `C:\ProgramData\chocolatey\lib`. 
(Do note `ProgramData` is a hidden folder, and can be accessed via GUI by changing view options in a folder to allow viewing of hidden folders).

**Comment by alpeb** [comment]
@drholmie thanks for circling back :+1: 

After performing `choco install linkerd -s .` I do see `linkerd.nupkg` and `linkerd.nuspec` under `C:\ProgramData\chocolatey\lib\linkerd` but I would expect to see a linkerd executable under `C:\ProgramData\chocolatey\bin` and I don' t see any. Do you?

**Comment by drholmie** [comment]
(Apologies for taking so long to get back)
Oh! Interesting. After looking into `release.yml`, the way the chocolatey package is packed may be the cause. The executable is meant to be found here `C:\ProgramData\chocolatey\lib\linkerd\tools\linkerd.exe` (as long as no environment variable for `linkerPath` or command line argument is applied)

But after experimenting with `choco pack /bin/win/linkerd.nuspec` vs `cd /bin/win; choco pack` (in a fresh windows VM). There seems to be a difference in how `linkerd.exe` is installed (This maybe an issue with chocolatey itself, couldn't find any documentation for it but will look around more). 

To verify this, could you please modify the `release.yml` file to run `choco pack` inside the `bin/win` directory instead and send over/ use the resulting `linkerd2.7.1.nupkg`.

**Comment by alpeb** [comment]
@drholmie I pushed your suggestion to this PR, and it still doesn't work. Note that another third party has just created a Chocolatey package for "Linkerd2":
https://chocolatey.org/packages/Linkerd2#files
That one appears to be working fine. Can you take a look?

**Comment by grampelberg** [comment]
@alpeb is this ready for review?

**Comment by alpeb** [comment]
> @alpeb is this ready for review?

No, the generated package isn't working... I'll spend a few more cycles trying to figure what's going on

**Comment by alpeb** [comment]
I have pushed #4536 for a different approach that fixes all the problems found in this PR.

**Pull request closed without merging**
