### PR TITLE
Validate httproutes.gateway.networking.k8s.io

### LINKED ISSUE #11116: policy-controller validating admission webhook doesn't validate `gateway.networking.kubernetes.io` HTTPRoutes
### What is the issue?

While working on other changes to the policy controller, I noticed that the validating admission webhook validates the `policy.linkerd.io` version of the HTTPRoute CRD, but not the upstream `gateway.networking.kubernetes.io` version. We should probably perform the same validation for both HTTPRoute objects.

### How can it be reproduced?

n/a

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

n/a

### Environment

- Linkerd 2.13+

### Possible solution

We should probably add an implementation of the validating admission controller logic for both versions of HTTPRoute.

### Additional context

_No response_

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by mikutas**
Fixes #11116

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
Hi @mikutas 

I believe that this change will start sending admission requests for httproutes.gateway.networking.k8s.io to the policy-controller.  However, the policy-controller needs to be updated in order be able to handle these requests and do the correct validation on them.  These updates would need to happen inhttps://github.com/linkerd/linkerd2/blob/main/policy-controller/src/admission.rs

We should also add admission tests in the `policy-test` directory to verify that admission is working correctly for httproutes.gateway.networking.k8s.io

**Comment by hawkw** [comment]
> I believe that this change will start sending admission requests for httproutes.gateway.networking.k8s.io to the policy-controller. However, the policy-controller needs to be updated in order be able to handle these requests and do the correct validation on them. These updates would need to happen inhttps://github.com/linkerd/linkerd2/blob/main/policy-controller/src/admission.rs

And, it's worth noting that the validating logic for `gateway.networking.k8s.io` HTTPRoutes will need to be somewhat different from the existing validation logic for `policy.linkerd.io` HTTPRoutes. The validation for `policy.linkerd.io` routes simply rejects the route completely if it contains filters Linkerd doesn't support. If we also validate Gateway API routes, we will not be able to reject unsupported filters, because those filters might be used by other Gateway API implementations.  In general, when we're validating the shared upstream version of the HTTPRoute resource, we'll have to be more careful to ensure we don't reject configurations that are unsupported by Linkerd but used by other Gateway implementations.

**Comment by mikutas** [comment]
tried to add validation and test but copied many codes...

**Review by adleong — APPROVED** [review]

**Review by alpeb — APPROVED** [review]
LGTM :+1: 
I'm gonna push a small change to address my comment above re RBAC

**Pull request merged**
