### PR TITLE
bin/shellcheck-all: Add filename/shebang check

### PR DESCRIPTION
**Pull request by joakimr-axis**
We only run shellcheck for files that contain a `#!/usr/bin/env` shebang
with either `bash` or `sh`. If a new shellscript file is added that has the
`.sh` extension but either lacks shebang or has something other than that,
shellcheck will not be run for that file. Then there is a risk that
by mistake such a file slips into the repo under the radar.

(An example of a real situation where this is applicable is to be found in https://github.com/linkerd/linkerd2/pull/7419/commits/56a829d855f655e7f84dde5a41de697e7444e591)

This patch adds a check for all .sh files to make sure they have a
corresponding shebang in order for them to be passed to shellcheck.

Signed-off-by: Joakim Roubert <joakimr@axis.com>

### CODE REVIEW

**Review by Pothulapati — APPROVED** [review]
Thanks for the PR, (and also being our go-to shell scripting person)

**Review by olix0r — COMMENTED** [review]
Is this appropriate when the file itself is not meant to be executed?  I.e. Isn't `env_vars.sh` just sourced without ever being expected to be executed? I don't see how executing that file could ever make sense.

**Comment by joakimr-axis** [comment]
> Is this appropriate when the file itself is not meant to be executed? I.e. Isn't `env_vars.sh` just sourced without ever being expected to be executed? I don't see how executing that file could ever make sense.

Good point, and there are some things that are inconsistent with the `env_vars.sh` file. The current stat is that is is not checked at all by shellcheck in the CI; only files with an /usr/bin/env shebang using sh or bash are. So errors could, currently, slip into that file that would ruin things but the CI shellscript checker would be fine with it. One way could be manually and explicitly add `env_vars.sh` to the files to be checked, set it to be excluded from my check for files that have the exension .sh, and let its content remain as is. Perhaps that would be better? Either way, something needs to be done to cover the current non-check of `env_vars.sh`.

**Review by kleimkuhler — APPROVED** [review]
@joakimr-axis I think this is good as is. `env_vars.sh` is being run—albeit just as part of the current shell and not executed in a new one—so if it ever were to have more logic added for some reason we'll know it's being shellchecked.

Additionally, maintaining a separate exluded-from-shellcheck list of bash files seems unnecessary when including the shebang is as easy as it is.

**Review by adleong — COMMENTED** [review]
Rather than ensuring that all *.sh files have a shebang and then running shellcheck on all files with a shebang, can we instead just run shellcheck on all *.sh files?  This would allow shellcheck to run on non-executable shell files like env_vars.sh without needing to make it executable or add a shebang.

**Comment by joakimr-axis** [comment]
> Rather than ensuring that all *.sh files have a shebang and then running shellcheck on all files with a shebang, can we instead just run shellcheck on all *.sh files? This would allow shellcheck to run on non-executable shell files like env_vars.sh without needing to make it executable or add a shebang.

That's also a possibility. But then if someone adds a shellscript file with a name that does not have the extension .sh that file would go under the radar. And furthermore, shellcheck will complain with [SC2148](https://github-wiki-see.page/m/koalaman/shellcheck/wiki/SC2148) on the file that doesn't have the shebang, so you would have to add a shellcheck skip comment to that file to properly show that the shebang is missing for a reason. Then I think it would be less quirky to add such an exception line to the existing `env_vars.sh` and use the setup suggested in this PR for the rest. (But I think it makes more sense to add a shebang line than a we-deliberately-have-no-shebang-line to the file.)

**Review by adleong — APPROVED** [review]
Fair enough

**Pull request merged**
