### PR TITLE
Update proxy-init version to v1.3.6 for multi-arch support

### PR DESCRIPTION
**Pull request by cpretzer**
## What
Bump to the latest proxy-init version

## Why
Pulls in the latest changes to address CNI issues and support for multi-arch builds

Signed-off-by: Charles Pretzer <charles@buoyant.io>

### CODE REVIEW

**Comment by alpeb** [comment]
Note that I have removed the proxy-init:v1.3.5 image from the registry because of linkerd/linkerd2-proxy-init#24

**Comment by alpeb** [comment]
I updated v1.3.5 with the `nsenter` fix but proxy.golang.org refused to update the package, so I tagged v1.3.6 which #4850 uses, superseding the current PR.

**Comment by cpretzer** [comment]
thanks @alpeb, I'll update this PR appropriately

**Comment by cpretzer** [comment]
closing this in favor of #4850

**Pull request closed without merging**
