### PR TITLE
(WIP) Helm: Allow arbitrary annotations on APIService/ Webhook configs

### PR DESCRIPTION
**Pull request by cypherfox**
Currently the linkerd2 helm charts don't allow the setting of annotations on the `*WebhookConfiguration` and `APIService` resources for proxy-inject, sp-validator, tap.
Annotations are required e.g. to allow cert-manager to set the CA certificate bundle when updating the certificates of the webhooks.
While the CA bundles can be set right now via the helm chart, this requires manual work in addition to the configuration of the cert-manager. The result can be a fragile configuration and does not lend itself to further automating with helm chart that use the linkerd one as a dependency.

This merge will add a chart configuration variable to set arbitrary annotations on the webhook configuration resources.

The MR is in WIP state, as it does not have a proper test yet.

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks @cypherfox , this makes sense to me :+1:  Looking forward when it comes out of draft :wink:

**Comment by adleong** [comment]
Hey @cypherfox!  Are you still working on this or should we close out this PR for now?

**Comment by cypherfox** [comment]
Please leave open, unless somebody else is wanting to do the same.

**Comment by adleong** [comment]
No problem!  I'm going to mark this as a draft, however, for now.  Please mark it as non-draft once it's ready to be reviewed.  Thanks!

**Comment by adleong** [comment]
Hey @cypherfox, I'm going to close this since it's been idle for a while.  Feel free to re-open when you're ready to work on it.

**Pull request closed without merging**
