### PR TITLE
chore: remove bin/helm-doc

### PR DESCRIPTION
**Pull request by alpeb**
The version in `bin/helm-doc` isn't in sync with what's installed in the dev container, which generates a diff in the README chart files. CI uses the dev container and it appears most folks do as well, so I'm removing that script instead of having to keep it in sync.

### CODE REVIEW

**Review by olix0r — DISMISSED** [review]

**Comment by olix0r** [comment]
@alpeb there are a [few more references](https://github.com/search?q=repo%3Alinkerd%2Flinkerd2%20bin%2Fhelm-docs&type=code) in the repo

**Comment by alpeb** [comment]
Good spot :+1: 
I'm removing the call to `helm-docs` from the helm-publish action since at that point we've already verified the READMEs are in sync.

**Comment by alpeb** [comment]
In my last push I made the following updates:

- Removed the helm.yml workflow
- Removed bin/helm-docs-diff, not used anywhere
- Updated the helm-publish action to use helm-docs from the setup-tools action
- Removed the generated charts `README.md` files; people can consult the `values.yaml` files directly, or the generated READMEs at https://artifacthub.io/
- Uptaded the `BUILD.md` file to remove instructions about helm-docs.

**Review by adleong — APPROVED** [review]
🌮 🌮 🌮 🌮 🌮

**Review by olix0r — APPROVED** [review]

**Pull request merged**
