### PR TITLE
Prevent proxy-injection for Helm Hook Job Pod

### LINKED ISSUE #8194: Call proxy shutdown endpoint to fix namespace-metadata helm jobs not completing
### What problem are you trying to solve?

The helm charts for the jaeger, viz, and multicluster extensions create a `namespace-metadata` job which never completes. The pods that the jobs create get stuck in a `NotReady` state because their sidecar container never exits (see #1869).

I'm using Flux to deploy these helm charts, which interprets this non-completion as failure to finish the installation and requires a workaround.

### How should the problem be solved?

Using the `/shutdown` endpoint added in linkerd/linkerd2-proxy#811, the jobs' main containers could be updated to manually terminate the proxy when finished, allowing the pod to terminate and the job to complete (see https://github.com/Foltik/linkerd2/commit/398c2c53a5c21f4199721817567fe4bea3ddc13e).

### Any alternatives you've considered?

It looks like the official solution to this issue in the future will be to use the Keystone containers feature from kubernetes/enhancements/issues/2872.

### How would users interact with this feature?

_No response_

### Would you like to work on this feature?

yes

### PR DESCRIPTION
**Pull request by alex-berger**
Prevent proxy-injection for Helm Hook Job Pod for namespace-metadata, as the injected proxy would prevent the Job from terminating. See also https://github.com/linkerd/linkerd2/issues/8194, which was closed but the Problem still exists.

Fixes #8194

Signed-off-by: Alex Berger <alex-berger@gmx.ch>

### CODE REVIEW

**Comment by alex-berger** [comment]
@olix0r This addresses https://github.com/linkerd/linkerd2/issues/8194, which apparently was closed without really fixing the problem. Would, be great to have this fix in the upcoming stable release `stable-2.12.0`. Fixing the underlying issue is important for GitOps (e.g. FluxCD) users, as otherwise the FluxCD Helm Controller would wait forever for the `namespace-metadata` *Job* to terminate.

**Comment by alpeb** [comment]
Thanks for the PR @alex-berger. Note though that the idea behind this Job is to add some metadata to the `linkerd-viz` namespace that Helm (or another CD tool) creates, which is usually a naked namespace with no `inject` annotation on it. So we haven't had the need to override anything in this Job. It doesn't matter to have this override, but I'm wondering why you're requiring it in your case?

**Review by olix0r — COMMENTED** [review]
is this needed for other extensions?
```
:; find . -name namespace-metadata.yaml
./jaeger/charts/linkerd-jaeger/templates/namespace-metadata.yaml
./viz/charts/linkerd-viz/templates/namespace-metadata.yaml
./multicluster/charts/linkerd-multicluster/templates/namespace-metadata.yaml
```

**Comment by alpeb** [comment]
> is this needed for other extensions?

If we're adding this, yes, we should add it to all extensions for consistency.

**Comment by alex-berger** [comment]
> Thanks for the PR @alex-berger. Note though that the idea behind this Job is to add some metadata to the `linkerd-viz` namespace that Helm (or another CD tool) creates, which is usually a naked namespace with no `inject` annotation on it. So we haven't had the need to override anything in this Job. It doesn't matter to have this override, but I'm wondering why you're requiring it in your case?

In our case the `linkerd-viz` namespace has the following annotation `linkerd.io/inject=enabled`. I don't know yet whether that is by intention or whether we could remove that annotation from the namespace. However, as *Job*s and *CronJob*s  [do not work well with injected proxies](https://github.com/linkerd/linkerd2/issues/1869), I recommend you do not make any assumptions about the annotations on the `linkerd-viz` namespace and instead explicitly opt-out such *Pod*s from proxy injection by adding the `linkerd.io/inject=disabled` annotation (as proposed by this PR).

**Comment by alpeb** [comment]
> In our case the `linkerd-viz` namespace has the following annotation `linkerd.io/inject=enabled`. I don't know yet whether that is by intention or whether we could remove that annotation from the namespace. However, as _Job_s and _CronJob_s [do not work well with injected proxies](https://github.com/linkerd/linkerd2/issues/1869), I recommend you do not make any assumptions about the annotations on the `linkerd-viz` namespace and instead explicitly opt-out such _Pod_s from proxy injection by adding the `linkerd.io/inject=disabled` annotation (as proposed by this PR).

Sounds good :+1: 
Do you mind adding that to the other `namespace-metadata.yaml` files from the other extensions?

**Review by kleimkuhler — APPROVED** [review]
Thanks!

**Review by alpeb — APPROVED** [review]
LGTM! :+1: :ship:

**Pull request merged**
