### PR TITLE
Add functionality to helm chart to allow image digest for controllerImage

### LINKED ISSUE #11312: Allow controllerImage to be pulled via image digest
### What problem are you trying to solve?

I need to reference each image via a digest . I cannot refference the controllerImage via digest currently

### How should the problem be solved?

introduce functionality to the helm chart to allow this

### Any alternatives you've considered?

I deploy via helm chart so there is no other good solution

### How would users interact with this feature?

add field `.controllerImageVersion` to values.yaml and updates to the helm chart to allow the digest

### Would you like to work on this feature?

yes

### PR DESCRIPTION
**Pull request by adamshawvipps**
```
Subject
Introduce helm functionality for controllerImage  digest

Problem
I need to reference each image via a digest or its not allowed to run in our cluster. 
The current helm chart behaviour appends .Values.linkerdVersion but there is currently no way to add a digest.

This is not an issue for other images because they already allow tags

Solution
Add helm functionality to allow setting the controllerImage  tag

Validation
1. update values.yaml with 
controllerImageVersion: tag@sha

2. Run helm template using the above values and view the output. The controllerImage  now has   the   value `cr.l5d.io/linkerd/controller:tag@sha:123` allowing you to reference a digest

Fixes #11312 

DCO Sign off
Signed-off-by: Adam Shaw adam.shaw@vipps.no
```

### CODE REVIEW

**Comment by adleong** [comment]
Is this a duplicate of https://github.com/linkerd/linkerd2/pull/11278 ?

**Comment by cromulentbanana** [comment]
hi @adleong 

> Is this a duplicate of #11278 ?

it appears to be a duplicate, but unlike #11278 it does pass tests. Given that I'm also blocked due to the original problem motivating this PR, does anything speak against merging it?

Thanks!

**Review by adleong — APPROVED** [review]

**Comment by cromulentbanana** [comment]
Hi @adleong 

 as a second reviewer's approval is needed, will another reviewer independently take that initiative or do one of us need to explicitly ask another maintainer?

Thank you!

**Comment by adamshawvipps** [comment]
@cromulentbanana the DCO sign off on your commit appears to have failed. how to we rectify that?

**Comment by cromulentbanana** [comment]
> @cromulentbanana the DCO sign off on your commit appears to have failed. how to we rectify that?

I'm sorry, that was an oversight on my part.

Perhaps the fastest solution might be, either revert or amend that commit with the sign-off as your own user.

If you're unable or unwilling to do that, I can address this later today.

**Comment by adamshawvipps** [comment]
@cromulentbanana I think we got there in the end 

@alpeb are all the concerns addressed now?

**Comment by adleong** [comment]
Hi @adamshawvipps, I think something has gone wrong with your git branch.  Can you try making sure that your `main` base branch is up to date? 

For future reference, there are a number of different ways to agree to the DCO including by public statement, if that's easier.  https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

**Comment by adamshawvipps** [comment]
@adleong thanks for your help. I attempted to update the branch. Please let me know how it looks now

**Comment by cromulentbanana** [comment]
> @adleong thanks for your help. I attempted to update the branch. Please let me know how it looks now

hi @adamshawvipps this PR currently modifies 131 files over 48 commits -- that doesn't seem right to me. 

I've rebased the original feature branch (main) in my own git remote on that of upstream -- you can find it here: https://github.com/cromulentbanana/linkerd2.

I expect that if you fetch my repo and reset your `main` branch to my `main` branch, then this PR should be fixed.

**Comment by cromulentbanana** [comment]
In order to help speed this along, I submitted a PR that could replace this PR in its currently broken state: https://github.com/linkerd/linkerd2/pull/11406

@adleong @alpeb Feel free to either take my new PR in place of this one or abandon it, as you like.

**Comment by cromulentbanana** [comment]
hi @adamshawvipps would you prefer to fix this PR or shall we abandon it and go forward with #11406 ?

**Comment by cromulentbanana** [comment]
I believe that this can be closed now that https://github.com/linkerd/linkerd2/pull/11406 has been merged

**Pull request closed without merging**
