### PR TITLE
Add webhook timeout

### PR DESCRIPTION
**Pull request by mikebell90**
I agree to the DCO for all the commits in this PR

Fixes #11984

### CODE REVIEW

**Comment by mikebell90** [comment]
It wasn't clear to me whether I need to or you automatically run helm-docs. So I didn't update that

**Comment by mikebell90** [comment]
@adleong thanks. Sorry it was kind of confusing how to make all the tests pass, update helm-docs etc

**Comment by adleong** [comment]
No problem! I know it's pretty complex

**Review by adleong — APPROVED** [review]

**Review by mateiidavid — APPROVED** [review]

**Comment by mateiidavid** [comment]
Thanks @mikebell90!

**Pull request merged**
