### PR TITLE
Match linkerd-init CPU/memory requests/limits

### LINKED ISSUE #7980: initContainer - set cpu and memory requests/limits
### What problem are you trying to solve?

It looks like this ignores the proxy annotations and merely makes up it's own?
stable 2.11.1

```
Limits:
   cpu:   100m
   memory: 50Mi
  Requests:
   cpu:   10m
   memory: 10Mi
```

This is with setting various proxy-cpu-limit-request, etc annotations - which work fine on the main proxy container

This forces the entire pod into Burstable

### How should the problem be solved?

Annotations for the initContainer

```
config.linkerd.io/init-cpu-limit | Maximum amount of CPU units that the initContainer can use
config.linkerd.io/init-cpu-request | Amount of CPU units that the initContainer requests
config.linkerd.io/init-memory-limit | Maximum amount of Memory that the initContainer can use
config.linkerd.io/init-memory-request | Amount of Memory that the initContainer can requests
```

### Any alternatives you've considered?

There are none I'm aware of other than our own mutating controller ordered after linkerd-inject

### How would users interact with this feature?

They would add these annotations "normally", and linkerd-inject would do them

### Would you like to work on this feature?

maybe

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #7980 

A pod is considered `Burstable` instead of `Guaranteed` if there exists at least one container in the pod that specifies CPU/memory limits/requests that do not match.

The `linkerd-init` container falls into this category meaning that even if all other containers in a Pod have matching CPU/memory limits/requests, the Pod will not be considered `Guaranteed` because of `linkerd-init`'s hardcoded values.

This changes the values to match, meaning that `linkerd-init` will not be the culprit container if a Pod is not considered `Guaranteed`. Raising the requests—instead of lowering the limits—felt like the safer option here. This means that the container will now always be guaranteed these amounts _and_ will never use more.

[Docs](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed) explain this in more detail.

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Review by olix0r — APPROVED** [review]
Hm, given what this process does, 50MB seems a bit high of a memory request, but i guess it's probably a safe default...

**Comment by kleimkuhler** [comment]
I had the same thought but I wasn't sure if we ran into an issue before that lead to that being the current `limit`. But yes with the goal of this feeling like a safe change, 50 MB felt fine.

**Comment by olix0r** [comment]
I'm a little unclear on how these requests interact with init containers... is kubernetes smart enough to not add this request to all other requests in the container?  i.e. it would be bad if this change incurred a 50MB overhead on all pods for a process that probably uses ~10MB and exits immediately. I don't know what I don't know here...

We're probably fine dropping the request/limit to ~20MB, in any case...

**Comment by kleimkuhler** [comment]
Okay I changed the limit from 50Mi to 20Mi.

**Pull request merged**
