### PR TITLE
bin/test-cleanup: Fix shellcheck issues

### PR DESCRIPTION
**Pull request by joakimr-axis**

### CODE REVIEW

**Comment by joakimr-axis** [comment]
Thanks to the shellcheck upgrade to 0.7.1 (#4439) there is no longer need to have those variables in test-cleanup capital letters anymore to pass shellcheck. Patchset updated.

**Comment by kleimkuhler** [comment]
@joakimr-axis Running this locally it looks like [line 62](https://github.com/linkerd/linkerd2/pull/4421/files#diff-ecec5e3a811f60bc2739019004fa35b0R62) is an issue.

Running `bin/test-cleanup` results in an error for me:

```
kubectl --context= delete namespace/l5d-integration '' '' 'namespace/l5d-integration-smoke-test
```

The issue here is quoting the empty variables results in the `''` showing up. We would want the above to look like:

```
kubectl --context= delete namespace/l5d-integration namespace/l5d-integration-smoke-test ..
```

You may have a less verbose solution in mind, but I think parameter substitution should fix this.

Instead of:

```
kubectl --context="$k8s_context" delete "$namespaces_controlplane" "$namespaces_cni" ..
```

It can use parameter substitution:

```
kubectl --context="$k8s_context" delete ${namespaces_controlplane:+"$namespaces_controlplane"} ${namespaces_cni:+"$namespaces_cni"}
```

**Comment by grampelberg** [comment]
@kleimkuhler any suggestions on how to get CI happy here?

**Comment by kleimkuhler** [comment]
@grampelberg I'm pretty sure this issue I mentioned in https://github.com/linkerd/linkerd2/pull/4421#issuecomment-637062564 is the reason for these failures.

It's not flakiness, it's just failing to cleanup the tests now

**Comment by joakimr-axis** [comment]
>  You may have a less verbose solution in mind, but I think parameter substitution should fix this.

I really like your suggestion. IMO it is POSIX, easy to read and understand and does the job.
I will update this immediately.

Since we have bash in this script, another option would be to put the namespaces in an array or something, but I think that does things more complicated than they need to.

**Comment by joakimr-axis** [comment]
I am not sure how to interpret the test log (and hence search for the cause) where the `helm` integration test fails:

```
"linkerd" has been added to your repositories
Test script: [install_test.go] Params: [--linkerd-namespace=l5d-integration-helm --helm-path=/home/runner/work/linkerd2/linkerd2/bin/helm --helm-chart=/home/runner/work/linkerd2/linkerd2/charts/linkerd2 --helm-release=l5d-integration-test]
ok  	command-line-arguments	143.327s
release "l5d-integration-test" uninstalled
namespace/l5d-integration-helm condition met
##[error]error removing existing Linkerd resources
##[error]Process completed with exit code 1.
```

**Comment by kleimkuhler** [comment]
> I am not sure how to interpret the test log (and hence search for the cause) where the helm integration test fails

@joakimr-axis Yes I think we pipe the output to `/dev/null` right now which is not too helpful. Running locally, it's failure is not related to helm but still that `bin/test-cleanup` is not properly generating the `kubectl delete` command.

When I run `bin/test-cleanup` manually and add `set -x` to the script on a cluster with linkerd resources, I see this:

```
kubectl --context= delete namespace/linkerd-integration 'namespace/linkerd-integration-smoke-test
namespace/linkerd-integration-smoke-test-ann
namespace/linkerd-integration-smoke-test-manual' 'clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-controller
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-destination
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-identity
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-prometheus
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-proxy-injector
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-sp-validator
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-tap
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-tap-auth-delegator
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-web-admin
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-integration-web-check' 'clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-controller
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-destination
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-identity
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-prometheus
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-proxy-injector
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-sp-validator
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-tap
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-tap-admin
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-integration-web-check' mutatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-proxy-injector-webhook-config validatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-sp-validator-webhook-config podsecuritypolicy.policy/linkerd-linkerd-integration-control-plane 'customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io
customresourcedefinition.apiextensions.k8s.io/trafficsplits.split.smi-spec.io' apiservice.apiregistration.k8s.io/v1alpha1.tap.linkerd.io
error: arguments in resource/name form may not have more than one slash
```

Simplyfing this down, this still fails:

```
kubectl --context= delete 'namespace/linkerd-integration-smoke-test namespace/linkerd-integration-smoke-test-manual'
error: arguments in resource/name form may not have more than one slash
```

It looks like the issue is when one of the variables is an array of resources, it is rendered with surrounding `'`s. I think `kubectl delete` then see it as one resource instead of multiple, and thinks there are too many slashes.

This would work if it didn't render the quotes:

```
kubectl --context= delete namespace/linkerd-integration-smoke-test namespace/linkerd-integration-smoke-test-manual
```

I'm not sure if there is a way to unpack an array without quoting it; that should fix the issue.

We could also add a `# shellcheck disable` here so that it doesn't get too complex looking.

**Comment by joakimr-axis** [comment]
Running locally, it's failure is not related to helm but still that `bin/test-cleanup` is not properly generating the `kubectl delete` command.
[...]

But of course! THANK YOU, I was looking for something like that but (obviously failed). Yes, it is the _array_ that causes the issue here when treated as a non-array.

> I'm not sure if there is a way to unpack an array without quoting it; that should fix the issue.

I think we could just do it the @adleong way from #4489. I will fix this immediately.

> We could also add a `# shellcheck disable` here so that it doesn't get too complex looking.

It shouldn't have to come to that if there is a proper way of doing it! :-)

**Comment by kleimkuhler** [comment]
@joakimr-axis Great! I think you'll need to make the same change for all the variables in the other `kubectl delete` (on line 62) as well.

**Comment by joakimr-axis** [comment]
Yes, will do!

**Comment by kleimkuhler** [comment]
Looking good!

Looks like the bash substitution still needs to be used. Using your change here, and bash substitution from above, `bin/test-cleanup` did work for me locally:

```
kubectl --context="$k8s_context" delete ${namespaces_controlplane:+"${namespaces_controlplane[@]}"} ${namespaces_cni:+"${namespaces_cni[@]}"} ${namespaces_helm:+"${namespaces_helm[@]}"} ${namespaces_dataplane:+"${namespaces_dataplane[@]}"} ${clusterrolebindings:+"${clusterrolebindings[@]}"} ${clusterrolebindings_helm:+"${clusterrolebindings_helm[@]}"} ${clusterroles:+"${clusterroles[@]}"} ${webhookconfigs:+"${webhookconfigs[@]}"} ${validatingconfigs:+"${validatingconfigs[@]}"} ${podsecuritypolicies:+"${podsecuritypolicies[@]}"} ${customresourcedefinitions:+"${customresourcedefinitions[@]}"} ${apiservices:+"${apiservices[@]}"}
```

**Comment by joakimr-axis** [comment]
> Looking good!

Thanks!

> Looks like the bash substitution still needs to be used. Using your change here, and bash substitution from above, `bin/test-cleanup` did work for me locally:

Thanks for checking that out! I have now updated (and reformatted somewhat to make it easier on human readers' eyes) and the tests pass.

**Comment by kleimkuhler** [comment]
Thanks for working through all the CI errors on this @joakimr-axis--really appreciate it!

**Comment by joakimr-axis** [comment]
> Thanks for working through all the CI errors on this @joakimr-axis--really appreciate it!

Thank you for the positive feedback and your assistance along the way. Teamwork!

**Pull request merged**
