### PR TITLE
[linkerd-jaeger] Adds support for collector config merge and Deployment env

### PR DESCRIPTION
**Pull request by iAnomaly**
Signed-off-by: Cameron Boulton <cameron.boulton@calm.com>

This PR changes a variety of things:
1. Changes value `collector.config` from a string to an object to support field level merging/changing without having to copy/paste the entire unchanged portion of the config.
2. Changes the default `collector.config` for sensible out of the box Linkerd tracing use-case:
    1. Only `opencensus` receiver (the format `linkerd-proxy` emits when configured for tracing)
    2. `resource` processor that maps the Pod name and namespace labels `linkerd-proxy` sets on injected Pods to the fields the `k8sattributes` processor expects for looking up the trace's source Pod.
    3. `k8sattributes` processor for decorating all traces with K8s metadata.
3. Standardizes `image.pullPolicy` behavior across all components and defaults to absent/null `imagePullPolicy` such that the K8s cluster configuration is used.
4. Adds collector RBAC needed for `k8sattributes` to lookup trace source K8s workloads
5. Adds collector ConfigMap checksum to rollout new Pod(s) when config is changed. 
6. Adds/parameterizes the collector container command with value `collector.command`.
7. Changes collector image from [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) to [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) which includes additional connectors, exporters, extensions, processors, receivers.
8. Adds value `collector.env` for additional collector Deployment environment variables.

### CODE REVIEW

**Comment by wmorgan** [comment]
Thank you @iAnomaly!

**Comment by wmorgan** [comment]
Sorry for the delay. The relevant maintainers were pulled into some high-priority customer escalations. This is still in the queue to review.

**Review by adleong — APPROVED** [review]
This is awesome!  Thanks for this contribution!
Screenshot 2023-09-12 at 5 20 18 PM

**Review by mateiidavid — APPROVED** [review]
🚢 📦! Thanks for the PR :)

**Pull request merged**
