### PR TITLE
Add Allotrac to ADOPTERS.md

### PR DESCRIPTION
**Pull request by dddanmar**
Subject: Add Allotrac to ADOPTERS.md

Problem: Allotrac has moved their entire production workload over to Linkerd.

Solution Add it to the ADOPTERS.md!

### CODE REVIEW

**Comment by dddanmar** [comment]
I didn't see this was in alphabetical order, I'll redo this next week.
(this is why we don't deploy on Friday afternoons!)

**Comment by cpretzer** [comment]
I'm going to merge this, then submit a new PR with the name in alphabetical order.

**Comment by cpretzer** [comment]
@dddanmar we're really excited to get you added to the adopters list, and I just saw that the DCO check didn't go through.

Before you resubmit the PR (whether it's this one or another one), please have a look at the [DCO section of CONTRIBUTING.md](https://github.com/linkerd/linkerd2/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)

Thanks again for being part of the community and we're looking forward to getting you added to the adopters list! 😄 🎉

**Comment by dddanmar** [comment]
Fixed the ordering and added the DCO line!

**Comment by dddanmar** [comment]
I'm just not winning here - did not anticipate the DCO to need my Git details and filled in with work details.

**Comment by dddanmar** [comment]
Fixed in #3797

**Pull request closed without merging**
