### PR TITLE
Removed dupe imports

### PR DESCRIPTION
**Pull request by alpeb**
My IDE (vim-gopls) has been complaining for a while, so I decided to take care of it. Found via [staticcheck](https://github.com/dominikh/go-tools)

### CODE REVIEW

**Comment by olix0r** [comment]
is staticcheck not enabled in our golangcilint? should it be?

**Review by olix0r — APPROVED** [review]

**Comment by alpeb** [comment]
> is staticcheck not enabled in our golangcilint? should it be?

It's enabled but it's [not exactly the same original staticcheck](https://golangci-lint.run/usage/linters/#enabled-by-default) and apparently it misses things like the dupe imports check:
> It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint.

We'd have to add an additional job to trigger the original staticcheck.

**Review by kleimkuhler — APPROVED** [review]

**Comment by adleong** [comment]
I got golangci-lint to check for duplicate imports by adding this to the config:

```
diff --git a/.golangci.yml b/.golangci.yml
index 80bef4a3c..ae55de564 100644
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -28,6 +28,7 @@ linters:
   - nakedret
   - revive
   - staticcheck
+  - stylecheck
   - typecheck
   - unconvert
   - unparam
@@ -42,7 +43,6 @@ linters:
   # - lll
   # - maligned
   # - prealloc
-  # - stylecheck
 
   disable:
   # https://github.com/golangci/golangci-lint/issues/2649
@@ -53,6 +53,8 @@ linters-settings:
     rules:
     - name: package-comments
       disabled: true
+  stylecheck:
+    checks: ["ST1019"]
 
 issues:
   exclude-use-default: false
```

and confirmed that your change resolves the duplicate import errors.  I think we should add this to the golangci-lint config to prevent duplicate imports going forward.

**Comment by alpeb** [comment]
Thanks for the lint config investigation @adleong, I've added it into this PR :+1:

**Pull request merged**
