### PR TITLE
public-api/viz split 1/8: a couple more protobuf changes

### PR DESCRIPTION
**Pull request by alpeb**
- Moved `healthcheck.proto` back from viz to `proto/common` as it remains being used by the main `healthcheck.go` library (it was moved to viz by #5510).
- Extracted from `viz.proto` the IP-related types and put them in `/controller/gen/common/net` to be used by both the public and the viz APIs.

### CODE REVIEW

**Review by Pothulapati — APPROVED** [review]
LGTM, 👍  on moving the IP types to a common pkg

**Comment by adleong** [comment]
As far as I can tell, the only place that `healthcheck.proto` is used in `healthcheck.go` is for the `checkRPC` machinery which only exists to call the `SelfCheck` API (which itself is moving to the viz API.  I would expect that `healthcheck.proto` would move to the viz extension and all of the `checkRPC` stuff would be removed from `healthcheck.go`.

I think `checkRPC` was probably overly complicated to begin with and I think only existed so that a single call to `SelfCheck` could return multiple check results.  Once this moves to the viz extension, I am perfectly okay simplifying this to be a regular check which returns a single result, just like everything else.

**Comment by alpeb** [comment]
@adleong that's a great call. In #5557 I have moved the `SelfCheck` API. I'll see how easy it would be to make that change in #5557 and its downstream PRs, or as a separate effort altogether.

**Comment by alpeb** [comment]
I figured the easiest would be to tackle the SelfCheck API refactoring separately, so I raised #5575 detailing the changes.

**Review by kleimkuhler — COMMENTED** [review]
`SelfCheck` refactoring aside, these changes look good.

@alpeb Just to make sure I'm following, you won't be making the `SelfCheck` refactoring changes as part of #5557 and will instead do this separately once this whole 1-8 merges?

**Comment by alpeb** [comment]
> @alpeb Just to make sure I'm following, you won't be making the `SelfCheck` refactoring changes as part of #5557 and will instead do this separately once this whole 1-8 merges?

Correct

**Review by kleimkuhler — APPROVED** [review]
👍

**Comment by alpeb** [comment]
Closing in favor of #5560 which will aggregate all these changes.

**Pull request closed without merging**
