### PR TITLE
Replaced deprecated label failure-domain

### LINKED ISSUE #11114: Replace the deprecated "failure-domain" label with "topology" label in the partials _affinity.tpl
### What is the issue?

As of K8s 1.17 the [`failure-domain`](https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone) label has been replaced with the [`topology`](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone) label. 

Our current implementation leads to noisy logs (and unnecessary ingestion costs associated with them) for users running on higher versions of K8s when paired with scheduling tools such as Karpenter. We should update our templates to reflect the currently supported label.

### How can it be reproduced?

Set up Linkerd in a Karpenter-controlled cluster and observe the logs noted below when attempting to schedule new pods.

### Logs, error output, etc

relaxing soft constraints for pod since it previously failed to schedule, removing: spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"linkerd.io/control-plane-component","operator":"In","values":["proxy-injector"]}]},"topologyKey":"failure-domain.beta.kubernetes.io/zone"}}

### output of `linkerd check -o short`

n/a

### Environment

n/a

### Possible solution

update templates to use supported labels.

### Additional context

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by piyushsingariya**
This PR fixes #11114 as mentioned in the issue,  templates are using a deprecated label `failure-domain`which has been replaced with `topology` from K8S version 1.17

[k8s docs about update for deprecated label](https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone) (mentioned in the respective issue also)

### CODE REVIEW

**Review by adleong — APPROVED** [review]

**Review by alpeb — COMMENTED** [review]
Thanks for the swift contribution @piyushsingariya . But if I'm ready right the docs you link to, should the new label be just `topology.kubernetes.io/region`?

**Comment by piyushsingariya** [comment]
> Thanks for the swift contribution @piyushsingariya . But if I'm reading right the docs you link to, shouldn't the new label be just `topology.kubernetes.io/region`?

image


@alpeb I am seeing `topology.kubernetes.io/zone` here.

**Comment by alpeb** [comment]
I made a typo in my previous comment. What I meant is that the `beta` part should be dropped.

**Comment by piyushsingariya** [comment]
> I made a typo in my previous comment. What I meant is that the `beta` part should be dropped.

My bad, I overlooked it. Will update the PR by this weekend. Thanks @alpeb

**Comment by alpeb** [comment]
@piyushsingariya can you take this one across the line? I'd love to include it in tomorrow's edge release :wink:

**Comment by piyushsingariya** [comment]
@alpeb apologies I totally missed the mark here. Thanks you! Let's get this merged now?

**Review by alpeb — APPROVED** [review]
There was one more typo whose fix I've just pushed into your branch. Should be good to go now! :shipit:

**Pull request merged**
