### PR TITLE
[RFC] Bikeshed the tap and top icons

### PR DESCRIPTION
**Pull request by adleong**
I find the tap and top icons a bit strange.  Using the filter icon for tap is weird because we already use the filter icon for filtering columns.  The caret-up icon looks weird to me for top because it looks like something that is click to expand.

Unfortunately, the alternatives aren't super great either.  Here are some possibilities I could think of:

For tap:
* `eye` (although this sometimes indicates show/hide... and it also just looks weird)
* `phone`
* `shower` (too whimsical?)

For top:
* `table` (looks like a calendar)
* `list-ol`
* `arrow-up`

Thoughts?

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Comment by adleong** [comment]
I like `stream` for top!  Another idea: `microscope` for tap.

**Comment by grampelberg** [comment]
That's awesome, I was looking for some kind of Sherlock icon, microscope is
perfect.

**Comment by rmars** [comment]
Yayyy, thanks for fixing these. I couldn't really think of good ones when I added this so I chose super arbitrarily.
Where are stream and microscope? Are they at https://ant.design/components/icon/ and I'm just blind?

**Comment by adleong** [comment]
https://fontawesome.com/icons/microscope?style=solid 

do we have fontawesome icons?

**Comment by rmars** [comment]
I don't think we actually have them anywhere right now, but we used to? They shouldn't be too bad to add.

**Comment by klingerf** [comment]
Looks like we're still importing the font-awesome css, here:

https://github.com/linkerd/linkerd2/blob/master/web/app/css/styles.css#L1

But we'd need to upgrade to the latest version to get the microscope icon. I'm planning on doing this as part of #1461.

**Comment by rmars** [comment]
I like microscope a lot! Stream is good too!

**Pull request merged**
