### PR TITLE
Add conntrack and netstat to debug container

### LINKED ISSUE #3671: Add netstat and conntrack to the debug container
## Feature Request
Add the `conntrack` and `netstat` utilities to the debug container

### What problem are you trying to solve?
While using the debug container, it's necessary to run `apt update && apt install` in the debug container to get `conntrack` and `netstat` for debugging. I'd like to save a few keystrokes. :)

### How should the problem be solved?
Add the `conntrack` and `net-tools` packages to the `apt install` command in `Dockerfile-debug`

### Any alternatives you've considered?
Just leave things as they are and document that users of the debug container can use `apt update && apt install` to install utilities

### PR DESCRIPTION
**Pull request by cpretzer**
Signed-off-by: Charles Pretzer <charles@buoyant.io>

Fixes #3671

### CODE REVIEW

**Comment by olix0r** [comment]
FWIW `ss` is considered to be the standard replacement for netstat these days. I thought we already had `ss` installed but maybe not

**Comment by cpretzer** [comment]
TIL! Thanks @olix0r, I've updated the PR

**Comment by olix0r** [comment]
@cpretzer though, i think i may have been wrong about `ss` already being available...

```
:; docker run --rm -it gcr.io/linkerd-io/base:2019-09-04.01 bash   
root@23445c64be1c:/# ss
bash: ss: command not found

```

**Comment by cpretzer** [comment]
okay, double checking now. Thanks for the review

**Comment by cpretzer** [comment]
Verified that the new updated debug image has `ss` and `conntrack`

**Pull request merged**
