### PR TITLE
Injection labels fixes

### PR DESCRIPTION
**Pull request by alpeb**
Follow-up to #2334 

Have `GetPatch()` return `*Patch` instead of its marshalled version, so that the consuming side can contribute to the patch; the CLI and the webhook now are adding their own `Created-by` labels, and the webhook will set the Deployment-level labels that Kuberenetes automatically adds in the CLI scenario (ref #2377).

### CODE REVIEW

**Comment by alpeb** [comment]
In my mind it's useful to know whether CLI or webhook injected something for debugging purposes... Any other opinions?

**Comment by ihcsim** [comment]
> In my mind it's useful to know whether CLI or webhook injected something for debugging purposes

Yup, totally fine. What you have here is good.

**Comment by klingerf** [comment]
Yep, I like having different `created-by` annotations based on whether the pod was injected by the CLI or auto-injector. I glance at bc1dca8d, and it looks good to me, pending other reviewers' comments. If it's too much of a pain to rebase this branch, I recommend just pushing a separate commit to #2334 with this change, I can review it there.

**Comment by alpeb** [comment]
I'm moving this patch into #2334 , after having applied your suggestions.

**Pull request closed without merging**
