### PR TITLE
Add new integration test for "linkerd multicluster allow" command #6693

### LINKED ISSUE #6693: Create new integration test for `linkerd multicluster allow`
`linkerd multicluster allow` outputs credentials resources (ClusterRole, ServiceAccount and a ClusterRoleBinding to link them) besides the default ones returned by `linkerd multicluster install`, to give additional access to a target cluster. 

Turns out this command has been broken for a few releases:
```console
$ linkerd mc allow --service-account-name foobar
Error: template: linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml:16:7: executing "linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml" at <include "partials.annotations.created-by" $>: error calling include: template: no template "partials.annotations.created-by" associated with template "gotpl"
```
but has already been fixed by #6665

It would be nice though to have it tested in the integration tests, somewhere under `test/integration/multicluster`. A simple call to the command using the context of the target cluster, and comparing its output to a golden file should do the trick.

### PR DESCRIPTION
**Pull request by krabradosty**
New test passes locally, need to check it in CICD pipeline

Fixes #6693

Signed-off-by: Dima Pugachev <krabradosty@gmail.com>

### CODE REVIEW

**Comment by krabradosty** [comment]
Two tests have failed. 
**Integration tests / test-multicluster (v1.21)** - looks like flaky
**Integration tests / test-policy (v1.26)** - related to Rust, I have no expertise

**Comment by mateiidavid** [comment]
I've re-run the failed actions. It's likely just some random timeouts. Would you mind pulling in the latest main? We made some small change to the multicluster tests to remove the viz dependency.

**Comment by krabradosty** [comment]
@mateiidavid `test-policy` suite has failed again. Please re-run it

**Comment by krabradosty** [comment]
**test-policy (v1.26)** still fails for some reason

**Review by alpeb — APPROVED** [review]
This is very nice, thanks @krabradosty !

**Review by mateiidavid — APPROVED** [review]

**Pull request merged**
