### PR TITLE
Guard `endpointTranslator` with mutex

### LINKED ISSUE #9896: linkerd-destination panicking
### What is the issue?

We just noticed that one of the POD of `linkerd-destination` crashed, after log analysis we found that there was a PANIC.
```
fatal error: concurrent map iteration and map write

[github.com/linkerd/linkerd2/controller/api/destination](http://github.com/linkerd/linkerd2/controller/api/destination).(*endpointTranslator).filterAddresses(0xc001386c80)
```

### How can it be reproduced?

I don't know exactly but at that time we had a peak of requests, maybe this will somehow help to reproduce the problem
image

### Logs, error output, etc

https://gist.github.com/mkrutik/42757233dbfd957c2f482a6ea3e00926

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.11.2 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.11.2 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-67f4d78577-k85vs (stable-2.11.2)
	* linkerd-destination-67f4d78577-xl2tj (stable-2.11.2)
	* linkerd-destination-67f4d78577-xxwvd (stable-2.11.2)
	* linkerd-identity-766d9bcf58-4cvn4 (stable-2.11.2)
	* linkerd-identity-766d9bcf58-pwmts (stable-2.11.2)
	* linkerd-identity-766d9bcf58-z9g7c (stable-2.11.2)
	* linkerd-proxy-injector-5bd7996d4-6d6hq (stable-2.11.2)
	* linkerd-proxy-injector-5bd7996d4-7667v (stable-2.11.2)
	* linkerd-proxy-injector-5bd7996d4-jq7pk (stable-2.11.2)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* grafana-7d95b8bb5d-hdbf4 (stable-2.11.2)
	* metrics-api-5678574899-4d2vb (stable-2.11.2)
	* metrics-api-5678574899-bgk5j (stable-2.11.2)
	* metrics-api-5678574899-cg9fn (stable-2.11.2)
	* service-prom-label-proxy-5567447694-9lxm2 (stable-2.11.2)
	* service-prom-label-proxy-5567447694-db7fz (stable-2.11.2)
	* tap-8486c6bff4-bpkrs (stable-2.11.2)
	* tap-8486c6bff4-l7vxg (stable-2.11.2)
	* tap-8486c6bff4-q49hh (stable-2.11.2)
	* tap-injector-85ffdc44fd-9vlb4 (stable-2.11.2)
	* web-558d8b8f96-rxn9n (stable-2.11.2)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- Kubernetes: v1.22.12-gke.2300
- Cluster environment: GKE
- Linkerd version: stable-2.11.2

### Possible solution

_No response_

### Additional context

_No response_

### Would you like to work on fixing this bug?

no

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #9896

The maps in `endpointTranslator` weren't being guarded against concurrent access, so we're adding locks at the `Add` and `Remove` methods. Also these functions ultimately call the `SendMsg` method on the gRPC `stream`, which is not
["thread-safe"](https://github.com/grpc/grpc-go/blob/master/stream.go#L122-L126), so as a side-effect we're guarding against other problems as well.

A new unit test `TestConcurrency` was added that failed in the following ways before this fix:

- When running the test with the `-race` flag, we immediately get the data race warning:

```bash
$ go test ./controller/api/destination/... -run TestConcurrency -race
time="2022-11-25T16:48:52-05:00" level=info msg="waiting for caches to sync"
time="2022-11-25T16:48:52-05:00" level=info msg="caches synced"
==================
WARNING: DATA RACE
Read at 0x00c0000c0040 by goroutine 161:
  github.com/linkerd/linkerd2/controller/api/destination.(*endpointTranslator).Add()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator.go:80 +0x29c
  github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency.func1()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:338 +0x92

Previous write at 0x00c0000c0040 by goroutine 162:
  github.com/linkerd/linkerd2/controller/api/destination.(*endpointTranslator).sendFilteredUpdate()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator.go:95 +0x66
  github.com/linkerd/linkerd2/controller/api/destination.(*endpointTranslator).Add()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator.go:83 +0x330
  github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency.func1()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:338 +0x92

Goroutine 161 (running) created at:
  github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:336 +0x6f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47

Goroutine 162 (running) created at:
  github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency()
      /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:336 +0x6f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
```

- If run without the `-race` flag, we get the `concurrent map writes` panic reported in #9896:

```bash
$ go test ./controller/api/destination/... -run TestConcurrency -count=1
time="2022-11-25T16:53:25-05:00" level=info msg="waiting for caches to sync"
time="2022-11-25T16:53:25-05:00" level=info msg="caches synced"
fatal error: concurrent map writes

goroutine 187 [running]:
runtime.throw({0x1b57bc4?, 0x500000000000000?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00013dc80 sp=0xc00013dc50 pc=0x43a5b1
runtime.mapassign(0xc00013dec8?, 0x2?, 0x0?)
        /usr/local/go/src/runtime/map.go:595 +0x4d6 fp=0xc00013dd00 sp=0xc00013dc80 pc=0x4113b6
github.com/linkerd/linkerd2/controller/api/destination.(*endpointTranslator).Add(...)
        /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator.go:80
github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency.func1()
        /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:338 +0x1a8 fp=0xc00013dfe0 sp=0xc00013dd00 pc=0x16d1da8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x46d721
created by github.com/linkerd/linkerd2/controller/api/destination.TestConcurrency
        /home/alpeb/pr/destination-panic/linkerd2/controller/api/destination/endpoint_translator_test.go:336 +0x3c
`

### CODE REVIEW

**Comment by alpeb** [comment]
I'm not sure if there's value on keeping that new test here, so will probably remove it before merging and instead will keep it as a note in the commit.

**Review by mateiidavid — APPROVED** [review]
Great find! IIUC the problem is:

1. For each `Get` request we create an `EndpointTranslator` (et)
2. `et` holds some state. `Add` and `Remove` functions may be called on it successively, e.g when a pod comes up, we'd call `Remove` followed by `Add`
3. Without a lock, both will operate on the same internal state (`et.availableEndpoints` and `et.filteredSnapshot`)
4. We get into trouble because we share memory in both of these locations and also both functions will call `SendMsg` on the grpc stream which is unsafe

> // but it is not safe to call SendMsg on the same stream in different goroutines
(ref: grpc lib comment linked above)

Is my understanding of the problem correct or is there something else I'm missing? Also, shame about the test, it would be cool to keep it in. I remember we used to suggest in some docs to run `go test ./... -race` perhaps precisely for this reason? Would be worth figuring out how to have some unit tests that exercise concurrency to make sure we don't bump into it further down the line.

**Comment by alpeb** [comment]
@mateiidavid , yep you've got it right. Just a couple of  notes:

> 2\. `et` holds some state. `Add` and `Remove` functions may be called on it successively, e.g when a pod comes up, we'd call `Remove` followed by `Add`

It appears events for a single object (using the same event handler) are [processed sequentially](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L135-L140). So I guess the source of races comes from different handlers like, services (that use a separate handler) getting updated at the same time as pods.

> I remember we used to suggest in some docs to run go test ./... -race perhaps precisely for this reason? 

We actually already do that [in CI](https://github.com/linkerd/linkerd2/blob/main/justfile#L20-L21), but our current unit tests for this particular case weren't excising `Add`/`Remove` concurrently.

I can just leave the test if you deem it makes sense :+1:

**Review by adleong — APPROVED** [review]
Great find and fix!

**Pull request merged**
