### PR TITLE
Add services to web dashboard

### LINKED ISSUE #6648: Dashboard support for `stat` on services
## Feature Request

See https://github.com/linkerd/linkerd2/issues/2967, 

With #6514, `stat` on services now works with the use of client side metrics and `authority` label. This means that the dashboard can also be made to do the same with a new `Services` button on the side bar. Most of the changes should be straight forward and should be very similar to the existing code paths but stat on services differs in the following ways:

- The `StatsSummary` response might include `weights` when a `ServiceProfile` exists. In which case, a different table format has to be used for rendering.
- Add an additional note describing how stat on a `service` differs. See #6646

### PR DESCRIPTION
**Pull request by krzysztofdrys**
Adds services as a new screan on a web dashboard. Services screen is
implemented as a separate func, because it is different from
pods/jobs/etc.

Services view will not have pods or edges section because this
information is not available.

Fixes #6648

Signed-off-by: Krzysztof Dryś <krzysztofdrys@gmail.com>

### CODE REVIEW

**Comment by Pothulapati** [comment]
@krzysztofdrys Thanks for the update! This goods till here.

Comparing the outputs from the viz cmd,

```
on ⛵ kind-kind  linkerd2 on 🌱 dash [📦🤷‍] via 🐼 v1.16.8 via  via ⚙️
❯ ./bin/linkerd -n linkerd-trafficsplit-test-sp stat svc/backend-svc                                       ~/work/linkerd2
Command "stat" is deprecated, use instead 'linkerd viz stat [flags] (RESOURCES)'

NAME          DST           WEIGHT   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
backend-svc   backend-svc     500m   100.00%   0.5rps           1ms           2ms           2ms          1
backend-svc   failing-svc     500m     0.00%   0.5rps           1ms           3ms           3ms          1

on ⛵ kind-kind  linkerd2 on 🌱 dash [📦🤷‍] via 🐼 v1.16.8 via  via ⚙️
➜ ./bin/linkerd -n linkerd-trafficsplit-test-sp stat svc                                                                                          ~/work/linkerd2
Command "stat" is deprecated, use instead 'linkerd viz stat [flags] (RESOURCES)'

NAME          MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
backend-svc        -   100.00%   0.5rps           1ms           2ms           2ms          1
failing-svc        -     0.00%   0.5rps           1ms           2ms           2ms          0

on ⛵ kind-kind  linkerd2 on 🌱 dash [📦🤷‍] via 🐼 v1.16.8 via  via ⚙️
➜ ./bin/linkerd -n linkerd-trafficsplit-test-sp stat svc/failing-svc                                                                              ~/work/linkerd2
Command "stat" is deprecated, use instead 'linkerd viz stat [flags] (RESOURCES)'

No traffic found.
```

Can we also show the weights and `DST` when **are available** in the services tab. If we do that I don't think we need anything special w.r.t traffic splitting. that should be enough.

> By and large I was trying to get the same/similar output as linkerd viz stat. There is not much on namespaces/linkerd-trafficsplit-test-sp/services/failing-svc, but at the same time:

When there is no direct traffic, I don't think we can show that directly. the same applies to the dashboard too I guess.

Also, Weirdly I don't see the grafana links 🤔 
image

**Comment by krzysztofdrys** [comment]
About grafana links: I will fix them. When I run `bin/web dev` there is no grafana, so I might have broke something.

> Can we also show the weights and DST when are available in the services tab.
You mean service details tab, right? Because there should be no weights on services list tab. At least there are none, whe I do `linkerd  viz stat svc -n linkerd-trafficsplit-test-sp`

**Comment by krzysztofdrys** [comment]
image

image

image

image

**Comment by krzysztofdrys** [comment]
@Pothulapati above are the newest screenshots. I tried to follow you suggestion. I added destination column. Please correct me if something is wrong. :-)

It would be easiest for me, if you somehow listed things to fix (other than grafana links).

**Comment by krzysztofdrys** [comment]
@Pothulapati I have just pushed fix which adds the grafana link.

BTW I was presently surprised that there already is a dashboard for services in grafana.

**Comment by Pothulapati** [comment]
> You mean service details tab, right? Because there should be no weights on services list tab. At least there are none, whe I do linkerd viz stat svc -n linkerd-trafficsplit-test-sp

@krzysztofdrys Yep, Right. That seems correct. Let me take another look today, and this should be good to go. Thanks

**Review by Pothulapati — APPROVED** [review]
LGTM! Showing trafficsplits through outbound table seems like the right way to replicate what's currently present in the CLI.

Thanks for taking this up!

I think, we should also verify the metrics in the grafana links for services, as those grafana configs seem to be present from when services were a thing (initially they were). This should be done in separate issue I think. Let's get this PR merged first.

**Review by alpeb — APPROVED** [review]
Thanks @krzysztofdrys , this is solid :+1:

**Pull request merged**
