### PR TITLE
Add client-go cache size metrics

### LINKED ISSUE #6354: Expose client-go cache metrics in control plane components
Control plane components such as `linkerd-proxy-injector` and `linkerd-destination` create multiple client-go informers whose caches can potentially grow a lot in big clusters that keep track of lots of workloads and resources. In order to verify that assumption we need to expose informer metrics.
It appears there's some instrumentation in place as shown in `reflector_metrics.go`(https://github.com/kubernetes/client-go/blob/v0.21.2/tools/cache/reflector_metrics.go) that we could wire-in.

### PR DESCRIPTION
**Pull request by adleong**
Fixes #6354 

We add Prometheus gauges which track the client-go cache size for each resource type.  For example, the following metrics are added to the destination controller:

```
# HELP endpoint_cache_size Number of items in the client-go endpoint cache
# TYPE endpoint_cache_size gauge
endpoint_cache_size 21
# HELP job_cache_size Number of items in the client-go job cache
# TYPE job_cache_size gauge
job_cache_size 0
# HELP namespace_cache_size Number of items in the client-go namespace cache
# TYPE namespace_cache_size gauge
namespace_cache_size 8
# HELP node_cache_size Number of items in the client-go node cache
# TYPE node_cache_size gauge
node_cache_size 1
# HELP pod_cache_size Number of items in the client-go pod cache
# TYPE pod_cache_size gauge
pod_cache_size 23
# HELP replica_set_cache_size Number of items in the client-go replica_set cache
# TYPE replica_set_cache_size gauge
replica_set_cache_size 40
# HELP service_cache_size Number of items in the client-go service cache
# TYPE service_cache_size gauge
service_cache_size 18
# HELP service_profile_cache_size Number of items in the client-go service_profile cache
# TYPE service_profile_cache_size gauge
service_profile_cache_size 4
# HELP traffic_split_cache_size Number of items in the client-go traffic_split cache
# TYPE traffic_split_cache_size gauge
traffic_split_cache_size 0
```

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Review by dadjeibaah — APPROVED** [review]
Tested and works great! 📦 🚢

**Comment by Pothulapati** [comment]
This looks good. So, I was trying to see if there are any projects exposing `client-go` metrics, and I stumbled upon [cache.SetReflectorMetricsProvider](https://pkg.go.dev/k8s.io/client-go/tools/cache#SetReflectorMetricsProvider) through which we can set a metrics provider and expose exhaustive metrics around workqueue, listing and the watches.

I was able to [find some use-cases of this](https://sourcegraph.com/search?q=context:global+cache.SetReflectorMetricsProvider&patternType=literal), and most of them seem to use prometheus (which we want). Should we use that? or should that be in a separate PR? 🤔

**Review by Pothulapati — APPROVED** [review]
LGTM, as the above suggestion seems to have been removed  https://github.com/kubernetes/client-go/commit/a1320a3a472a94bbf467d743f845b1269fc0398e

**Review by kleimkuhler — APPROVED** [review]
Looks good and works well for me 👍

**Pull request merged**
