### PR TITLE
docker-build-proxy: make apt work behind proxy

### PR DESCRIPTION
**Pull request by joakimr-axis**
This patch sends the proxy settings to docker build if present.
Without this, the docker build will fail on apt-get update on a
system that is behind a proxy.

Change-Id: I3fcbad4d9a9c30e5f0a00f03c6d8629ed8cc97b0
Signed-off-by: Joakim Roubert <joakimr@axis.com>

### CODE REVIEW

**Comment by adleong** [comment]
Thanks, @joakimr-axis!  I'm trying to determine if this is broadly applicable to many Linkerd developers or if it's more of a special case to your workflow.  I don't have a good sense of how common it is to run behind a proxy like this.  I've personally never run into it.  It might be helpful to hear if anyone else has.

Regardless of whether this gets merged, of course there's nothing stopping you from using your own build scripts that work for your environment.

**Comment by joakimr-axis** [comment]
> Thanks, @joakimr-axis! I'm trying to determine if this is broadly applicable to many Linkerd developers or if it's more of a special case to your workflow.

When it comes to corporate level, at least, many developers find themselves behind web proxies.

> Regardless of whether this gets merged, of course there's nothing stopping you from using your own build scripts that work for your environment.

Of course not! :-) But I always try to share back to the community when there are things I believe others can have use for.

When it comes to this patch, it will work just the same for people who do not sit behind proxies, while it will work for those who are behind one (as opposed to current master).

**Comment by joakimr-axis** [comment]
> 
> When I ran the script on my mac, I got an `unbound variable`

Yes, I overlooked the set -u part in the script, sorry about that and thank you for pointing it out. I have now added the means to handle that properly in the latest update.

**Comment by cpretzer** [comment]
@joakimr-axis this looks better for sure!

I think a bit more modularity and validation would be nice

Currently the docker build command is executed with empty `build-arg` parameters like this:

```
docker build /Users/cpretzer/projects/linkerd2/linkerd2 -t gcr.io/linkerd-io/proxy:some-tag -f /Users/cpretzer/projects/linkerd2/linkerd2/Dockerfile-proxy --build-arg LINKERD_VERSION=my-linkerd-version --build-arg http_proxy= --build-arg https_proxy= --build-arg no_proxy=
```

Instead, I'd like to see the build command omit empty arguments, like this:

```
docker build /Users/cpretzer/projects/linkerd2/linkerd2 -t gcr.io/linkerd-io/proxy:some-tag -f /Users/cpretzer/projects/linkerd2/linkerd2/Dockerfile-proxy --build-arg LINKERD_VERSION=my-linkerd-version
```

In the case where the `http_proxy` environment variable is set, it should be appended to the build command and the unset arguments should be omitted:

```
docker build /Users/cpretzer/projects/linkerd2/linkerd2 -t gcr.io/linkerd-io/proxy:some-tag -f /Users/cpretzer/projects/linkerd2/linkerd2/Dockerfile-proxy --build-arg LINKERD_VERSION=my-linkerd-version --build-arg http_proxy=http://my-proxy
```

Currently, when I set only the `http_proxy` argument, I see this build command:

```
docker build /Users/cpretzer/projects/linkerd2/linkerd2 -t gcr.io/linkerd-io/proxy:some-tag -f /Users/cpretzer/projects/linkerd2/linkerd2/Dockerfile-proxy --build-arg LINKERD_VERSION=my-linkerd-version --build-arg http_proxy=http://my-proxy --build-arg https_proxy= --build-arg no_proxy=
```

**Comment by joakimr-axis** [comment]
> Currently, when I set only the `http_proxy` argument, I see this build command:
> 
> ```
> docker build /Users/cpretzer/projects/linkerd2/linkerd2 -t gcr.io/linkerd-io/proxy:some-tag -f /Users/cpretzer/projects/linkerd2/linkerd2/Dockerfile-proxy --build-arg LINKERD_VERSION=my-linkerd-version --build-arg http_proxy=http://my-proxy --build-arg https_proxy= --build-arg no_proxy=
> ```

Yes, and that was the intention (keeping the script simple). With the docker build getting empty variables, it would act like it would with the variables not set although it would not be _exactly_ the same as not sending them at all.

> In the case where the `http_proxy` environment variable is set, it should be appended to the build command and the unset arguments should be omitted:

N.P., I can fix that.

**Pull request merged**
