### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by RicardoNalesAmato**
Add Tradeshift to the Linkerd 2 adopters list

### CODE REVIEW

**Review by Pothulapati — COMMENTED** [review]
Heyyy, Thanks for the PR. :)

Can you make sure that the new addition is in the alphabetical order.

**Comment by kleimkuhler** [comment]
@RicardoNalesAmato if you can also update your commit to follow the [DCO guidelines](https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) that will allow CI to pass. Thanks!

**Comment by RicardoNalesAmato** [comment]
@Pothulapati @kleimkuhler Thanks for the comments! I have corrected the PR, should be good now :)

**Comment by alpeb** [comment]
The new CI failures are unrelated to the PR. I'll address that separately and let you know :wink:

**Comment by alpeb** [comment]
@RicardoNalesAmato Please merge the `main` branch into this PR in order to pick the CI fix, and it should be ready to go :-)

**Review by Pothulapati — APPROVED** [review]
LGTM :shipit:

**Review by alpeb — APPROVED** [review]

**Pull request merged**
