### PR TITLE
feat(linkerd2-cni): allow adding extra initContainers to the daemonset

### PR DESCRIPTION
**Pull request by mhulscher**
This PR would allow users to add extra initContainers to the linkerd2-cni daemonset. This can be used, for example, to wait for the existence of a file, before starting the installation of the linkerd2-cni.

Helps with race conditions like
https://github.com/linkerd/linkerd2/issues/2219
https://github.com/linkerd/linkerd2/issues/4789

### CODE REVIEW

**Comment by adleong** [comment]
Hi @mhulscher!  We recommend using something like kustomize to customize the Linkerd configurations rather than editing the chart directly like this.  See: https://linkerd.io/2.10/tasks/customize-install/

Does that seem like it would satisfy your use-case?

**Comment by mhulscher** [comment]
Hi @adleong , it would unfortunately not satisfy our use-case. We use helm exclusively to install all of our applications.

**Comment by adleong** [comment]
Helm supports tools like kustomize through the use of post-rendering: https://helm.sh/docs/topics/advanced/#post-rendering

**Comment by mhulscher** [comment]
Definitely not something I look forward to doing 😅 Is there a reason why updating the helm-chart is not preferred? Is helm not a supported / recommended way of installing linkerd2 ?

**Comment by adleong** [comment]
Helm is definitely a supported and recommended way of installing Linkerd2.  We just want to keep our Helm charts as simple, focused, and supportable as possible.  Tools like Kustomize are the recommended way to customize the charts to your specific needs.

**Comment by mhulscher** [comment]
Hi @adleong ,

Regarding
> Tools like Kustomize are the recommended way to customize the charts to your specific needs.

I understand where you're coming from. Maintaining a sprawling values.yaml inside a chart can be pain. However, kustomize does not and will not fit within our way of working. We consider helm-charts to be the definitive artifact for installing a solution inside Kubernetes.

This PR could offer a fix/workaround for users that are affected by the issues I linked and can offer real value. I don't believe that this PR will significantly increase the burden of maintenance. But opinions differ. Is there no way this functionality can be added to chart? If not, I see ourselves forced to fork the chart and to maintain a local copy.

**Comment by adleong** [comment]
Hi @mhulscher, I've discussed this further with some of the other maintainers and we can definitely see how applying these modifications on topic of the Helm template with Kustomize can be awkward.  

There are some test failures on this branch that need to be fixed up, but once those are taken care of, I think we can accept this PR.  Thank you for your patience!

**Comment by mhulscher** [comment]
@adleong that's great to hear! I feel like I have to update the golden files, but the command that I previously used `go test ./... -update` doesn't seem to work. Can you maybe point me in the right direction?

**Comment by kleimkuhler** [comment]
@mhulscher It looks like these are actual test failures. The template is trying to get the length of a nil pointer in the template. I fixed this locally with the following diff:

```
diff --git a/charts/linkerd2-cni/templates/cni-plugin.yaml b/charts/linkerd2-cni/templates/cni-plugin.yaml
index 3d2145e55..6f87a1f13 100644
--- a/charts/linkerd2-cni/templates/cni-plugin.yaml
+++ b/charts/linkerd2-cni/templates/cni-plugin.yaml
@@ -198,7 +198,7 @@ spec:
       {{- if .Values.priorityClassName }}
       priorityClassName: {{ .Values.priorityClassName }}
       {{- end }}
-      {{- if gt (len .Values.extraInitContainers) 0 }}
+      {{- if .Values.extraInitContainers }}
       initContainers:
       {{- toYaml .Values.extraInitContainers | nindent 6 }}
       {{- end }}
diff --git a/charts/linkerd2-cni/values.yaml b/charts/linkerd2-cni/values.yaml
index 02ec41080..51a76c2eb 100644
--- a/charts/linkerd2-cni/values.yaml
+++ b/charts/linkerd2-cni/values.yaml
@@ -47,7 +47,7 @@ priorityClassName: ""
 imagePullSecrets:
 
 # -- Add additional initContainers to the daemonset
-extraInitContainers: []
+extraInitContainers:
 # - name: wait-for-other-cni
 #   image: busybox:1.33
 #   command:
```

**Comment by mhulscher** [comment]
@kleimkuhler looks like those broken tests pass now. However, there's a diff in the README which causes a test to fail. That's because I used helm-docs v1.5.0. Do you want me to use 1.4.0 or is the PR acceptable in its current form?

**Comment by kleimkuhler** [comment]
@mhulscher You can run `bin/helm-docs` from within the repo. That will use the correct version and fix the issue.

**Review by kleimkuhler — APPROVED** [review]
Awesome thanks @mhulscher for all the discussion on this. It looks good.

**Comment by mhulscher** [comment]
No problem. Thanks for helping out.

**Review by alpeb — APPROVED** [review]
LGTM, thanks @mhulscher ! :+1:

**Pull request merged**
