### PR TITLE
policy-controller: Use `openssl` instead of `rustls`

### PR DESCRIPTION
**Pull request by olix0r**
The Rustls/Ring/Webpki crates have issues communicating with a variety
of Kubernetes clusters. This change modifes the policy-controller's
default TLS implementation to use `libssl` (as provided by the
`distroless:base` container image).

### CODE REVIEW

**Comment by hawkw** [comment]
it looks like the commit intended to change the base image didn't actually change any files?

**Comment by olix0r** [comment]
@hawkw no changes to the base image are necessary. 7089164 is intentionally empty to update the commit message (so it's easier to include on squash)

**Comment by hawkw** [comment]
ohh, got it!

**Review by hawkw — APPROVED** [review]
👍

**Comment by olix0r** [comment]
Fixes #7217 #7275

We should wait for feedback on the above issues before merging.

**Review by kleimkuhler — APPROVED** [review]

**Pull request merged**
