### PR TITLE
Add timeout and failureThreshold to multicluster probe

### PR DESCRIPTION
**Pull request by alpeb**
This adds the `probeSpec.failureThreshold` and `probeSpec.timeout` fields to the Link CRD spec.

Likewise, the `gateway.probe.failureThreshold` and `gateway.probe.timeout` fields are added to the linkerd-multicluster chart, that are used to populate the new `mirror.linkerd.io/probe-failure-threshold` and `mirror.linkerd.io/probe-timeout` annotations in the gateway service (consumed by `linkerd mc link` to populate probe spec).

In the probe worker, we replace the hard-coded 50s timeout with the new timeout config (which now defaults to 30s). And the probe loop got refactored in order to not mark the gateway as unhealty until the consecutive failures threshold is reached.

### CODE REVIEW

**Review by adleong — COMMENTED** [review]
This looks good but I have questions about the defaults (which preceded this PR).  A probe timeout of 30s but interval of 3s means that in the case of a timeout, many probe requests will pile up, right?  It seems like the interval should be at least as long as the timeout.

**Comment by alpeb** [comment]
Good insight :+1:, yes I've observed a pile up of one request when timeouts occur; the ticker goroutine blocks on run() consuming `probeTicker.C`, but that has a capacity of one, which is generating the piling up.
If we increase the probe interval that'll affect the non-failed use case as well. WDYT about just removing the buffer on that channel so both goroutines become completely synchronized?

**Comment by adleong** [comment]
That would essentially amount to removing the ticker and simply waiting the jittered period after each probe completes (successfully or unsuccessfully).  This could work, but it seems a bit unintuitive that the rate of probes would change depending on how quickly probes are returning.  I'm not familiar with any other probe systems that do this.

More straightforward would be to increase the probe period to be longer than the timeout.  Do we really need a 3 second period?  Our timeout suggests that probes could take up to 30s to respond which means that we can't really react to liveness changes faster than that anyway.

**Comment by alpeb** [comment]
> That would essentially amount to removing the ticker and simply waiting the jittered period after each probe completes (successfully or unsuccessfully). This could work, but it seems a bit unintuitive that the rate of probes would change depending on how quickly probes are returning. I'm not familiar with any other probe systems that do this.

Under normal circumstances and with the default config, probes are triggered every 3s to 3.3s (accounting for jitter). I don't expect the probe to take more than that. This rate remains constant unless we're dealing with a pathological case where the probes take more than those 3s, in which case the following probe will be triggered immediately.

> More straightforward would be to increase the probe period to be longer than the timeout. Do we really need a 3 second period? Our timeout suggests that probes could take up to 30s to respond which means that we can't really detect liveness changes faster than that anyway.

I think those long probes are not the common case. Increasing the probe period would introduce an unnecessary liveness delay for the base case IMO.

**Review by adleong — APPROVED** [review]
I don't want to block this PR on these values which predate this change.  But I still think that having a period which is shorter than the timeout leads to some pretty unexpected properties.

**Pull request merged**
