### PR TITLE
Adds logFormat and logLevel values for proxy-init (#6881)

### LINKED ISSUE #6881: Support json log format in linkerd-proxy-init
### What problem are you trying to solve?
Unifying all my logs in json format, including linkerd-proxy-init.

### How should the problem be solved?
There is precedent in `linkerd2`:

The main helm chart for linkerd supports log formats (plain and json) for the controller (`controllerLogFormat`) and the proxy (`proxy.logFormat`).  Either `proxyInit.logFormat` should be added, or proxy-init should obey `proxy.logFormat`.

What do you want to happen? Add any considered drawbacks.
Add support for the same json logging functionality into linkerd-proxy-init as well as the linkerd helm chart.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?
Setting the new log format field in linkerd helm chart to `json`.  Or, possibly, through the existing `proxy.logFormat` helm chart field.

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

### PR DESCRIPTION
**Pull request by gusfcarvalho**
This PR adds changes in partials and values.yaml to allow the optional flags `log-level` and `log-format` to proxy-init.

This approach was used to have backwards compatibility between different linkerd-proxy-init images without needing to change helm charts.

Related to https://github.com/linkerd/linkerd2-proxy-init/pull/47

Fixes #6881

Signed-off-by: Gustavo Carvalho <gusfcarvalho@gmail.com>

### CODE REVIEW

**Review by alpeb — COMMENTED** [review]
Thanks again @gusfcarvalho !

These new settings are working as expected when tailing the logs from the control plane components. But it's not for other pods injected by the injector (the flags aren't getting added). I believe you still need to add corresponding entries into `pkg/charts/linkerd/values.go` for the settings to be picked up.

FYI I've just published a new proxy-init release v1.4.1 containing your changes there, and I also raised #7010 to have the control plane pick that version up :wink:

**Comment by alpeb** [comment]
The remaining change is trivial, so if there is no further interest in completing this PR, I'd be glad to take it across the finish line :wink:

**Comment by gusfcarvalho** [comment]
sorry all, somehow these notifications started to go to spam :( I think I'll try to finish today, if I cannot, I'll just hand it over to you, so I'm not a blocker more than I already have been :(

**Comment by alpeb** [comment]
Thanks @gusfcarvalho , could you also please merge `main` into this branch and fix the conflicts? (the easiest is to either accept all the changes in either `main` or this branch without dealing with each conflict, and then run `go test -update` and `bin/helm-docs` again).

**Comment by gusfcarvalho** [comment]
There you go! I think that should cover it all now =) Sorry again for the delay.

**Review by alpeb — APPROVED** [review]
This looks good to me, thanks @gusfcarvalho !

**Review by kleimkuhler — APPROVED** [review]
Great thanks @gusfcarvalho this works well!

**Pull request merged**
